/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/erik/.choosenim/toolchains/nim-0.18.0/lib -o /home/erik/Code/TFG/void/NimVoid/src/nimcache/codegen.o /home/erik/Code/TFG/void/NimVoid/src/nimcache/codegen.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdlib.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_M3y5mHl2OtcVFI81N2j0DQ tyTuple_M3y5mHl2OtcVFI81N2j0DQ;
typedef struct tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ;
typedef struct tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw;
typedef struct tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q;
typedef struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw;
typedef struct tySequence_g8wWagWtbBE4jkij9axgDjA tySequence_g8wWagWtbBE4jkij9axgDjA;
typedef struct tyTuple_p7Uw0BAWm1JV3F8w0mhMOA tyTuple_p7Uw0BAWm1JV3F8w0mhMOA;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_49cSLhOXtIXPXzKKaGFU0eQ tySequence_49cSLhOXtIXPXzKKaGFU0eQ;
typedef struct tySequence_rl1wTgiGRBZamH1pllm1bA tySequence_rl1wTgiGRBZamH1pllm1bA;
typedef struct tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg;
typedef struct tyObject_Table_zjMaDBasw1LnKbj11akpfw tyObject_Table_zjMaDBasw1LnKbj11akpfw;
typedef struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og tySequence_pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct TNimType TNimType;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA;
typedef struct RootObj RootObj;
typedef struct TNimNode TNimNode;
typedef struct tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ;
typedef struct tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg;
typedef struct tyObject_BooleanValuecolonObjectType__ygkSdrtwKhJuVTe5ua9b39aA tyObject_BooleanValuecolonObjectType__ygkSdrtwKhJuVTe5ua9b39aA;
typedef struct tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ;
typedef struct tySequence_9bpx44aFIusE9bW4FLAgSGhA tySequence_9bpx44aFIusE9bW4FLAgSGhA;
typedef struct tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g;
typedef struct tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg;
typedef struct tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A;
typedef struct tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ;
typedef struct tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ;
typedef struct tyTuple_KWcIY9c1klZQizoiQC0yHOg tyTuple_KWcIY9c1klZQizoiQC0yHOg;
typedef struct tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q;
typedef struct tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw;
typedef struct tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ;
typedef struct tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA;
typedef struct tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ;
typedef struct tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A;
typedef struct tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg;
typedef struct tySequence_x9cl451W8JtBGbwWydXa7PQ tySequence_x9cl451W8JtBGbwWydXa7PQ;
typedef struct tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA;
typedef struct tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA;
typedef struct tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw;
typedef struct tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg;
typedef struct tySequence_q5SKz0XShJtOaiDC4VrjTA tySequence_q5SKz0XShJtOaiDC4VrjTA;
typedef struct tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw;
typedef struct tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA;
typedef struct tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ;
typedef struct tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ;
typedef struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw;
typedef struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ tySequence_JAV0yhDlrNFYdAVDw2r39bQ;
typedef struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ tyTuple_zXBGqNygOt4DlBCAX3NcVQ;
typedef NU8 tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_Table_zjMaDBasw1LnKbj11akpfw {
tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* data;
NI counter;
};
struct tyTuple_M3y5mHl2OtcVFI81N2j0DQ {
tySequence_g8wWagWtbBE4jkij9axgDjA* Field0;
tySequence_49cSLhOXtIXPXzKKaGFU0eQ* Field1;
tySequence_rl1wTgiGRBZamH1pllm1bA* Field2;
tyObject_Table_zjMaDBasw1LnKbj11akpfw Field3;
NI Field4;
NI Field5;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw {
  RootObj Sup;
};
struct tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NF value;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ {
  RootObj Sup;
};
struct tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
NF value;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NimStringDesc* value;
};
struct tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
NimStringDesc* value;
};
struct tyObject_BooleanValuecolonObjectType__ygkSdrtwKhJuVTe5ua9b39aA {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NIM_BOOL value;
};
struct tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
NIM_BOOL value;
};
struct tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tySequence_9bpx44aFIusE9bW4FLAgSGhA* values;
};
struct tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
};
struct tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw {
  RootObj Sup;
};
struct tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
struct tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
typedef NU8 tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A;
struct tyTuple_KWcIY9c1klZQizoiQC0yHOg {
tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A Field0;
NI Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
};
struct tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg operator_0;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* right;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg operator_0;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* left;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* right;
};
struct tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg name;
};
struct tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg name;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* value;
};
struct tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg name;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* index;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* value;
};
struct tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg operator_0;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* left;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* right;
};
struct tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
struct tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tySequence_x9cl451W8JtBGbwWydXa7PQ* body;
};
struct tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* condition;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
struct tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* condition;
tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* thenBranch;
tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* elseBranch;
};
struct tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* condition;
tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* body;
};
struct tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tySequence_q5SKz0XShJtOaiDC4VrjTA* arguments;
tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* body;
};
struct tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg keyword;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* value;
};
struct tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* callee;
tyTuple_KWcIY9c1klZQizoiQC0yHOg paren;
tySequence_9bpx44aFIusE9bW4FLAgSGhA* arguments;
};
struct tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tySequence_q5SKz0XShJtOaiDC4VrjTA* arguments;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
struct tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg item;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* index;
};
struct tyTuple_p7Uw0BAWm1JV3F8w0mhMOA {
tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw Field0;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field1;
};
struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw {
tySequence_JAV0yhDlrNFYdAVDw2r39bQ* data;
NI counter;
};
struct tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg {
tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw Field0;
NI Field1;
};
struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
};
struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ {
NI Field0;
NimStringDesc* Field1;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field2;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_g8wWagWtbBE4jkij9axgDjA {
  TGenericSeq Sup;
  tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* data[SEQ_DECL_SIZE];
};
struct tySequence_49cSLhOXtIXPXzKKaGFU0eQ {
  TGenericSeq Sup;
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* data[SEQ_DECL_SIZE];
};
struct tySequence_rl1wTgiGRBZamH1pllm1bA {
  TGenericSeq Sup;
  tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* data[SEQ_DECL_SIZE];
};
struct tySequence_x9cl451W8JtBGbwWydXa7PQ {
  TGenericSeq Sup;
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* data[SEQ_DECL_SIZE];
};
struct tySequence_q5SKz0XShJtOaiDC4VrjTA {
  TGenericSeq Sup;
  tyTuple_KWcIY9c1klZQizoiQC0yHOg data[SEQ_DECL_SIZE];
};
struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og {
  TGenericSeq Sup;
  tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tySequence_9bpx44aFIusE9bW4FLAgSGhA {
  TGenericSeq Sup;
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* data[SEQ_DECL_SIZE];
};
struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ {
  TGenericSeq Sup;
  tyTuple_zXBGqNygOt4DlBCAX3NcVQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, codegen_HAf1eaZa49buZ74UHeiEXAQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_K58RXI9bdKFzN29blMRc19beA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_k647zAl9aqjPz9bhxBhsmc9ag)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q* n);
N_LIB_PRIVATE N_NIMCALL(void, add_E3g4xDBK9cp2YYvK9cfQDRDg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw kind, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value);
N_LIB_PRIVATE N_NIMCALL(tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*, newInstruction_v3erJGxJlXuevon1DXWGig)(tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw kind, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, codegen_snz9a9cyYwhPId3NP6wd0Zxg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ* n);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, codegen_aYYJTR6Gkr9aZzVsuT0X8Xw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_SRUl0VvFhaGkrP5tr7XBvA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_e5bkuvgkJIs0vTYM9bKJnrw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_izJfw0844YpaxTlRQ8YavA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_qm5IhTMx3hsNN5wPevfGqg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A* n);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NIMCALL(void, codegen_ZOjI1MgjgV0FtYr9aE89auGg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_tg4SzdMw6QTdCu51V4Mcrw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ* n);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, codegen_udSnc9bFfz59cc1zJwqP4bPw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_RS4jLNLeoVPIqwdbsXBPbA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_N2BXiaPWJPLPVkCy1sS0zA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_mLcnGwCt2J4iwCyLG2CyCw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_CquNSooQ6eHzD9anpHxraGQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_HlWNUdGT9bAxs8VxgNG8iEA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_yB80YqnH9bY7gy8un6EBw6w)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_40eAnmhyopV809a9aWd9cVY4w)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_s9c9cOo1X9b6u0Dc39aUGR2guw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA* n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, tempLabel_4BbOJaErQoxvC9cm3k9cGHvA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm);
N_LIB_PRIVATE N_NIMCALL(void, codegen_6toYxA03r49bqYQQc1FkGFw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_w8hfJOqNE0oYLypDshgbMQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_hi9c9cD78swm2LWcXfXdZ9c1g)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_BFfT8tdjP39a9cl9ac0YyRV4A)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_WrjWETWKYgx8HGlnhmi9aSQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_M9ceZlVu2XxX2ox9aPMJz9blA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ* n);
N_LIB_PRIVATE N_NIMCALL(void, codegen_TwiAnoKB2pOqRb40Hub1Qg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ* n);
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_gOxHjz9bS5yarbZPfCpiI9ag_;
extern TNimType NTI_560SkOiRWWBbF6rm9aw64dA_;
extern TNimType NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_;
extern TNimType NTI_PO9bUMXtlWXaezrslbDbWhQ_;
extern TNimType NTI_f5gWzHwMtmnTXyOKmj74kA_;
extern TNimType NTI_ygkSdrtwKhJuVTe5ua9b39aA_;
extern TNimType NTI_wxtX2Dn9bLzkwATjviHoHPw_;
extern TNimType NTI_tKCpk3v6uzTPdzngd4khKg_;
extern TNimType NTI_3MoUzdd6JpcZ1tSX82rd2Q_;
static TNimType* Nim_OfCheck_CACHE3[2];
extern TNimType NTI_H6QC3PBmhdJSmT9cDaRWAAQ_;
static TNimType* Nim_OfCheck_CACHE4[2];
extern TNimType NTI_TeU0tViLpeWJ89cheW1wFUg_;
static TNimType* Nim_OfCheck_CACHE5[2];
extern TNimType NTI_5n4g9cmeh9b6y5ArRowKRuIQ_;
static TNimType* Nim_OfCheck_CACHE6[2];
extern TNimType NTI_xzysDaRkx9b8cniE9aTMy37g_;
static TNimType* Nim_OfCheck_CACHE7[2];
extern TNimType NTI_WJW05mFVFR8R5Re1RdwjkQ_;
static TNimType* Nim_OfCheck_CACHE8[2];
extern TNimType NTI_qHyvSBqcF0iFkrOEJDqLyQ_;
static TNimType* Nim_OfCheck_CACHE9[2];
extern TNimType NTI_dqD3ROdpQFuI6y9a2nYB32Q_;
static TNimType* Nim_OfCheck_CACHE10[2];
extern TNimType NTI_kRnNrqDqgCDbcfyCYJWfkw_;
static TNimType* Nim_OfCheck_CACHE11[2];
extern TNimType NTI_rw8DvbXrFC9cPt2Vhqv9clxQ_;
static TNimType* Nim_OfCheck_CACHE12[2];
extern TNimType NTI_K9aIg0VZvCzVPoXP2BYctmw_;
static TNimType* Nim_OfCheck_CACHE19[2];
STRING_LITERAL(TM_0BUMaz53LighJcSfEhiVog_13, "Error generating code for unary operator", 40);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_0BUMaz53LighJcSfEhiVog_12 = {((NimStringDesc*) &TM_0BUMaz53LighJcSfEhiVog_13)}
;
STRING_LITERAL(TM_0BUMaz53LighJcSfEhiVog_15, "Error generating code for a binary operator", 43);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_0BUMaz53LighJcSfEhiVog_14 = {((NimStringDesc*) &TM_0BUMaz53LighJcSfEhiVog_15)}
;
STRING_LITERAL(TM_0BUMaz53LighJcSfEhiVog_17, "Error generating code for a logical operator", 44);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_0BUMaz53LighJcSfEhiVog_16 = {((NimStringDesc*) &TM_0BUMaz53LighJcSfEhiVog_17)}
;

N_LIB_PRIVATE N_NIMCALL(void, codegen_HAf1eaZa49buZ74UHeiEXAQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* n) {
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_K58RXI9bdKFzN29blMRc19beA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* n) {
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(void, add_E3g4xDBK9cp2YYvK9cfQDRDg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw kind, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value) {
	tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T1_;
	NI T2_;
	T1_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
	T1_ = newInstruction_v3erJGxJlXuevon1DXWGig(kind, value);
	(*vm).Field0 = (tySequence_g8wWagWtbBE4jkij9axgDjA*) incrSeqV2(&((*vm).Field0)->Sup, sizeof(tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*));
	T2_ = (*vm).Field0->Sup.len++;
	asgnRef((void**) (&(*vm).Field0->data[T2_]), T1_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_k647zAl9aqjPz9bhxBhsmc9ag)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q* n) {
	tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA* T1_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T2_;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T1_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*)0;
	T1_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) newObj((&NTI_gOxHjz9bS5yarbZPfCpiI9ag_), sizeof(tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA));
	(*T1_).Sup.Sup.m_type = (&NTI_560SkOiRWWBbF6rm9aw64dA_);
	(*T1_).value = (*n).value;
	T2_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T2_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T2_);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_snz9a9cyYwhPId3NP6wd0Zxg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ* n) {
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1((*n).value);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T3_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_aYYJTR6Gkr9aZzVsuT0X8Xw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg* n) {
	tyObject_BooleanValuecolonObjectType__ygkSdrtwKhJuVTe5ua9b39aA* T1_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T2_;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T1_ = (tyObject_BooleanValuecolonObjectType__ygkSdrtwKhJuVTe5ua9b39aA*)0;
	T1_ = (tyObject_BooleanValuecolonObjectType__ygkSdrtwKhJuVTe5ua9b39aA*) newObj((&NTI_f5gWzHwMtmnTXyOKmj74kA_), sizeof(tyObject_BooleanValuecolonObjectType__ygkSdrtwKhJuVTe5ua9b39aA));
	(*T1_).Sup.Sup.m_type = (&NTI_ygkSdrtwKhJuVTe5ua9b39aA_);
	(*T1_).value = (*n).value;
	T2_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T2_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T2_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_SRUl0VvFhaGkrP5tr7XBvA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ* n) {
	NI i;
	NI T1_;
	tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA* T4_;
	NI T5_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T6_;
	T1_ = ((*n).values ? (*n).values->Sup.len : 0);
	i = (NI)(T1_ - ((NI) 1));
	{
		while (1) {
			if (!(((NI) 0) <= i)) goto LA3;
			codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).values->data[i]);
			i -= ((NI) 1);
		} LA3: ;
	}
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 35), NIM_NIL);
	T4_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*)0;
	T4_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) newObj((&NTI_gOxHjz9bS5yarbZPfCpiI9ag_), sizeof(tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA));
	(*T4_).Sup.Sup.m_type = (&NTI_560SkOiRWWBbF6rm9aw64dA_);
	T5_ = ((*n).values ? (*n).values->Sup.len : 0);
	(*T4_).value = ((NF) (T5_));
	T6_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T6_ = &T4_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T6_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_izJfw0844YpaxTlRQ8YavA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g* n) {
	tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg* T1_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T2_;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T1_ = (tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg*)0;
	T1_ = (tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg*) newObj((&NTI_wxtX2Dn9bLzkwATjviHoHPw_), sizeof(tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg));
	(*T1_).Sup.Sup.m_type = (&NTI_tKCpk3v6uzTPdzngd4khKg_);
	T2_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T2_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T2_);
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA15_: ;
	result = isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_qm5IhTMx3hsNN5wPevfGqg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A* n) {
	tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* ex;
{	ex = (*n).expression;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_3MoUzdd6JpcZ1tSX82rd2Q_), Nim_OfCheck_CACHE3)))) goto LA3_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_H6QC3PBmhdJSmT9cDaRWAAQ_), Nim_OfCheck_CACHE4)))) goto LA6_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_TeU0tViLpeWJ89cheW1wFUg_), Nim_OfCheck_CACHE5)))) goto LA9_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA9_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_5n4g9cmeh9b6y5ArRowKRuIQ_), Nim_OfCheck_CACHE6)))) goto LA12_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA12_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_xzysDaRkx9b8cniE9aTMy37g_), Nim_OfCheck_CACHE7)))) goto LA15_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA15_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_WJW05mFVFR8R5Re1RdwjkQ_), Nim_OfCheck_CACHE8)))) goto LA18_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA18_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_qHyvSBqcF0iFkrOEJDqLyQ_), Nim_OfCheck_CACHE9)))) goto LA21_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA21_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_dqD3ROdpQFuI6y9a2nYB32Q_), Nim_OfCheck_CACHE10)))) goto LA24_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA24_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_kRnNrqDqgCDbcfyCYJWfkw_), Nim_OfCheck_CACHE11)))) goto LA27_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA27_: ;
	{
		if (!((ex) && (isObjWithCache((*ex).Sup.m_type, (&NTI_rw8DvbXrFC9cPt2Vhqv9clxQ_), Nim_OfCheck_CACHE12)))) goto LA30_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA30_: ;
	LA1_: ;
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).expression);
	}BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_ZOjI1MgjgV0FtYr9aE89auGg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ* n) {
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).expression);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_tg4SzdMw6QTdCu51V4Mcrw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ* n) {
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).right);
	switch ((*n).operator_0.Field0) {
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 17):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 8), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 1):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 7), NIM_NIL);
	}
	break;
	default:
	{
		echoBinSafe(TM_0BUMaz53LighJcSfEhiVog_12, 1);
		exit(((NI) 0));
	}
	break;
	}
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_udSnc9bFfz59cc1zJwqP4bPw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q* n) {
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).left);
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).right);
	switch ((*n).operator_0.Field0) {
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 11), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 1):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 12), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 2):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 13), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 3):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 14), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 4):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 15), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 16):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 16), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 18):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 17), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 19):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 18), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 20):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 19), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 21):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 20), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 22):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 21), NIM_NIL);
	}
	break;
	default:
	{
		echoBinSafe(TM_0BUMaz53LighJcSfEhiVog_14, 1);
		exit(((NI) 0));
	}
	break;
	}
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_RS4jLNLeoVPIqwdbsXBPbA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw* n) {
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 27), NIM_NIL);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1((*n).name.Field2);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T3_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_N2BXiaPWJPLPVkCy1sS0zA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ* n) {
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).value);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 26), NIM_NIL);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1((*n).name.Field2);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T3_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_mLcnGwCt2J4iwCyLG2CyCw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA* n) {
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).index);
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).value);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 39), NIM_NIL);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1((*n).name.Field2);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T3_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_CquNSooQ6eHzD9anpHxraGQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ* n) {
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).left);
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).right);
	switch ((*n).operator_0.Field0) {
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 29):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 9), NIM_NIL);
	}
	break;
	case ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 28):
	{
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 10), NIM_NIL);
	}
	break;
	default:
	{
		echoBinSafe(TM_0BUMaz53LighJcSfEhiVog_16, 1);
		exit(((NI) 0));
	}
	break;
	}
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_HlWNUdGT9bAxs8VxgNG8iEA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A* n) {
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).expression);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 5), NIM_NIL);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_yB80YqnH9bY7gy8un6EBw6w)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* n) {
	{
		tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* i;
		tySequence_x9cl451W8JtBGbwWydXa7PQ* colontmp_;
		NI i_2;
		NI L;
		NI T2_;
		i = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
		colontmp_ = (tySequence_x9cl451W8JtBGbwWydXa7PQ*)0;
		colontmp_ = (*n).body;
		i_2 = ((NI) 0);
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				if (!(i_2 < L)) goto LA4;
				i = colontmp_->data[i_2];
				codegen_40eAnmhyopV809a9aWd9cVY4w(vm, i);
				{
					if (!((i) && (isObjWithCache((*i).Sup.m_type, (&NTI_K9aIg0VZvCzVPoXP2BYctmw_), Nim_OfCheck_CACHE19)))) goto LA7_;
					goto LA1;
				}
				LA7_: ;
				i_2 += ((NI) 1);
			} LA4: ;
		}
	} LA1: ;
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_s9c9cOo1X9b6u0Dc39aUGR2guw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA* n) {
	NimStringDesc* label;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T4_;
	NimStringDesc* T5_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T6_;
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).condition);
	label = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 25), NIM_NIL);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1(label);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T3_);
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).expression);
	T4_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T4_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T4_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T5_ = (NimStringDesc*)0;
	T5_ = (*T4_).value; (*T4_).value = copyStringRC1(label);
	if (T5_) nimGCunrefNoCycle(T5_);
	T6_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T6_ = &T4_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T6_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_6toYxA03r49bqYQQc1FkGFw)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA* n) {
	{
		NimStringDesc* endLabel;
		tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T5_;
		NimStringDesc* T6_;
		tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T7_;
		tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T8_;
		tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T9_;
		NimStringDesc* T10_;
		tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T11_;
		if (!((*n).elseBranch == NIM_NIL)) goto LA3_;
		codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).condition);
		endLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 25), NIM_NIL);
		T5_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
		T5_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
		(*T5_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
		T6_ = (NimStringDesc*)0;
		T6_ = (*T5_).value; (*T5_).value = copyStringRC1(endLabel);
		if (T6_) nimGCunrefNoCycle(T6_);
		T7_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
		T7_ = &T5_->Sup;
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T7_);
		T8_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
		T8_ = &(*n).thenBranch->Sup;
		codegen_40eAnmhyopV809a9aWd9cVY4w(vm, T8_);
		T9_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
		T9_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
		(*T9_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
		T10_ = (NimStringDesc*)0;
		T10_ = (*T9_).value; (*T9_).value = copyStringRC1(endLabel);
		if (T10_) nimGCunrefNoCycle(T10_);
		T11_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
		T11_ = &T9_->Sup;
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T11_);
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringDesc* elseLabel;
		NimStringDesc* endLabel_2;
		tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T13_;
		NimStringDesc* T14_;
		tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T15_;
		tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T16_;
		tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T17_;
		NimStringDesc* T18_;
		tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T19_;
		tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T20_;
		NimStringDesc* T21_;
		tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T22_;
		tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T23_;
		tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T24_;
		NimStringDesc* T25_;
		tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T26_;
		codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).condition);
		elseLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
		endLabel_2 = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 25), NIM_NIL);
		T13_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
		T13_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
		(*T13_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
		T14_ = (NimStringDesc*)0;
		T14_ = (*T13_).value; (*T13_).value = copyStringRC1(elseLabel);
		if (T14_) nimGCunrefNoCycle(T14_);
		T15_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
		T15_ = &T13_->Sup;
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T15_);
		T16_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
		T16_ = &(*n).thenBranch->Sup;
		codegen_40eAnmhyopV809a9aWd9cVY4w(vm, T16_);
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 22), NIM_NIL);
		T17_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
		T17_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
		(*T17_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
		T18_ = (NimStringDesc*)0;
		T18_ = (*T17_).value; (*T17_).value = copyStringRC1(endLabel_2);
		if (T18_) nimGCunrefNoCycle(T18_);
		T19_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
		T19_ = &T17_->Sup;
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T19_);
		T20_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
		T20_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
		(*T20_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
		T21_ = (NimStringDesc*)0;
		T21_ = (*T20_).value; (*T20_).value = copyStringRC1(elseLabel);
		if (T21_) nimGCunrefNoCycle(T21_);
		T22_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
		T22_ = &T20_->Sup;
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T22_);
		T23_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
		T23_ = &(*n).elseBranch->Sup;
		codegen_40eAnmhyopV809a9aWd9cVY4w(vm, T23_);
		T24_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
		T24_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
		(*T24_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
		T25_ = (NimStringDesc*)0;
		T25_ = (*T24_).value; (*T24_).value = copyStringRC1(endLabel_2);
		if (T25_) nimGCunrefNoCycle(T25_);
		T26_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
		T26_ = &T24_->Sup;
		add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T26_);
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_w8hfJOqNE0oYLypDshgbMQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw* n) {
	NimStringDesc* startLabel;
	NimStringDesc* endLabel;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T4_;
	NimStringDesc* T5_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T6_;
	tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T7_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T8_;
	NimStringDesc* T9_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T10_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T11_;
	NimStringDesc* T12_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T13_;
	startLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
	endLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1(startLabel);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T3_);
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).condition);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 25), NIM_NIL);
	T4_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T4_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T4_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T5_ = (NimStringDesc*)0;
	T5_ = (*T4_).value; (*T4_).value = copyStringRC1(endLabel);
	if (T5_) nimGCunrefNoCycle(T5_);
	T6_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T6_ = &T4_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T6_);
	T7_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
	T7_ = &(*n).body->Sup;
	codegen_40eAnmhyopV809a9aWd9cVY4w(vm, T7_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 22), NIM_NIL);
	T8_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T8_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T8_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T9_ = (NimStringDesc*)0;
	T9_ = (*T8_).value; (*T8_).value = copyStringRC1(startLabel);
	if (T9_) nimGCunrefNoCycle(T9_);
	T10_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T10_ = &T8_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T10_);
	T11_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T11_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T11_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T12_ = (NimStringDesc*)0;
	T12_ = (*T11_).value; (*T11_).value = copyStringRC1(endLabel);
	if (T12_) nimGCunrefNoCycle(T12_);
	T13_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T13_ = &T11_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T13_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_hi9c9cD78swm2LWcXfXdZ9c1g)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg* n) {
	NimStringDesc* startLabel;
	NimStringDesc* endLabel;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T4_;
	NimStringDesc* T5_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T6_;
	tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA* T7_;
	NI T8_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T9_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T10_;
	NimStringDesc* T11_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T12_;
	tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T20_;
	tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg* T21_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T22_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T23_;
	NimStringDesc* T24_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T25_;
	startLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
	endLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1(startLabel);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T3_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T4_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T4_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T4_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T5_ = (NimStringDesc*)0;
	T5_ = (*T4_).value; (*T4_).value = copyStringRC1(endLabel);
	if (T5_) nimGCunrefNoCycle(T5_);
	T6_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T6_ = &T4_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T6_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T7_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*)0;
	T7_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) newObj((&NTI_gOxHjz9bS5yarbZPfCpiI9ag_), sizeof(tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA));
	(*T7_).Sup.Sup.m_type = (&NTI_560SkOiRWWBbF6rm9aw64dA_);
	T8_ = ((*n).arguments ? (*n).arguments->Sup.len : 0);
	(*T7_).value = ((NF) (T8_));
	T9_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T9_ = &T7_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T9_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 28), NIM_NIL);
	T10_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T10_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T10_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T11_ = (NimStringDesc*)0;
	T11_ = (*T10_).value; (*T10_).value = copyStringRC1(startLabel);
	if (T11_) nimGCunrefNoCycle(T11_);
	T12_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T12_ = &T10_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T12_);
	{
		tyTuple_KWcIY9c1klZQizoiQC0yHOg i;
		tySequence_q5SKz0XShJtOaiDC4VrjTA* colontmp_;
		NI i_2;
		NI L;
		NI T14_;
		memset((void*)(&i), 0, sizeof(i));
		colontmp_ = (tySequence_q5SKz0XShJtOaiDC4VrjTA*)0;
		colontmp_ = (*n).arguments;
		i_2 = ((NI) 0);
		T14_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T14_;
		{
			while (1) {
				tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T17_;
				NimStringDesc* T18_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T19_;
				if (!(i_2 < L)) goto LA16;
				i.Field0 = colontmp_->data[i_2].Field0;
				i.Field1 = colontmp_->data[i_2].Field1;
				i.Field2 = colontmp_->data[i_2].Field2;
				i.Field3 = colontmp_->data[i_2].Field3;
				add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 26), NIM_NIL);
				T17_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
				T17_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
				(*T17_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
				T18_ = (NimStringDesc*)0;
				T18_ = (*T17_).value; (*T17_).value = copyStringRC1(i.Field2);
				if (T18_) nimGCunrefNoCycle(T18_);
				T19_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T19_ = &T17_->Sup;
				add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T19_);
				i_2 += ((NI) 1);
			} LA16: ;
		}
	}
	T20_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
	T20_ = &(*n).body->Sup;
	codegen_40eAnmhyopV809a9aWd9cVY4w(vm, T20_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T21_ = (tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg*)0;
	T21_ = (tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg*) newObj((&NTI_wxtX2Dn9bLzkwATjviHoHPw_), sizeof(tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg));
	(*T21_).Sup.Sup.m_type = (&NTI_tKCpk3v6uzTPdzngd4khKg_);
	T22_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T22_ = &T21_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T22_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 31), NIM_NIL);
	T23_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T23_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T23_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T24_ = (NimStringDesc*)0;
	T24_ = (*T23_).value; (*T23_).value = copyStringRC1(endLabel);
	if (T24_) nimGCunrefNoCycle(T24_);
	T25_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T25_ = &T23_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T25_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_BFfT8tdjP39a9cl9ac0YyRV4A)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw* n) {
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).value);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 31), NIM_NIL);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_WrjWETWKYgx8HGlnhmi9aSQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA* n) {
	NI max;
	NI T1_;
	tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA* T4_;
	NI T5_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T6_;
	T1_ = ((*n).arguments ? (*n).arguments->Sup.len : 0);
	max = T1_;
	{
		while (1) {
			if (!(((NI) 0) < max)) goto LA3;
			codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).arguments->data[(NI)(max - ((NI) 1))]);
			max -= ((NI) 1);
		} LA3: ;
	}
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).callee);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T4_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*)0;
	T4_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) newObj((&NTI_gOxHjz9bS5yarbZPfCpiI9ag_), sizeof(tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA));
	(*T4_).Sup.Sup.m_type = (&NTI_560SkOiRWWBbF6rm9aw64dA_);
	T5_ = ((*n).arguments ? (*n).arguments->Sup.len : 0);
	(*T4_).value = ((NF) (T5_));
	T6_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T6_ = &T4_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T6_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 30), NIM_NIL);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_M9ceZlVu2XxX2ox9aPMJz9blA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ* n) {
	NimStringDesc* startLabel;
	NimStringDesc* endLabel;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T4_;
	NimStringDesc* T5_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T6_;
	tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA* T7_;
	NI T8_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T9_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T10_;
	NimStringDesc* T11_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T12_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T20_;
	NimStringDesc* T21_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T22_;
	startLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
	endLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1(startLabel);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T3_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T4_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T4_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T4_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T5_ = (NimStringDesc*)0;
	T5_ = (*T4_).value; (*T4_).value = copyStringRC1(endLabel);
	if (T5_) nimGCunrefNoCycle(T5_);
	T6_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T6_ = &T4_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T6_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
	T7_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*)0;
	T7_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) newObj((&NTI_gOxHjz9bS5yarbZPfCpiI9ag_), sizeof(tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA));
	(*T7_).Sup.Sup.m_type = (&NTI_560SkOiRWWBbF6rm9aw64dA_);
	T8_ = ((*n).arguments ? (*n).arguments->Sup.len : 0);
	(*T7_).value = ((NF) (T8_));
	T9_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T9_ = &T7_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T9_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 28), NIM_NIL);
	T10_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T10_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T10_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T11_ = (NimStringDesc*)0;
	T11_ = (*T10_).value; (*T10_).value = copyStringRC1(startLabel);
	if (T11_) nimGCunrefNoCycle(T11_);
	T12_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T12_ = &T10_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T12_);
	{
		tyTuple_KWcIY9c1klZQizoiQC0yHOg i;
		tySequence_q5SKz0XShJtOaiDC4VrjTA* colontmp_;
		NI i_2;
		NI L;
		NI T14_;
		memset((void*)(&i), 0, sizeof(i));
		colontmp_ = (tySequence_q5SKz0XShJtOaiDC4VrjTA*)0;
		colontmp_ = (*n).arguments;
		i_2 = ((NI) 0);
		T14_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T14_;
		{
			while (1) {
				tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T17_;
				NimStringDesc* T18_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T19_;
				if (!(i_2 < L)) goto LA16;
				i.Field0 = colontmp_->data[i_2].Field0;
				i.Field1 = colontmp_->data[i_2].Field1;
				i.Field2 = colontmp_->data[i_2].Field2;
				i.Field3 = colontmp_->data[i_2].Field3;
				add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 26), NIM_NIL);
				T17_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
				T17_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
				(*T17_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
				T18_ = (NimStringDesc*)0;
				T18_ = (*T17_).value; (*T17_).value = copyStringRC1(i.Field2);
				if (T18_) nimGCunrefNoCycle(T18_);
				T19_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T19_ = &T17_->Sup;
				add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T19_);
				i_2 += ((NI) 1);
			} LA16: ;
		}
	}
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).expression);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 31), NIM_NIL);
	T20_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T20_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T20_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T21_ = (NimStringDesc*)0;
	T21_ = (*T20_).value; (*T20_).value = copyStringRC1(endLabel);
	if (T21_) nimGCunrefNoCycle(T21_);
	T22_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T22_ = &T20_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T22_);
}

N_LIB_PRIVATE N_NIMCALL(void, codegen_TwiAnoKB2pOqRb40Hub1Qg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ* n) {
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T1_;
	NimStringDesc* T2_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T3_;
	codegen_e5bkuvgkJIs0vTYM9bKJnrw(vm, (*n).index);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 27), NIM_NIL);
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T1_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T1_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T2_ = (NimStringDesc*)0;
	T2_ = (*T1_).value; (*T1_).value = copyStringRC1((*n).item.Field2);
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T3_ = &T1_->Sup;
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T3_);
	add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 36), NIM_NIL);
}
NIM_EXTERNC N_NOINLINE(void, unknown_codegenInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_codegenDatInit000)(void) {
}

