/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/erik/.choosenim/toolchains/nim-0.18.0/lib -o /home/erik/Code/TFG/void/NimVoid/src/nimcache/frame.o /home/erik/Code/TFG/void/NimVoid/src/nimcache/frame.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg;
typedef struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw;
typedef struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ tySequence_JAV0yhDlrNFYdAVDw2r39bQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ tyTuple_zXBGqNygOt4DlBCAX3NcVQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw;
typedef struct RootObj RootObj;
struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw {
tySequence_JAV0yhDlrNFYdAVDw2r39bQ* data;
NI counter;
};
struct tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg {
tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw Field0;
NI Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ {
NI Field0;
NimStringDesc* Field1;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field2;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw {
  RootObj Sup;
};
struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ {
  TGenericSeq Sup;
  tyTuple_zXBGqNygOt4DlBCAX3NcVQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_ZJnTpp110EyOkSiqN7Yliw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
TNimType NTI_r4JoVxlxeWnXF9cuRoe3Jtg_;
extern TNimType NTI_upT1OmA0PO9bbHjDDPVn2Uw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_ZJnTpp110EyOkSiqN7Yliw_;
extern TNimType NTI_JAV0yhDlrNFYdAVDw2r39bQ_;
static N_NIMCALL(void, Marker_tyRef_ZJnTpp110EyOkSiqN7Yliw)(void* p, NI op) {
	tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* a;
	a = (tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*)p;
	nimGCvisit((void*)(*a).Field0.data, op);
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*, newFrame_nfe2NsS0Jn8q3iozdCF9c8g)(NI return_address, tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw heap) {
	tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* result;
	result = (tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*)0;
	result = (tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*) newObj((&NTI_ZJnTpp110EyOkSiqN7Yliw_), sizeof(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg));
	genericSeqAssign((&(*result).Field0.data), heap.data, (&NTI_JAV0yhDlrNFYdAVDw2r39bQ_));
	(*result).Field0.counter = heap.counter;
	(*result).Field1 = return_address;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_frameInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_frameDatInit000)(void) {
static TNimNode* TM_RIitdbkPjYqOfx0jT0j4Zg_2[2];
static TNimNode TM_RIitdbkPjYqOfx0jT0j4Zg_0[3];
NTI_r4JoVxlxeWnXF9cuRoe3Jtg_.size = sizeof(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg);
NTI_r4JoVxlxeWnXF9cuRoe3Jtg_.kind = 18;
NTI_r4JoVxlxeWnXF9cuRoe3Jtg_.base = 0;
TM_RIitdbkPjYqOfx0jT0j4Zg_2[0] = &TM_RIitdbkPjYqOfx0jT0j4Zg_0[1];
TM_RIitdbkPjYqOfx0jT0j4Zg_0[1].kind = 1;
TM_RIitdbkPjYqOfx0jT0j4Zg_0[1].offset = offsetof(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg, Field0);
TM_RIitdbkPjYqOfx0jT0j4Zg_0[1].typ = (&NTI_upT1OmA0PO9bbHjDDPVn2Uw_);
TM_RIitdbkPjYqOfx0jT0j4Zg_0[1].name = "Field0";
TM_RIitdbkPjYqOfx0jT0j4Zg_2[1] = &TM_RIitdbkPjYqOfx0jT0j4Zg_0[2];
TM_RIitdbkPjYqOfx0jT0j4Zg_0[2].kind = 1;
TM_RIitdbkPjYqOfx0jT0j4Zg_0[2].offset = offsetof(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg, Field1);
TM_RIitdbkPjYqOfx0jT0j4Zg_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_RIitdbkPjYqOfx0jT0j4Zg_0[2].name = "Field1";
TM_RIitdbkPjYqOfx0jT0j4Zg_0[0].len = 2; TM_RIitdbkPjYqOfx0jT0j4Zg_0[0].kind = 2; TM_RIitdbkPjYqOfx0jT0j4Zg_0[0].sons = &TM_RIitdbkPjYqOfx0jT0j4Zg_2[0];
NTI_r4JoVxlxeWnXF9cuRoe3Jtg_.node = &TM_RIitdbkPjYqOfx0jT0j4Zg_0[0];
NTI_ZJnTpp110EyOkSiqN7Yliw_.size = sizeof(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*);
NTI_ZJnTpp110EyOkSiqN7Yliw_.kind = 22;
NTI_ZJnTpp110EyOkSiqN7Yliw_.base = (&NTI_r4JoVxlxeWnXF9cuRoe3Jtg_);
NTI_ZJnTpp110EyOkSiqN7Yliw_.marker = Marker_tyRef_ZJnTpp110EyOkSiqN7Yliw;
}

