/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/erik/.choosenim/toolchains/nim-0.18.0/lib -o /home/erik/Code/TFG/void/NimVoid/src/nimcache/lexer.o /home/erik/Code/TFG/void/NimVoid/src/nimcache/lexer.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_I5ADwVYNrBGClFh5IRSxFw tyTuple_I5ADwVYNrBGClFh5IRSxFw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_q5SKz0XShJtOaiDC4VrjTA tySequence_q5SKz0XShJtOaiDC4VrjTA;
typedef struct tyTuple_KWcIY9c1klZQizoiQC0yHOg tyTuple_KWcIY9c1klZQizoiQC0yHOg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_Table_pntvPsgDJ7q7yAcWyvfffA tyObject_Table_pntvPsgDJ7q7yAcWyvfffA;
typedef struct tySequence_ABPSpAd6GJPBDOgnx8Xaeg tySequence_ABPSpAd6GJPBDOgnx8Xaeg;
typedef struct tyTuple_CqK5avyg59bVH4ni9ajbhfNw tyTuple_CqK5avyg59bVH4ni9ajbhfNw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A;
struct tyTuple_KWcIY9c1klZQizoiQC0yHOg {
tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A Field0;
NI Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
};
struct tyTuple_I5ADwVYNrBGClFh5IRSxFw {
NimStringDesc* Field0;
tySequence_q5SKz0XShJtOaiDC4VrjTA* Field1;
NI Field2;
NI Field3;
NI Field4;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Table_pntvPsgDJ7q7yAcWyvfffA {
tySequence_ABPSpAd6GJPBDOgnx8Xaeg* data;
NI counter;
};
struct tyTuple_CqK5avyg59bVH4ni9ajbhfNw {
NI Field0;
NimStringDesc* Field1;
tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A Field2;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_q5SKz0XShJtOaiDC4VrjTA {
  TGenericSeq Sup;
  tyTuple_KWcIY9c1klZQizoiQC0yHOg data[SEQ_DECL_SIZE];
};
struct tySequence_ABPSpAd6GJPBDOgnx8Xaeg {
  TGenericSeq Sup;
  tyTuple_CqK5avyg59bVH4ni9ajbhfNw data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_q5SKz0XShJtOaiDC4VrjTA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_dVZkeDWzk9aGQiF4blk8l8A)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAtEnd_LmZvVccof2CmOEf78oKFYg)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer);
N_LIB_PRIVATE N_NIMCALL(void, scanToken_hGh27pfCxctQGssRzChCug)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, advance_W5Oaj6fT4TwcY9cB9bNAisbw)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, peek_h4VKNPKna0k8bNYhU5nqRQ)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer, NI offset);
N_LIB_PRIVATE N_NIMCALL(void, addToken_1Vv9bcwSfPpY19cX2OsHBXyA)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer, tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A kind, NimStringDesc* value);
static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bglexer)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qlexer)(NI a, NI b);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nextIs_1X4gy8WADUqPNHC9c6SGplA)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer, NIM_CHAR expected);
N_LIB_PRIVATE N_NIMCALL(void, text_hGh27pfCxctQGssRzChCug_2)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsDigitChar)(NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, number_vsWTO0plbrzs9azuzrp3kTQ)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsAlphaAsciiChar)(NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, identifier_vsWTO0plbrzs9azuzrp3kTQ_2)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsAlphaNumericChar)(NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_4ygQFmCO3DZsQWcbRPxovg)(tyObject_Table_pntvPsgDJ7q7yAcWyvfffA t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A, X5BX5D__AMJfbib2i6SfJzvstSdk9ag)(tyObject_Table_pntvPsgDJ7q7yAcWyvfffA t, NimStringDesc* key);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, newToken_CxEPRFYDeVoM1n45VSW9bqQ)(tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A kind, NI line, NimStringDesc* lexeme, NimStringDesc* value, tyTuple_KWcIY9c1klZQizoiQC0yHOg* Result);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
TNimType NTI_I5ADwVYNrBGClFh5IRSxFw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_KWcIY9c1klZQizoiQC0yHOg_;
TNimType NTI_q5SKz0XShJtOaiDC4VrjTA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_dVZkeDWzk9aGQiF4blk8l8A_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_3, "There\'s an unterminated text at line ", 37);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_5, "while", 5);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_6, "none", 4);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_7, "true", 4);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_8, "print", 5);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_9, "if", 2);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_10, "or", 2);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_11, "false", 5);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_12, "return", 6);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_13, "for", 3);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_14, "else", 4);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_15, "and", 3);
NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple_CqK5avyg59bVH4ni9ajbhfNw data[32];
} TM_LGhhYqHVISrBY59b6oZtR9bA_16 = {{32, 32}, {{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) IL64(8683479061899664385)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_5),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 37)}
,
{((NI) IL64(-1109021522048414303)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_6),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 34)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) IL64(1906568283076584997)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_7),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 30)}
,
{((NI) IL64(7788902189690996838)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_8),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 38)}
,
{((NI) IL64(32559052130055)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_9),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 32)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) IL64(34462542094794)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_10),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 29)}
,
{((NI) IL64(4664163461661366122)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_11),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 31)}
,
{((NI) IL64(4347013207704641964)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_12),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 35)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) IL64(32892977241142227)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_13),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 36)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) IL64(-4289227729636157483)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_14),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 33)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
,
{((NI) IL64(30664327852826910)),
((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_15),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 28)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0)}
}};
NIM_CONST tyObject_Table_pntvPsgDJ7q7yAcWyvfffA TM_LGhhYqHVISrBY59b6oZtR9bA_4 = {((tySequence_ABPSpAd6GJPBDOgnx8Xaeg*)&TM_LGhhYqHVISrBY59b6oZtR9bA_16), ((NI) 11)};
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_17, "Unknown character \'", 19);
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_18, "\' found at line ", 16);
static N_NIMCALL(void, Marker_tySequence_q5SKz0XShJtOaiDC4VrjTA)(void* p, NI op) {
	tySequence_q5SKz0XShJtOaiDC4VrjTA* a;
	NI T1_;
	a = (tySequence_q5SKz0XShJtOaiDC4VrjTA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2, op);
	nimGCvisit((void*)a->data[T1_].Field3, op);
	}
}
static N_NIMCALL(void, Marker_tyRef_dVZkeDWzk9aGQiF4blk8l8A)(void* p, NI op) {
	tyTuple_I5ADwVYNrBGClFh5IRSxFw* a;
	a = (tyTuple_I5ADwVYNrBGClFh5IRSxFw*)p;
	nimGCvisit((void*)(*a).Field0, op);
	nimGCvisit((void*)(*a).Field1, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_I5ADwVYNrBGClFh5IRSxFw*, newLexer_5yIGXlzqNO0bwZLHvU6W9bA)(NimStringDesc* source) {
	tyTuple_I5ADwVYNrBGClFh5IRSxFw* result;
	NimStringDesc* T1_;
	result = (tyTuple_I5ADwVYNrBGClFh5IRSxFw*)0;
	result = (tyTuple_I5ADwVYNrBGClFh5IRSxFw*) newObj((&NTI_dVZkeDWzk9aGQiF4blk8l8A_), sizeof(tyTuple_I5ADwVYNrBGClFh5IRSxFw));
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).Field0; (*result).Field0 = copyStringRC1(source);
	if (T1_) nimGCunrefNoCycle(T1_);
	if ((*result).Field1) { nimGCunrefNoCycle((*result).Field1); (*result).Field1 = NIM_NIL; }
	(*result).Field1 = (tySequence_q5SKz0XShJtOaiDC4VrjTA*) newSeqRC1((&NTI_q5SKz0XShJtOaiDC4VrjTA_), 0);
	(*result).Field2 = ((NI) 0);
	(*result).Field3 = ((NI) 0);
	(*result).Field4 = ((NI) 1);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAtEnd_LmZvVccof2CmOEf78oKFYg)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (((*lexer).Field0 ? (*lexer).Field0->Sup.len : 0) <= (*lexer).Field3);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, advance_W5Oaj6fT4TwcY9cB9bNAisbw)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer) {
	NIM_CHAR result;
{	result = (NIM_CHAR)0;
	(*lexer).Field3 += ((NI) 1);
	result = (*lexer).Field0->data[(NI)((*lexer).Field3 - ((NI) 1))];
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, peek_h4VKNPKna0k8bNYhU5nqRQ)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer, NI offset) {
	NIM_CHAR result;
{	result = (NIM_CHAR)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isAtEnd_LmZvVccof2CmOEf78oKFYg(lexer);
		if (T3_) goto LA4_;
		T3_ = (((*lexer).Field0 ? (*lexer).Field0->Sup.len : 0) <= (NI)((*lexer).Field3 + offset));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = 0;
		goto BeforeRet_;
	}
	LA5_: ;
	result = (*lexer).Field0->data[(NI)((*lexer).Field3 + offset)];
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bglexer)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	result = (NimStringDesc*)0;
	a = x.a;
	L = (NI)((NI)(x.b - a) + ((NI) 1));
	result = mnewString(((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < L)) goto LA3;
				i = i_2;
				result->data[i] = s->data[(NI)(i + a)];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qlexer)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, addToken_1Vv9bcwSfPpY19cX2OsHBXyA)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer, tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A kind, NimStringDesc* value) {
	tyTuple_KWcIY9c1klZQizoiQC0yHOg token;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T1_;
	NI T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	memset((void*)(&token), 0, sizeof(token));
	token.Field0 = kind;
	T1_ = dotdot__vDQySKWzgnxQdUarow6k5Qlexer((*lexer).Field2, (NI)((*lexer).Field3 - ((NI) 1)));
	token.Field2 = X5BX5D__xiaaX9b4cczHG39bivOynT9bglexer((*lexer).Field0, T1_);
	token.Field3 = copyString(value);
	token.Field1 = (*lexer).Field4;
	(*lexer).Field1 = (tySequence_q5SKz0XShJtOaiDC4VrjTA*) incrSeqV2(&((*lexer).Field1)->Sup, sizeof(tyTuple_KWcIY9c1klZQizoiQC0yHOg));
	T2_ = (*lexer).Field1->Sup.len++;
	(*lexer).Field1->data[T2_].Field0 = token.Field0;
	(*lexer).Field1->data[T2_].Field1 = token.Field1;
	T3_ = (NimStringDesc*)0;
	T3_ = (*lexer).Field1->data[T2_].Field2; (*lexer).Field1->data[T2_].Field2 = copyStringRC1(token.Field2);
	if (T3_) nimGCunrefNoCycle(T3_);
	T4_ = (NimStringDesc*)0;
	T4_ = (*lexer).Field1->data[T2_].Field3; (*lexer).Field1->data[T2_].Field3 = copyStringRC1(token.Field3);
	if (T4_) nimGCunrefNoCycle(T4_);
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nextIs_1X4gy8WADUqPNHC9c6SGplA)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer, NIM_CHAR expected) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isAtEnd_LmZvVccof2CmOEf78oKFYg(lexer);
		if (T3_) goto LA4_;
		T3_ = !(((NU8)((*lexer).Field0->data[(*lexer).Field3]) == (NU8)(expected)));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA5_: ;
	(*lexer).Field3 += ((NI) 1);
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, text_hGh27pfCxctQGssRzChCug_2)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer) {
	NIM_CHAR T21_;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T22_;
	NimStringDesc* T23_;
	{
		while (1) {
			NIM_BOOL T3_;
			NIM_CHAR T4_;
			NIM_BOOL T6_;
			NIM_CHAR T12_;
			T3_ = (NIM_BOOL)0;
			T4_ = (NIM_CHAR)0;
			T4_ = peek_h4VKNPKna0k8bNYhU5nqRQ(lexer, ((NI) 0));
			T3_ = !(((NU8)(T4_) == (NU8)(34)));
			if (!(T3_)) goto LA5_;
			T6_ = (NIM_BOOL)0;
			T6_ = isAtEnd_LmZvVccof2CmOEf78oKFYg(lexer);
			T3_ = !(T6_);
			LA5_: ;
			if (!T3_) goto LA2;
			{
				NIM_CHAR T9_;
				T9_ = (NIM_CHAR)0;
				T9_ = peek_h4VKNPKna0k8bNYhU5nqRQ(lexer, ((NI) 0));
				if (!((NU8)(T9_) == (NU8)(10))) goto LA10_;
				(*lexer).Field4 += ((NI) 1);
			}
			LA10_: ;
			T12_ = (NIM_CHAR)0;
			T12_ = advance_W5Oaj6fT4TwcY9cB9bNAisbw(lexer);
			T12_;
		} LA2: ;
	}
	{
		NIM_BOOL T15_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T18_;
		NimStringDesc* T19_;
		NimStringDesc* T20_;
		T15_ = (NIM_BOOL)0;
		T15_ = isAtEnd_LmZvVccof2CmOEf78oKFYg(lexer);
		if (!T15_) goto LA16_;
		memset((void*)T18_, 0, sizeof(T18_));
		T19_ = (NimStringDesc*)0;
		T20_ = (NimStringDesc*)0;
		T20_ = nimIntToStr((*lexer).Field4);
		T19_ = rawNewString(T20_->Sup.len + 37);
appendString(T19_, ((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_3));
appendString(T19_, T20_);
		T18_[0] = T19_;
		echoBinSafe(T18_, 1);
		exit(((NI) 0));
	}
	LA16_: ;
	T21_ = (NIM_CHAR)0;
	T21_ = advance_W5Oaj6fT4TwcY9cB9bNAisbw(lexer);
	T21_;
	T22_ = dotdot__vDQySKWzgnxQdUarow6k5Qlexer((NI)((*lexer).Field2 + ((NI) 1)), (NI)((*lexer).Field3 - ((NI) 2)));
	T23_ = (NimStringDesc*)0;
	T23_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bglexer((*lexer).Field0, T22_);
	addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 26), T23_);
}

N_LIB_PRIVATE N_NIMCALL(void, number_vsWTO0plbrzs9azuzrp3kTQ)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T20_;
	NimStringDesc* T21_;
	{
		while (1) {
			NIM_CHAR T3_;
			NIM_BOOL T4_;
			NIM_CHAR T5_;
			T3_ = (NIM_CHAR)0;
			T3_ = peek_h4VKNPKna0k8bNYhU5nqRQ(lexer, ((NI) 0));
			T4_ = (NIM_BOOL)0;
			T4_ = nsuIsDigitChar(T3_);
			if (!T4_) goto LA2;
			T5_ = (NIM_CHAR)0;
			T5_ = advance_W5Oaj6fT4TwcY9cB9bNAisbw(lexer);
			T5_;
		} LA2: ;
	}
	{
		NIM_BOOL T8_;
		NIM_CHAR T9_;
		NIM_CHAR T11_;
		NIM_CHAR T14_;
		T8_ = (NIM_BOOL)0;
		T9_ = (NIM_CHAR)0;
		T9_ = peek_h4VKNPKna0k8bNYhU5nqRQ(lexer, ((NI) 0));
		T8_ = ((NU8)(T9_) == (NU8)(46));
		if (!(T8_)) goto LA10_;
		T11_ = (NIM_CHAR)0;
		T11_ = peek_h4VKNPKna0k8bNYhU5nqRQ(lexer, ((NI) 1));
		T8_ = nsuIsDigitChar(T11_);
		LA10_: ;
		if (!T8_) goto LA12_;
		T14_ = (NIM_CHAR)0;
		T14_ = advance_W5Oaj6fT4TwcY9cB9bNAisbw(lexer);
		T14_;
		{
			while (1) {
				NIM_CHAR T17_;
				NIM_BOOL T18_;
				NIM_CHAR T19_;
				T17_ = (NIM_CHAR)0;
				T17_ = peek_h4VKNPKna0k8bNYhU5nqRQ(lexer, ((NI) 0));
				T18_ = (NIM_BOOL)0;
				T18_ = nsuIsDigitChar(T17_);
				if (!T18_) goto LA16;
				T19_ = (NIM_CHAR)0;
				T19_ = advance_W5Oaj6fT4TwcY9cB9bNAisbw(lexer);
				T19_;
			} LA16: ;
		}
	}
	LA12_: ;
	T20_ = dotdot__vDQySKWzgnxQdUarow6k5Qlexer((*lexer).Field2, (NI)((*lexer).Field3 - ((NI) 1)));
	T21_ = (NimStringDesc*)0;
	T21_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bglexer((*lexer).Field0, T20_);
	addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 27), T21_);
}

N_LIB_PRIVATE N_NIMCALL(void, identifier_vsWTO0plbrzs9azuzrp3kTQ_2)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer) {
	NimStringDesc* text;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T6_;
	{
		while (1) {
			NIM_CHAR T3_;
			NIM_BOOL T4_;
			NIM_CHAR T5_;
			T3_ = (NIM_CHAR)0;
			T3_ = peek_h4VKNPKna0k8bNYhU5nqRQ(lexer, ((NI) 0));
			T4_ = (NIM_BOOL)0;
			T4_ = nsuIsAlphaNumericChar(T3_);
			if (!T4_) goto LA2;
			T5_ = (NIM_CHAR)0;
			T5_ = advance_W5Oaj6fT4TwcY9cB9bNAisbw(lexer);
			T5_;
		} LA2: ;
	}
	T6_ = dotdot__vDQySKWzgnxQdUarow6k5Qlexer((*lexer).Field2, (NI)((*lexer).Field3 - ((NI) 1)));
	text = X5BX5D__xiaaX9b4cczHG39bivOynT9bglexer((*lexer).Field0, T6_);
	{
		NIM_BOOL T9_;
		tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A T12_;
		T9_ = (NIM_BOOL)0;
		T9_ = hasKey_4ygQFmCO3DZsQWcbRPxovg(TM_LGhhYqHVISrBY59b6oZtR9bA_4, text);
		if (!T9_) goto LA10_;
		T12_ = (tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A)0;
		T12_ = X5BX5D__AMJfbib2i6SfJzvstSdk9ag(TM_LGhhYqHVISrBY59b6oZtR9bA_4, text);
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, T12_, NIM_NIL);
	}
	goto LA7_;
	LA10_: ;
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 25), NIM_NIL);
	}
	LA7_: ;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_LIB_PRIVATE N_NIMCALL(void, scanToken_hGh27pfCxctQGssRzChCug)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer) {
	NIM_CHAR c;
	c = advance_W5Oaj6fT4TwcY9cB9bNAisbw(lexer);
	switch (((NU8)(c))) {
	case 32:
	case 13:
	case 9:
	{
	}
	break;
	case 35:
	{
		{
			while (1) {
				NIM_BOOL T5_;
				NIM_CHAR T6_;
				NIM_BOOL T8_;
				NIM_CHAR T9_;
				T5_ = (NIM_BOOL)0;
				T6_ = (NIM_CHAR)0;
				T6_ = peek_h4VKNPKna0k8bNYhU5nqRQ(lexer, ((NI) 0));
				T5_ = !(((NU8)(T6_) == (NU8)(10)));
				if (!(T5_)) goto LA7_;
				T8_ = (NIM_BOOL)0;
				T8_ = isAtEnd_LmZvVccof2CmOEf78oKFYg(lexer);
				T5_ = !(T8_);
				LA7_: ;
				if (!T5_) goto LA4;
				T9_ = (NIM_CHAR)0;
				T9_ = advance_W5Oaj6fT4TwcY9cB9bNAisbw(lexer);
				T9_;
			} LA4: ;
		}
	}
	break;
	case 43:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 0), NIM_NIL);
	}
	break;
	case 45:
	{
		{
			NIM_BOOL T14_;
			T14_ = (NIM_BOOL)0;
			T14_ = nextIs_1X4gy8WADUqPNHC9c6SGplA(lexer, 62);
			if (!T14_) goto LA15_;
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 23), NIM_NIL);
		}
		goto LA12_;
		LA15_: ;
		{
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 1), NIM_NIL);
		}
		LA12_: ;
	}
	break;
	case 42:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 2), NIM_NIL);
	}
	break;
	case 47:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 3), NIM_NIL);
	}
	break;
	case 37:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 4), NIM_NIL);
	}
	break;
	case 40:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 5), NIM_NIL);
	}
	break;
	case 41:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 6), NIM_NIL);
	}
	break;
	case 91:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 7), NIM_NIL);
	}
	break;
	case 93:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 8), NIM_NIL);
	}
	break;
	case 123:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 9), NIM_NIL);
	}
	break;
	case 125:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 10), NIM_NIL);
	}
	break;
	case 44:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 11), NIM_NIL);
	}
	break;
	case 46:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 12), NIM_NIL);
	}
	break;
	case 58:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 13), NIM_NIL);
	}
	break;
	case 59:
	{
		addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 14), NIM_NIL);
	}
	break;
	case 61:
	{
		{
			NIM_BOOL T34_;
			T34_ = (NIM_BOOL)0;
			T34_ = nextIs_1X4gy8WADUqPNHC9c6SGplA(lexer, 61);
			if (!T34_) goto LA35_;
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 16), NIM_NIL);
		}
		goto LA32_;
		LA35_: ;
		{
			NIM_BOOL T38_;
			T38_ = (NIM_BOOL)0;
			T38_ = nextIs_1X4gy8WADUqPNHC9c6SGplA(lexer, 62);
			if (!T38_) goto LA39_;
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 24), NIM_NIL);
		}
		goto LA32_;
		LA39_: ;
		{
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 15), NIM_NIL);
		}
		LA32_: ;
	}
	break;
	case 33:
	{
		{
			NIM_BOOL T45_;
			T45_ = (NIM_BOOL)0;
			T45_ = nextIs_1X4gy8WADUqPNHC9c6SGplA(lexer, 61);
			if (!T45_) goto LA46_;
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 18), NIM_NIL);
		}
		goto LA43_;
		LA46_: ;
		{
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 17), NIM_NIL);
		}
		LA43_: ;
	}
	break;
	case 62:
	{
		{
			NIM_BOOL T52_;
			T52_ = (NIM_BOOL)0;
			T52_ = nextIs_1X4gy8WADUqPNHC9c6SGplA(lexer, 61);
			if (!T52_) goto LA53_;
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 20), NIM_NIL);
		}
		goto LA50_;
		LA53_: ;
		{
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 19), NIM_NIL);
		}
		LA50_: ;
	}
	break;
	case 60:
	{
		{
			NIM_BOOL T59_;
			T59_ = (NIM_BOOL)0;
			T59_ = nextIs_1X4gy8WADUqPNHC9c6SGplA(lexer, 61);
			if (!T59_) goto LA60_;
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 22), NIM_NIL);
		}
		goto LA57_;
		LA60_: ;
		{
			addToken_1Vv9bcwSfPpY19cX2OsHBXyA(lexer, ((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 21), NIM_NIL);
		}
		LA57_: ;
	}
	break;
	case 10:
	{
		(*lexer).Field4 += ((NI) 1);
	}
	break;
	case 34:
	{
		text_hGh27pfCxctQGssRzChCug_2(lexer);
	}
	break;
	default:
	{
		{
			NIM_BOOL T68_;
			T68_ = (NIM_BOOL)0;
			T68_ = nsuIsDigitChar(c);
			if (!T68_) goto LA69_;
			number_vsWTO0plbrzs9azuzrp3kTQ(lexer);
		}
		goto LA66_;
		LA69_: ;
		{
			NIM_BOOL T72_;
			T72_ = (NIM_BOOL)0;
			T72_ = nsuIsAlphaAsciiChar(c);
			if (!T72_) goto LA73_;
			identifier_vsWTO0plbrzs9azuzrp3kTQ_2(lexer);
		}
		goto LA66_;
		LA73_: ;
		{
			tyArray_nHXaesL0DJZHyVS07ARPRA T76_;
			NimStringDesc* T77_;
			NimStringDesc* T78_;
			memset((void*)T76_, 0, sizeof(T76_));
			T77_ = (NimStringDesc*)0;
			T78_ = (NimStringDesc*)0;
			T78_ = nimIntToStr((*lexer).Field4);
			T77_ = rawNewString(T78_->Sup.len + 36);
appendString(T77_, ((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_17));
appendChar(T77_, c);
appendString(T77_, ((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_18));
appendString(T77_, T78_);
			T76_[0] = T77_;
			echoBinSafe(T76_, 1);
		}
		LA66_: ;
	}
	break;
	}
}

N_LIB_PRIVATE N_NIMCALL(tySequence_q5SKz0XShJtOaiDC4VrjTA*, scan_gkPen9czuh8xnlh1KZaiknQ)(tyTuple_I5ADwVYNrBGClFh5IRSxFw* lexer) {
	tySequence_q5SKz0XShJtOaiDC4VrjTA* result;
	tyTuple_KWcIY9c1klZQizoiQC0yHOg T4_;
	NI T5_;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
{	result = (tySequence_q5SKz0XShJtOaiDC4VrjTA*)0;
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = isAtEnd_LmZvVccof2CmOEf78oKFYg(lexer);
			if (!!(T3_)) goto LA2;
			(*lexer).Field2 = (*lexer).Field3;
			scanToken_hGh27pfCxctQGssRzChCug(lexer);
		} LA2: ;
	}
	memset((void*)(&T4_), 0, sizeof(T4_));
	newToken_CxEPRFYDeVoM1n45VSW9bqQ(((tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A) 39), (*lexer).Field4, NIM_NIL, NIM_NIL, (&T4_));
	(*lexer).Field1 = (tySequence_q5SKz0XShJtOaiDC4VrjTA*) incrSeqV2(&((*lexer).Field1)->Sup, sizeof(tyTuple_KWcIY9c1klZQizoiQC0yHOg));
	T5_ = (*lexer).Field1->Sup.len++;
	(*lexer).Field1->data[T5_].Field0 = T4_.Field0;
	(*lexer).Field1->data[T5_].Field1 = T4_.Field1;
	T6_ = (NimStringDesc*)0;
	T6_ = (*lexer).Field1->data[T5_].Field2; (*lexer).Field1->data[T5_].Field2 = copyStringRC1(T4_.Field2);
	if (T6_) nimGCunrefNoCycle(T6_);
	T7_ = (NimStringDesc*)0;
	T7_ = (*lexer).Field1->data[T5_].Field3; (*lexer).Field1->data[T5_].Field3 = copyStringRC1(T4_.Field3);
	if (T7_) nimGCunrefNoCycle(T7_);
	genericSeqAssign((&result), (*lexer).Field1, (&NTI_q5SKz0XShJtOaiDC4VrjTA_));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_lexerInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_lexerDatInit000)(void) {
static TNimNode* TM_LGhhYqHVISrBY59b6oZtR9bA_2[5];
static TNimNode TM_LGhhYqHVISrBY59b6oZtR9bA_0[6];
NTI_I5ADwVYNrBGClFh5IRSxFw_.size = sizeof(tyTuple_I5ADwVYNrBGClFh5IRSxFw);
NTI_I5ADwVYNrBGClFh5IRSxFw_.kind = 18;
NTI_I5ADwVYNrBGClFh5IRSxFw_.base = 0;
NTI_I5ADwVYNrBGClFh5IRSxFw_.flags = 2;
TM_LGhhYqHVISrBY59b6oZtR9bA_2[0] = &TM_LGhhYqHVISrBY59b6oZtR9bA_0[1];
TM_LGhhYqHVISrBY59b6oZtR9bA_0[1].kind = 1;
TM_LGhhYqHVISrBY59b6oZtR9bA_0[1].offset = offsetof(tyTuple_I5ADwVYNrBGClFh5IRSxFw, Field0);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[1].name = "Field0";
TM_LGhhYqHVISrBY59b6oZtR9bA_2[1] = &TM_LGhhYqHVISrBY59b6oZtR9bA_0[2];
NTI_q5SKz0XShJtOaiDC4VrjTA_.size = sizeof(tySequence_q5SKz0XShJtOaiDC4VrjTA*);
NTI_q5SKz0XShJtOaiDC4VrjTA_.kind = 24;
NTI_q5SKz0XShJtOaiDC4VrjTA_.base = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
NTI_q5SKz0XShJtOaiDC4VrjTA_.flags = 2;
NTI_q5SKz0XShJtOaiDC4VrjTA_.marker = Marker_tySequence_q5SKz0XShJtOaiDC4VrjTA;
TM_LGhhYqHVISrBY59b6oZtR9bA_0[2].kind = 1;
TM_LGhhYqHVISrBY59b6oZtR9bA_0[2].offset = offsetof(tyTuple_I5ADwVYNrBGClFh5IRSxFw, Field1);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[2].typ = (&NTI_q5SKz0XShJtOaiDC4VrjTA_);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[2].name = "Field1";
TM_LGhhYqHVISrBY59b6oZtR9bA_2[2] = &TM_LGhhYqHVISrBY59b6oZtR9bA_0[3];
TM_LGhhYqHVISrBY59b6oZtR9bA_0[3].kind = 1;
TM_LGhhYqHVISrBY59b6oZtR9bA_0[3].offset = offsetof(tyTuple_I5ADwVYNrBGClFh5IRSxFw, Field2);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[3].name = "Field2";
TM_LGhhYqHVISrBY59b6oZtR9bA_2[3] = &TM_LGhhYqHVISrBY59b6oZtR9bA_0[4];
TM_LGhhYqHVISrBY59b6oZtR9bA_0[4].kind = 1;
TM_LGhhYqHVISrBY59b6oZtR9bA_0[4].offset = offsetof(tyTuple_I5ADwVYNrBGClFh5IRSxFw, Field3);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[4].name = "Field3";
TM_LGhhYqHVISrBY59b6oZtR9bA_2[4] = &TM_LGhhYqHVISrBY59b6oZtR9bA_0[5];
TM_LGhhYqHVISrBY59b6oZtR9bA_0[5].kind = 1;
TM_LGhhYqHVISrBY59b6oZtR9bA_0[5].offset = offsetof(tyTuple_I5ADwVYNrBGClFh5IRSxFw, Field4);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_LGhhYqHVISrBY59b6oZtR9bA_0[5].name = "Field4";
TM_LGhhYqHVISrBY59b6oZtR9bA_0[0].len = 5; TM_LGhhYqHVISrBY59b6oZtR9bA_0[0].kind = 2; TM_LGhhYqHVISrBY59b6oZtR9bA_0[0].sons = &TM_LGhhYqHVISrBY59b6oZtR9bA_2[0];
NTI_I5ADwVYNrBGClFh5IRSxFw_.node = &TM_LGhhYqHVISrBY59b6oZtR9bA_0[0];
NTI_dVZkeDWzk9aGQiF4blk8l8A_.size = sizeof(tyTuple_I5ADwVYNrBGClFh5IRSxFw*);
NTI_dVZkeDWzk9aGQiF4blk8l8A_.kind = 22;
NTI_dVZkeDWzk9aGQiF4blk8l8A_.base = (&NTI_I5ADwVYNrBGClFh5IRSxFw_);
NTI_dVZkeDWzk9aGQiF4blk8l8A_.flags = 2;
NTI_dVZkeDWzk9aGQiF4blk8l8A_.marker = Marker_tyRef_dVZkeDWzk9aGQiF4blk8l8A;
}

