/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/erik/.choosenim/toolchains/nim-0.18.0/lib -o /home/erik/Code/TFG/void/NimVoid/src/nimcache/rules.o /home/erik/Code/TFG/void/NimVoid/src/nimcache/rules.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ;
typedef struct tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ;
typedef struct tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg;
typedef struct tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ;
typedef struct tySequence_9bpx44aFIusE9bW4FLAgSGhA tySequence_9bpx44aFIusE9bW4FLAgSGhA;
typedef struct tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g;
typedef struct tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ;
typedef struct tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ;
typedef struct tyTuple_KWcIY9c1klZQizoiQC0yHOg tyTuple_KWcIY9c1klZQizoiQC0yHOg;
typedef struct tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q;
typedef struct tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw;
typedef struct tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ;
typedef struct tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ;
typedef struct tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA;
typedef struct tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ;
typedef struct tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw;
typedef struct tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A;
typedef struct tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A;
typedef struct tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg;
typedef struct tySequence_x9cl451W8JtBGbwWydXa7PQ tySequence_x9cl451W8JtBGbwWydXa7PQ;
typedef struct tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA;
typedef struct tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA;
typedef struct tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw;
typedef struct tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw;
typedef struct tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg;
typedef struct tySequence_q5SKz0XShJtOaiDC4VrjTA tySequence_q5SKz0XShJtOaiDC4VrjTA;
typedef struct tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ;
typedef struct tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ {
  RootObj Sup;
};
struct tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
NF value;
};
struct tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
NimStringDesc* value;
};
struct tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
NIM_BOOL value;
};
struct tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tySequence_9bpx44aFIusE9bW4FLAgSGhA* values;
};
struct tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
typedef NU8 tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A;
struct tyTuple_KWcIY9c1klZQizoiQC0yHOg {
tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A Field0;
NI Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
};
struct tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg operator_0;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* right;
};
struct tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg operator_0;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* left;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* right;
};
struct tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg name;
};
struct tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg name;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* value;
};
struct tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg operator_0;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* left;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* right;
};
struct tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* callee;
tyTuple_KWcIY9c1klZQizoiQC0yHOg paren;
tySequence_9bpx44aFIusE9bW4FLAgSGhA* arguments;
};
struct tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg item;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* index;
};
struct tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw {
  RootObj Sup;
};
struct tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
struct tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
struct tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tySequence_x9cl451W8JtBGbwWydXa7PQ* body;
};
struct tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* condition;
tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* thenBranch;
tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* elseBranch;
};
struct tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* condition;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
struct tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* condition;
tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* body;
};
struct tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw {
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg keyword;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* value;
};
struct tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tySequence_q5SKz0XShJtOaiDC4VrjTA* arguments;
tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* body;
};
struct tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tySequence_q5SKz0XShJtOaiDC4VrjTA* arguments;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* expression;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
};
struct tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA {
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ Sup;
tyTuple_KWcIY9c1klZQizoiQC0yHOg name;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* index;
tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* value;
};
struct tySequence_9bpx44aFIusE9bW4FLAgSGhA {
  TGenericSeq Sup;
  tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* data[SEQ_DECL_SIZE];
};
struct tySequence_x9cl451W8JtBGbwWydXa7PQ {
  TGenericSeq Sup;
  tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* data[SEQ_DECL_SIZE];
};
struct tySequence_q5SKz0XShJtOaiDC4VrjTA {
  TGenericSeq Sup;
  tyTuple_KWcIY9c1klZQizoiQC0yHOg data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__ggE5iCvDcHJc5oPETQvwmg)(tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* t);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__e9a2OqyskFnxFCvhQSrXTxg)(tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q* t);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Tv9bN4nfZDMP7Hd3sW4qlmA)(tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__GcBOs9bLcuMRn5VAwtMtesQ)(tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg* t);
N_NIMCALL(NimStringDesc*, nimBoolToStr)(NIM_BOOL x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__9aRCh7ExWhZE19c29bOwA20HQ)(tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__ultDzGajUm1FtAZeeNOcFQ)(tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* t);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__UCOm65V3c0hYVgldEcdFug)(tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__WR2AffrOCpnUgkwtemTYjg)(tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__b5f9bz1Le9cm9c9bT9bNScaTIfA)(tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__fTtCeZJn6hbR5LaLN9cFuWw)(tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__1OGt2lPFzjufXxAQEUwZ1g)(tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__QR4qIPO9cioDpRSS3OlrSMA)(tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Kq9cKsPHB8D3KsidpWblfLQ)(tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__PhN2Na5DoP89b4obWPl2Jzg)(tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__gqz7v5rH04UgEK5O89cLzgA)(tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__2zoJJSUvlrkiKRWedqwDBA)(tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__k9cbY8xSMvVxgbU06y6HnLQ)(tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__NE6k4Fh1BENmGa89aJl9cFIA)(tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Hzukc9c80xTm0jwPz6dYxIw)(tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__xDTaOVUWqcxRXMoDU15O0w)(tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__8mPOJbdpXIOG6j9c3Iz9bpyA)(tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Gvr0GxUlN3UZWoC9bm4R4nw)(tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__qQG6Qx18X9bg4nGGG9a45Zfw)(tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__gL79allBM3aikke9cGk5N9bLw)(tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__A8QWsPBSVHERRHABfIuV0A)(tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg* t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__zl3tqrK2xGjBoPba50Ihtg)(tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ* t);
static N_NIMCALL(void, Marker_tyRef_NenfDgTNVh6SvXGs80KU2A)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_9bpx44aFIusE9bW4FLAgSGhA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_vrDqE1cN4bW1IytyuKpmSQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_zFjXHWb6uMsuJNIG9awiuug)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_9bTNwoqjfakfBtY05rvxxWw)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_uZRrfTaV9b4SF3HWx9bwsr2A)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_jdZGByKgvXlIb9b3stA2TIg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_DL9aQlHvs6h2nnit0jUeC7Q)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_CBobTOx0GswbKO18xqssIA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_gMusbyN15UJBRxE8mQITkQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_tx5HDH7XI1F1wmNqlcaw6g)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_9aHvZsHm9aUiDR6MMbfKGX1g)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_Ofqzvrn9ciQqdn2DHPB8MaQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_d2OzjtAZ2xAFsxCjsp3KeA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_K1dj7759cs8U08D9biGluCQQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_lQxA8LgwOz1RB2r9crx9a6fg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_9byfr5Q9c3j9cZwj6B9cKxGVTw)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_zgf9byZOH735gbLd9b6y3Ddw)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_A29aeP1yJWXm58U9bNRz87yQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_9b2yF8eg2p3nFw60XJXuC9aQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_amAOnss7JKRUudZgJKMrZg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_REwFzo5GNPW2hz33o9b4sZA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_9a9bq2t9b77qCcff6YL5yLsvg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_04BvVjBlmkK2D3Dvo59cE1Q)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_0nas9cdBOCeb1qHpvxOocGg)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_1iwO2mjhvAgjUCXIYlFkzw)(void* p, NI op);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_iy1XUAZvASFmRHhy6Sl3QQ_;
TNimType NTI_3MoUzdd6JpcZ1tSX82rd2Q_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_H6QC3PBmhdJSmT9cDaRWAAQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_TeU0tViLpeWJ89cheW1wFUg_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_5n4g9cmeh9b6y5ArRowKRuIQ_;
TNimType NTI_NenfDgTNVh6SvXGs80KU2A_;
TNimType NTI_9bpx44aFIusE9bW4FLAgSGhA_;
TNimType NTI_xzysDaRkx9b8cniE9aTMy37g_;
TNimType NTI_WJW05mFVFR8R5Re1RdwjkQ_;
TNimType NTI_qHyvSBqcF0iFkrOEJDqLyQ_;
extern TNimType NTI_KWcIY9c1klZQizoiQC0yHOg_;
TNimType NTI_dqD3ROdpQFuI6y9a2nYB32Q_;
TNimType NTI_kRnNrqDqgCDbcfyCYJWfkw_;
TNimType NTI_rw8DvbXrFC9cPt2Vhqv9clxQ_;
TNimType NTI_g3GRisyoY8TUGSo7QDexIw_;
TNimType NTI_K9aIg0VZvCzVPoXP2BYctmw_;
TNimType NTI_vrDqE1cN4bW1IytyuKpmSQ_;
TNimType NTI_zFjXHWb6uMsuJNIG9awiuug_;
TNimType NTI_9bTNwoqjfakfBtY05rvxxWw_;
TNimType NTI_uZRrfTaV9b4SF3HWx9bwsr2A_;
TNimType NTI_jdZGByKgvXlIb9b3stA2TIg_;
TNimType NTI_DL9aQlHvs6h2nnit0jUeC7Q_;
TNimType NTI_CBobTOx0GswbKO18xqssIA_;
TNimType NTI_gMusbyN15UJBRxE8mQITkQ_;
TNimType NTI_u265gaSX0MPT06gifycCyQ_;
extern TNimType NTI_q5SKz0XShJtOaiDC4VrjTA_;
TNimType NTI_tx5HDH7XI1F1wmNqlcaw6g_;
TNimType NTI_x2GjBVvTXMSLFyceo9csgtg_;
TNimType NTI_3PhzvO9b59cuRtHL3meWMYpg_;
extern TNimType NTI_x9cl451W8JtBGbwWydXa7PQ_;
TNimType NTI_9aHvZsHm9aUiDR6MMbfKGX1g_;
TNimType NTI_Ofqzvrn9ciQqdn2DHPB8MaQ_;
TNimType NTI_d2OzjtAZ2xAFsxCjsp3KeA_;
TNimType NTI_WilglSQ9aUNqKdPtw9bgGnTA_;
TNimType NTI_K1dj7759cs8U08D9biGluCQQ_;
TNimType NTI_uxYIijxEkQ8erAyjJzJcOQ_;
TNimType NTI_lQxA8LgwOz1RB2r9crx9a6fg_;
TNimType NTI_9byfr5Q9c3j9cZwj6B9cKxGVTw_;
TNimType NTI_zgf9byZOH735gbLd9b6y3Ddw_;
TNimType NTI_GsCLniDIGL7wguLE00poBQ_;
TNimType NTI_A29aeP1yJWXm58U9bNRz87yQ_;
TNimType NTI_44ZOUzoHf9a19bYVak31LkdA_;
TNimType NTI_9b2yF8eg2p3nFw60XJXuC9aQ_;
TNimType NTI_x9aL9cMYr9cCbSrhkSWnryVvA_;
TNimType NTI_amAOnss7JKRUudZgJKMrZg_;
TNimType NTI_8cjtRrEFjHGd6Y7na7NGlA_;
TNimType NTI_REwFzo5GNPW2hz33o9b4sZA_;
TNimType NTI_gws4iaqmhdyLuikDU0Kd4A_;
TNimType NTI_9a9bq2t9b77qCcff6YL5yLsvg_;
TNimType NTI_04BvVjBlmkK2D3Dvo59cE1Q_;
TNimType NTI_5M9ar9bYql9bg3tWBfZPXpTFw_;
TNimType NTI_0nas9cdBOCeb1qHpvxOocGg_;
TNimType NTI_0fTeFc1ncIUGvG6ZDbWW3A_;
TNimType NTI_1iwO2mjhvAgjUCXIYlFkzw_;
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_2, "Expression()", 12);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_3, "Number(", 7);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_4, ")", 1);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_5, "String(", 7);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_6, "Boolean(", 8);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_7, "List(", 5);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_8, ", ", 2);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_9, "None()", 6);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_10, "Group(", 6);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_11, "Unary(", 6);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_12, "Binary(", 7);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_13, "Variable(", 9);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_14, "Assign(", 7);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_15, "Logical(", 8);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_16, "Call(", 5);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_17, ", [", 3);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_18, "])", 2);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_19, "Access(", 7);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_20, "Statement()", 11);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_21, "ExpressionStatement(", 20);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_22, "Print(", 6);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_23, "Block(", 6);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_24, "If(", 3);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_25, "SimpleIf(", 9);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_26, "While(", 6);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_27, "Return(", 7);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_28, "Function([", 10);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_29, "], ", 3);
STRING_LITERAL(TM_e1qf3uIyLveIFu9a9cRtgNyg_30, "SimpleFunction([", 16);

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__ggE5iCvDcHJc5oPETQvwmg)(tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* t) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_2));
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__e9a2OqyskFnxFCvhQSrXTxg)(tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimFloatToStr((*t).value);
	T1_ = rawNewString(T2_->Sup.len + 8);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_3));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Tv9bN4nfZDMP7Hd3sW4qlmA)(tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString((*t).value->Sup.len + 8);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_5));
appendString(T1_, (*t).value);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__GcBOs9bLcuMRn5VAwtMtesQ)(tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimBoolToStr((*t).value);
	T1_ = rawNewString(T2_->Sup.len + 9);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_6));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__9aRCh7ExWhZE19c29bOwA20HQ)(tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ* t) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_7));
	{
		tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* i;
		tySequence_9bpx44aFIusE9bW4FLAgSGhA* colontmp_;
		NI i_2;
		NI L;
		NI T2_;
		i = (tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ*)0;
		colontmp_ = (tySequence_9bpx44aFIusE9bW4FLAgSGhA*)0;
		colontmp_ = (*t).values;
		i_2 = ((NI) 0);
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				NimStringDesc* T5_;
				NimStringDesc* T6_;
				if (!(i_2 < L)) goto LA4;
				i = colontmp_->data[i_2];
				T5_ = (NimStringDesc*)0;
				T6_ = (NimStringDesc*)0;
				T6_ = dollar__ultDzGajUm1FtAZeeNOcFQ(i);
				T5_ = rawNewString(T6_->Sup.len + 2);
appendString(T5_, T6_);
appendString(T5_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
				result = resizeString(result, T5_->Sup.len + 0);
appendString(result, T5_);
				i_2 += ((NI) 1);
			} LA4: ;
		}
	}
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__UCOm65V3c0hYVgldEcdFug)(tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g* t) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_9));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__WR2AffrOCpnUgkwtemTYjg)(tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).expression);
	T1_ = rawNewString(T2_->Sup.len + 7);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_10));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__b5f9bz1Le9cm9c9bT9bNScaTIfA)(tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).right);
	T1_ = rawNewString((*t).operator_0.Field2->Sup.len + T2_->Sup.len + 9);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_11));
appendString(T1_, (*t).operator_0.Field2);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__fTtCeZJn6hbR5LaLN9cFuWw)(tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).left);
	T3_ = (NimStringDesc*)0;
	T3_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).right);
	T1_ = rawNewString(T2_->Sup.len + (*t).operator_0.Field2->Sup.len + T3_->Sup.len + 12);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_12));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, (*t).operator_0.Field2);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__1OGt2lPFzjufXxAQEUwZ1g)(tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString((*t).name.Field2->Sup.len + 10);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_13));
appendString(T1_, (*t).name.Field2);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__QR4qIPO9cioDpRSS3OlrSMA)(tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).value);
	T1_ = rawNewString((*t).name.Field2->Sup.len + T2_->Sup.len + 10);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_14));
appendString(T1_, (*t).name.Field2);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Kq9cKsPHB8D3KsidpWblfLQ)(tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).left);
	T3_ = (NimStringDesc*)0;
	T3_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).right);
	T1_ = rawNewString(T2_->Sup.len + (*t).operator_0.Field2->Sup.len + T3_->Sup.len + 13);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_15));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, (*t).operator_0.Field2);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__PhN2Na5DoP89b4obWPl2Jzg)(tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).callee);
	T1_ = rawNewString(T2_->Sup.len + 8);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_16));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_17));
	result = T1_;
	{
		tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* i;
		tySequence_9bpx44aFIusE9bW4FLAgSGhA* colontmp_;
		NI i_2;
		NI L;
		NI T4_;
		i = (tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ*)0;
		colontmp_ = (tySequence_9bpx44aFIusE9bW4FLAgSGhA*)0;
		colontmp_ = (*t).arguments;
		i_2 = ((NI) 0);
		T4_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T4_;
		{
			while (1) {
				NimStringDesc* T7_;
				NimStringDesc* T8_;
				if (!(i_2 < L)) goto LA6;
				i = colontmp_->data[i_2];
				T7_ = (NimStringDesc*)0;
				T8_ = (NimStringDesc*)0;
				T8_ = dollar__ultDzGajUm1FtAZeeNOcFQ(i);
				T7_ = rawNewString(T8_->Sup.len + 2);
appendString(T7_, T8_);
appendString(T7_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
				result = resizeString(result, T7_->Sup.len + 0);
appendString(result, T7_);
				i_2 += ((NI) 1);
			} LA6: ;
		}
	}
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_18));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__gqz7v5rH04UgEK5O89cLzgA)(tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).index);
	T1_ = rawNewString((*t).item.Field2->Sup.len + T2_->Sup.len + 10);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_19));
appendString(T1_, (*t).item.Field2);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__2zoJJSUvlrkiKRWedqwDBA)(tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* t) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_20));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__k9cbY8xSMvVxgbU06y6HnLQ)(tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).expression);
	T1_ = rawNewString(T2_->Sup.len + 21);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_21));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__NE6k4Fh1BENmGa89aJl9cFIA)(tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).expression);
	T1_ = rawNewString(T2_->Sup.len + 7);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_22));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Hzukc9c80xTm0jwPz6dYxIw)(tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* t) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_23));
	{
		tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* i;
		tySequence_x9cl451W8JtBGbwWydXa7PQ* colontmp_;
		NI i_2;
		NI L;
		NI T2_;
		i = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
		colontmp_ = (tySequence_x9cl451W8JtBGbwWydXa7PQ*)0;
		colontmp_ = (*t).body;
		i_2 = ((NI) 0);
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				NimStringDesc* T5_;
				NimStringDesc* T6_;
				if (!(i_2 < L)) goto LA4;
				i = colontmp_->data[i_2];
				T5_ = (NimStringDesc*)0;
				T6_ = (NimStringDesc*)0;
				T6_ = dollar__xDTaOVUWqcxRXMoDU15O0w(i);
				T5_ = rawNewString(T6_->Sup.len + 2);
appendString(T5_, T6_);
appendString(T5_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
				result = resizeString(result, T5_->Sup.len + 0);
appendString(result, T5_);
				i_2 += ((NI) 1);
			} LA4: ;
		}
	}
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__8mPOJbdpXIOG6j9c3Iz9bpyA)(tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T3_;
	NimStringDesc* T4_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).condition);
	T3_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
	T3_ = &(*t).thenBranch->Sup;
	T4_ = (NimStringDesc*)0;
	T4_ = dollar__xDTaOVUWqcxRXMoDU15O0w(T3_);
	T1_ = rawNewString(T2_->Sup.len + T4_->Sup.len + 5);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_24));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, T4_);
	result = T1_;
	{
		NimStringDesc* T9_;
		tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T10_;
		NimStringDesc* T11_;
		if (!!(((*t).elseBranch == NIM_NIL))) goto LA7_;
		T9_ = (NimStringDesc*)0;
		T10_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
		T10_ = &(*t).elseBranch->Sup;
		T11_ = (NimStringDesc*)0;
		T11_ = dollar__xDTaOVUWqcxRXMoDU15O0w(T10_);
		T9_ = rawNewString(T11_->Sup.len + 2);
appendString(T9_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T9_, T11_);
		result = resizeString(result, T9_->Sup.len + 0);
appendString(result, T9_);
	}
	LA7_: ;
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Gvr0GxUlN3UZWoC9bm4R4nw)(tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).condition);
	T3_ = (NimStringDesc*)0;
	T3_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).expression);
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + 12);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_25));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__qQG6Qx18X9bg4nGGG9a45Zfw)(tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T3_;
	NimStringDesc* T4_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).condition);
	T3_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
	T3_ = &(*t).body->Sup;
	T4_ = (NimStringDesc*)0;
	T4_ = dollar__xDTaOVUWqcxRXMoDU15O0w(T3_);
	T1_ = rawNewString(T2_->Sup.len + T4_->Sup.len + 9);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_26));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
appendString(T1_, T4_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__gL79allBM3aikke9cGk5N9bLw)(tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).value);
	T1_ = rawNewString(T2_->Sup.len + 8);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_27));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = T1_;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__A8QWsPBSVHERRHABfIuV0A)(tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg* t) {
	NimStringDesc* result;
	NimStringDesc* T6_;
	tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* T7_;
	NimStringDesc* T8_;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_28));
	{
		tyTuple_KWcIY9c1klZQizoiQC0yHOg i;
		tySequence_q5SKz0XShJtOaiDC4VrjTA* colontmp_;
		NI i_2;
		NI L;
		NI T2_;
		memset((void*)(&i), 0, sizeof(i));
		colontmp_ = (tySequence_q5SKz0XShJtOaiDC4VrjTA*)0;
		colontmp_ = (*t).arguments;
		i_2 = ((NI) 0);
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				NimStringDesc* T5_;
				if (!(i_2 < L)) goto LA4;
				i.Field0 = colontmp_->data[i_2].Field0;
				i.Field1 = colontmp_->data[i_2].Field1;
				i.Field2 = colontmp_->data[i_2].Field2;
				i.Field3 = colontmp_->data[i_2].Field3;
				T5_ = (NimStringDesc*)0;
				T5_ = rawNewString(i.Field2->Sup.len + 2);
appendString(T5_, i.Field2);
appendString(T5_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
				result = resizeString(result, T5_->Sup.len + 0);
appendString(result, T5_);
				i_2 += ((NI) 1);
			} LA4: ;
		}
	}
	T6_ = (NimStringDesc*)0;
	T7_ = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)0;
	T7_ = &(*t).body->Sup;
	T8_ = (NimStringDesc*)0;
	T8_ = dollar__xDTaOVUWqcxRXMoDU15O0w(T7_);
	T6_ = rawNewString(T8_->Sup.len + 4);
appendString(T6_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_29));
appendString(T6_, T8_);
appendString(T6_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = resizeString(result, T6_->Sup.len + 0);
appendString(result, T6_);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__zl3tqrK2xGjBoPba50Ihtg)(tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ* t) {
	NimStringDesc* result;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_30));
	{
		tyTuple_KWcIY9c1klZQizoiQC0yHOg i;
		tySequence_q5SKz0XShJtOaiDC4VrjTA* colontmp_;
		NI i_2;
		NI L;
		NI T2_;
		memset((void*)(&i), 0, sizeof(i));
		colontmp_ = (tySequence_q5SKz0XShJtOaiDC4VrjTA*)0;
		colontmp_ = (*t).arguments;
		i_2 = ((NI) 0);
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				NimStringDesc* T5_;
				if (!(i_2 < L)) goto LA4;
				i.Field0 = colontmp_->data[i_2].Field0;
				i.Field1 = colontmp_->data[i_2].Field1;
				i.Field2 = colontmp_->data[i_2].Field2;
				i.Field3 = colontmp_->data[i_2].Field3;
				T5_ = (NimStringDesc*)0;
				T5_ = rawNewString(i.Field2->Sup.len + 2);
appendString(T5_, i.Field2);
appendString(T5_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_8));
				result = resizeString(result, T5_->Sup.len + 0);
appendString(result, T5_);
				i_2 += ((NI) 1);
			} LA4: ;
		}
	}
	T6_ = (NimStringDesc*)0;
	T7_ = (NimStringDesc*)0;
	T7_ = dollar__ultDzGajUm1FtAZeeNOcFQ((*t).expression);
	T6_ = rawNewString(T7_->Sup.len + 4);
appendString(T6_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_29));
appendString(T6_, T7_);
appendString(T6_, ((NimStringDesc*) &TM_e1qf3uIyLveIFu9a9cRtgNyg_4));
	result = resizeString(result, T6_->Sup.len + 0);
appendString(result, T6_);
	return result;
}
static N_NIMCALL(void, Marker_tyRef_NenfDgTNVh6SvXGs80KU2A)(void* p, NI op) {
	tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ* a;
	a = (tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ*)p;
}
static N_NIMCALL(void, Marker_tySequence_9bpx44aFIusE9bW4FLAgSGhA)(void* p, NI op) {
	tySequence_9bpx44aFIusE9bW4FLAgSGhA* a;
	NI T1_;
	a = (tySequence_9bpx44aFIusE9bW4FLAgSGhA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef_vrDqE1cN4bW1IytyuKpmSQ)(void* p, NI op) {
	tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw* a;
	a = (tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*)p;
}
static N_NIMCALL(void, Marker_tyRef_zFjXHWb6uMsuJNIG9awiuug)(void* p, NI op) {
	tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ* a;
	a = (tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ*)p;
	nimGCvisit((void*)(*a).operator_0.Field2, op);
	nimGCvisit((void*)(*a).operator_0.Field3, op);
	nimGCvisit((void*)(*a).right, op);
}
static N_NIMCALL(void, Marker_tyRef_9bTNwoqjfakfBtY05rvxxWw)(void* p, NI op) {
	tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg* a;
	a = (tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg*)p;
}
static N_NIMCALL(void, Marker_tyRef_uZRrfTaV9b4SF3HWx9bwsr2A)(void* p, NI op) {
	tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g* a;
	a = (tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g*)p;
}
static N_NIMCALL(void, Marker_tyRef_jdZGByKgvXlIb9b3stA2TIg)(void* p, NI op) {
	tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q* a;
	a = (tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q*)p;
}
static N_NIMCALL(void, Marker_tyRef_DL9aQlHvs6h2nnit0jUeC7Q)(void* p, NI op) {
	tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ* a;
	a = (tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ*)p;
	nimGCvisit((void*)(*a).value, op);
}
static N_NIMCALL(void, Marker_tyRef_CBobTOx0GswbKO18xqssIA)(void* p, NI op) {
	tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw* a;
	a = (tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw*)p;
	nimGCvisit((void*)(*a).name.Field2, op);
	nimGCvisit((void*)(*a).name.Field3, op);
}
static N_NIMCALL(void, Marker_tyRef_gMusbyN15UJBRxE8mQITkQ)(void* p, NI op) {
	tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ* a;
	a = (tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ*)p;
	nimGCvisit((void*)(*a).values, op);
}
static N_NIMCALL(void, Marker_tyRef_tx5HDH7XI1F1wmNqlcaw6g)(void* p, NI op) {
	tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ* a;
	a = (tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ*)p;
	nimGCvisit((void*)(*a).arguments, op);
	nimGCvisit((void*)(*a).expression, op);
}
static N_NIMCALL(void, Marker_tyRef_9aHvZsHm9aUiDR6MMbfKGX1g)(void* p, NI op) {
	tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg* a;
	a = (tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg*)p;
	nimGCvisit((void*)(*a).body, op);
}
static N_NIMCALL(void, Marker_tyRef_Ofqzvrn9ciQqdn2DHPB8MaQ)(void* p, NI op) {
	tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg* a;
	a = (tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg*)p;
	nimGCvisit((void*)(*a).arguments, op);
	nimGCvisit((void*)(*a).body, op);
}
static N_NIMCALL(void, Marker_tyRef_d2OzjtAZ2xAFsxCjsp3KeA)(void* p, NI op) {
	tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ* a;
	a = (tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ*)p;
	nimGCvisit((void*)(*a).expression, op);
}
static N_NIMCALL(void, Marker_tyRef_K1dj7759cs8U08D9biGluCQQ)(void* p, NI op) {
	tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA* a;
	a = (tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA*)p;
	nimGCvisit((void*)(*a).callee, op);
	nimGCvisit((void*)(*a).paren.Field2, op);
	nimGCvisit((void*)(*a).paren.Field3, op);
	nimGCvisit((void*)(*a).arguments, op);
}
static N_NIMCALL(void, Marker_tyRef_lQxA8LgwOz1RB2r9crx9a6fg)(void* p, NI op) {
	tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ* a;
	a = (tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ*)p;
	nimGCvisit((void*)(*a).item.Field2, op);
	nimGCvisit((void*)(*a).item.Field3, op);
	nimGCvisit((void*)(*a).index, op);
}
static N_NIMCALL(void, Marker_tyRef_9byfr5Q9c3j9cZwj6B9cKxGVTw)(void* p, NI op) {
	tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q* a;
	a = (tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q*)p;
	nimGCvisit((void*)(*a).operator_0.Field2, op);
	nimGCvisit((void*)(*a).operator_0.Field3, op);
	nimGCvisit((void*)(*a).left, op);
	nimGCvisit((void*)(*a).right, op);
}
static N_NIMCALL(void, Marker_tyRef_zgf9byZOH735gbLd9b6y3Ddw)(void* p, NI op) {
	tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ* a;
	a = (tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ*)p;
	nimGCvisit((void*)(*a).operator_0.Field2, op);
	nimGCvisit((void*)(*a).operator_0.Field3, op);
	nimGCvisit((void*)(*a).left, op);
	nimGCvisit((void*)(*a).right, op);
}
static N_NIMCALL(void, Marker_tyRef_A29aeP1yJWXm58U9bNRz87yQ)(void* p, NI op) {
	tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ* a;
	a = (tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ*)p;
	nimGCvisit((void*)(*a).name.Field2, op);
	nimGCvisit((void*)(*a).name.Field3, op);
	nimGCvisit((void*)(*a).value, op);
}
static N_NIMCALL(void, Marker_tyRef_9b2yF8eg2p3nFw60XJXuC9aQ)(void* p, NI op) {
	tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA* a;
	a = (tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA*)p;
	nimGCvisit((void*)(*a).name.Field2, op);
	nimGCvisit((void*)(*a).name.Field3, op);
	nimGCvisit((void*)(*a).index, op);
	nimGCvisit((void*)(*a).value, op);
}
static N_NIMCALL(void, Marker_tyRef_amAOnss7JKRUudZgJKMrZg)(void* p, NI op) {
	tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA* a;
	a = (tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA*)p;
	nimGCvisit((void*)(*a).condition, op);
	nimGCvisit((void*)(*a).expression, op);
}
static N_NIMCALL(void, Marker_tyRef_REwFzo5GNPW2hz33o9b4sZA)(void* p, NI op) {
	tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA* a;
	a = (tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA*)p;
	nimGCvisit((void*)(*a).condition, op);
	nimGCvisit((void*)(*a).thenBranch, op);
	nimGCvisit((void*)(*a).elseBranch, op);
}
static N_NIMCALL(void, Marker_tyRef_9a9bq2t9b77qCcff6YL5yLsvg)(void* p, NI op) {
	tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A* a;
	a = (tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A*)p;
	nimGCvisit((void*)(*a).expression, op);
}
static N_NIMCALL(void, Marker_tyRef_04BvVjBlmkK2D3Dvo59cE1Q)(void* p, NI op) {
	tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw* a;
	a = (tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw*)p;
	nimGCvisit((void*)(*a).keyword.Field2, op);
	nimGCvisit((void*)(*a).keyword.Field3, op);
	nimGCvisit((void*)(*a).value, op);
}
static N_NIMCALL(void, Marker_tyRef_0nas9cdBOCeb1qHpvxOocGg)(void* p, NI op) {
	tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw* a;
	a = (tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw*)p;
	nimGCvisit((void*)(*a).condition, op);
	nimGCvisit((void*)(*a).body, op);
}
static N_NIMCALL(void, Marker_tyRef_1iwO2mjhvAgjUCXIYlFkzw)(void* p, NI op) {
	tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A* a;
	a = (tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A*)p;
	nimGCvisit((void*)(*a).expression, op);
}
NIM_EXTERNC N_NOINLINE(void, unknown_rulesInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_rulesDatInit000)(void) {
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_31[2];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_32[3];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_33[3];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_34[2];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_35[2];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_36[2];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_37[3];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_38[2];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_39[2];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_40[3];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_41[2];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_42[3];
static TNimNode* TM_e1qf3uIyLveIFu9a9cRtgNyg_43[2];
static TNimNode TM_e1qf3uIyLveIFu9a9cRtgNyg_0[56];
NTI_iy1XUAZvASFmRHhy6Sl3QQ_.size = sizeof(tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ);
NTI_iy1XUAZvASFmRHhy6Sl3QQ_.kind = 17;
NTI_iy1XUAZvASFmRHhy6Sl3QQ_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_iy1XUAZvASFmRHhy6Sl3QQ_.flags = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[0].len = 0; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[0].kind = 2;
NTI_iy1XUAZvASFmRHhy6Sl3QQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[0];
NTI_3MoUzdd6JpcZ1tSX82rd2Q_.size = sizeof(tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q);
NTI_3MoUzdd6JpcZ1tSX82rd2Q_.kind = 17;
NTI_3MoUzdd6JpcZ1tSX82rd2Q_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
NTI_3MoUzdd6JpcZ1tSX82rd2Q_.flags = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[1].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[1].offset = offsetof(tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q, value);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[1].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[1].name = "value";
NTI_3MoUzdd6JpcZ1tSX82rd2Q_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[1];
NTI_H6QC3PBmhdJSmT9cDaRWAAQ_.size = sizeof(tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ);
NTI_H6QC3PBmhdJSmT9cDaRWAAQ_.kind = 17;
NTI_H6QC3PBmhdJSmT9cDaRWAAQ_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[2].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[2].offset = offsetof(tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ, value);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[2].name = "value";
NTI_H6QC3PBmhdJSmT9cDaRWAAQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[2];
NTI_TeU0tViLpeWJ89cheW1wFUg_.size = sizeof(tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg);
NTI_TeU0tViLpeWJ89cheW1wFUg_.kind = 17;
NTI_TeU0tViLpeWJ89cheW1wFUg_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
NTI_TeU0tViLpeWJ89cheW1wFUg_.flags = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[3].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[3].offset = offsetof(tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg, value);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[3].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[3].name = "value";
NTI_TeU0tViLpeWJ89cheW1wFUg_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[3];
NTI_5n4g9cmeh9b6y5ArRowKRuIQ_.size = sizeof(tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ);
NTI_5n4g9cmeh9b6y5ArRowKRuIQ_.kind = 17;
NTI_5n4g9cmeh9b6y5ArRowKRuIQ_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
NTI_NenfDgTNVh6SvXGs80KU2A_.size = sizeof(tyObject_ExpressioncolonObjectType__iy1XUAZvASFmRHhy6Sl3QQ*);
NTI_NenfDgTNVh6SvXGs80KU2A_.kind = 22;
NTI_NenfDgTNVh6SvXGs80KU2A_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
NTI_NenfDgTNVh6SvXGs80KU2A_.marker = Marker_tyRef_NenfDgTNVh6SvXGs80KU2A;
NTI_9bpx44aFIusE9bW4FLAgSGhA_.size = sizeof(tySequence_9bpx44aFIusE9bW4FLAgSGhA*);
NTI_9bpx44aFIusE9bW4FLAgSGhA_.kind = 24;
NTI_9bpx44aFIusE9bW4FLAgSGhA_.base = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
NTI_9bpx44aFIusE9bW4FLAgSGhA_.marker = Marker_tySequence_9bpx44aFIusE9bW4FLAgSGhA;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[4].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[4].offset = offsetof(tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ, values);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[4].typ = (&NTI_9bpx44aFIusE9bW4FLAgSGhA_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[4].name = "values";
NTI_5n4g9cmeh9b6y5ArRowKRuIQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[4];
NTI_xzysDaRkx9b8cniE9aTMy37g_.size = sizeof(tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g);
NTI_xzysDaRkx9b8cniE9aTMy37g_.kind = 17;
NTI_xzysDaRkx9b8cniE9aTMy37g_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
NTI_xzysDaRkx9b8cniE9aTMy37g_.flags = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[5].len = 0; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[5].kind = 2;
NTI_xzysDaRkx9b8cniE9aTMy37g_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[5];
NTI_WJW05mFVFR8R5Re1RdwjkQ_.size = sizeof(tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ);
NTI_WJW05mFVFR8R5Re1RdwjkQ_.kind = 17;
NTI_WJW05mFVFR8R5Re1RdwjkQ_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[6].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[6].offset = offsetof(tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ, expression);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[6].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[6].name = "expression";
NTI_WJW05mFVFR8R5Re1RdwjkQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[6];
NTI_qHyvSBqcF0iFkrOEJDqLyQ_.size = sizeof(tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ);
NTI_qHyvSBqcF0iFkrOEJDqLyQ_.kind = 17;
NTI_qHyvSBqcF0iFkrOEJDqLyQ_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_31[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[8];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[8].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[8].offset = offsetof(tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ, operator_0);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[8].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[8].name = "operator";
TM_e1qf3uIyLveIFu9a9cRtgNyg_31[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[9];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[9].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[9].offset = offsetof(tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ, right);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[9].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[9].name = "right";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[7].len = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[7].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[7].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_31[0];
NTI_qHyvSBqcF0iFkrOEJDqLyQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[7];
NTI_dqD3ROdpQFuI6y9a2nYB32Q_.size = sizeof(tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q);
NTI_dqD3ROdpQFuI6y9a2nYB32Q_.kind = 17;
NTI_dqD3ROdpQFuI6y9a2nYB32Q_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_32[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[11];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[11].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[11].offset = offsetof(tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q, operator_0);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[11].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[11].name = "operator";
TM_e1qf3uIyLveIFu9a9cRtgNyg_32[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[12];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[12].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[12].offset = offsetof(tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q, left);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[12].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[12].name = "left";
TM_e1qf3uIyLveIFu9a9cRtgNyg_32[2] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[13];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[13].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[13].offset = offsetof(tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q, right);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[13].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[13].name = "right";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[10].len = 3; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[10].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[10].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_32[0];
NTI_dqD3ROdpQFuI6y9a2nYB32Q_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[10];
NTI_kRnNrqDqgCDbcfyCYJWfkw_.size = sizeof(tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw);
NTI_kRnNrqDqgCDbcfyCYJWfkw_.kind = 17;
NTI_kRnNrqDqgCDbcfyCYJWfkw_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[14].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[14].offset = offsetof(tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw, name);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[14].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[14].name = "name";
NTI_kRnNrqDqgCDbcfyCYJWfkw_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[14];
NTI_rw8DvbXrFC9cPt2Vhqv9clxQ_.size = sizeof(tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ);
NTI_rw8DvbXrFC9cPt2Vhqv9clxQ_.kind = 17;
NTI_rw8DvbXrFC9cPt2Vhqv9clxQ_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_33[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[16];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[16].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[16].offset = offsetof(tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ, operator_0);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[16].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[16].name = "operator";
TM_e1qf3uIyLveIFu9a9cRtgNyg_33[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[17];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[17].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[17].offset = offsetof(tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ, left);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[17].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[17].name = "left";
TM_e1qf3uIyLveIFu9a9cRtgNyg_33[2] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[18];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[18].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[18].offset = offsetof(tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ, right);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[18].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[18].name = "right";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[15].len = 3; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[15].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[15].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_33[0];
NTI_rw8DvbXrFC9cPt2Vhqv9clxQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[15];
NTI_g3GRisyoY8TUGSo7QDexIw_.size = sizeof(tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw);
NTI_g3GRisyoY8TUGSo7QDexIw_.kind = 17;
NTI_g3GRisyoY8TUGSo7QDexIw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_g3GRisyoY8TUGSo7QDexIw_.flags = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[19].len = 0; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[19].kind = 2;
NTI_g3GRisyoY8TUGSo7QDexIw_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[19];
NTI_K9aIg0VZvCzVPoXP2BYctmw_.size = sizeof(tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw);
NTI_K9aIg0VZvCzVPoXP2BYctmw_.kind = 17;
NTI_K9aIg0VZvCzVPoXP2BYctmw_.base = (&NTI_g3GRisyoY8TUGSo7QDexIw_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_34[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[21];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[21].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[21].offset = offsetof(tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw, keyword);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[21].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[21].name = "keyword";
TM_e1qf3uIyLveIFu9a9cRtgNyg_34[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[22];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[22].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[22].offset = offsetof(tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw, value);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[22].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[22].name = "value";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[20].len = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[20].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[20].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_34[0];
NTI_K9aIg0VZvCzVPoXP2BYctmw_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[20];
NTI_vrDqE1cN4bW1IytyuKpmSQ_.size = sizeof(tyObject_StatementcolonObjectType__g3GRisyoY8TUGSo7QDexIw*);
NTI_vrDqE1cN4bW1IytyuKpmSQ_.kind = 22;
NTI_vrDqE1cN4bW1IytyuKpmSQ_.base = (&NTI_g3GRisyoY8TUGSo7QDexIw_);
NTI_vrDqE1cN4bW1IytyuKpmSQ_.marker = Marker_tyRef_vrDqE1cN4bW1IytyuKpmSQ;
NTI_zFjXHWb6uMsuJNIG9awiuug_.size = sizeof(tyObject_UnarycolonObjectType__qHyvSBqcF0iFkrOEJDqLyQ*);
NTI_zFjXHWb6uMsuJNIG9awiuug_.kind = 22;
NTI_zFjXHWb6uMsuJNIG9awiuug_.base = (&NTI_qHyvSBqcF0iFkrOEJDqLyQ_);
NTI_zFjXHWb6uMsuJNIG9awiuug_.marker = Marker_tyRef_zFjXHWb6uMsuJNIG9awiuug;
NTI_9bTNwoqjfakfBtY05rvxxWw_.size = sizeof(tyObject_BooleancolonObjectType__TeU0tViLpeWJ89cheW1wFUg*);
NTI_9bTNwoqjfakfBtY05rvxxWw_.kind = 22;
NTI_9bTNwoqjfakfBtY05rvxxWw_.base = (&NTI_TeU0tViLpeWJ89cheW1wFUg_);
NTI_9bTNwoqjfakfBtY05rvxxWw_.marker = Marker_tyRef_9bTNwoqjfakfBtY05rvxxWw;
NTI_uZRrfTaV9b4SF3HWx9bwsr2A_.size = sizeof(tyObject_NonecolonObjectType__xzysDaRkx9b8cniE9aTMy37g*);
NTI_uZRrfTaV9b4SF3HWx9bwsr2A_.kind = 22;
NTI_uZRrfTaV9b4SF3HWx9bwsr2A_.base = (&NTI_xzysDaRkx9b8cniE9aTMy37g_);
NTI_uZRrfTaV9b4SF3HWx9bwsr2A_.marker = Marker_tyRef_uZRrfTaV9b4SF3HWx9bwsr2A;
NTI_jdZGByKgvXlIb9b3stA2TIg_.size = sizeof(tyObject_NumbercolonObjectType__3MoUzdd6JpcZ1tSX82rd2Q*);
NTI_jdZGByKgvXlIb9b3stA2TIg_.kind = 22;
NTI_jdZGByKgvXlIb9b3stA2TIg_.base = (&NTI_3MoUzdd6JpcZ1tSX82rd2Q_);
NTI_jdZGByKgvXlIb9b3stA2TIg_.marker = Marker_tyRef_jdZGByKgvXlIb9b3stA2TIg;
NTI_DL9aQlHvs6h2nnit0jUeC7Q_.size = sizeof(tyObject_StringcolonObjectType__H6QC3PBmhdJSmT9cDaRWAAQ*);
NTI_DL9aQlHvs6h2nnit0jUeC7Q_.kind = 22;
NTI_DL9aQlHvs6h2nnit0jUeC7Q_.base = (&NTI_H6QC3PBmhdJSmT9cDaRWAAQ_);
NTI_DL9aQlHvs6h2nnit0jUeC7Q_.marker = Marker_tyRef_DL9aQlHvs6h2nnit0jUeC7Q;
NTI_CBobTOx0GswbKO18xqssIA_.size = sizeof(tyObject_VariablecolonObjectType__kRnNrqDqgCDbcfyCYJWfkw*);
NTI_CBobTOx0GswbKO18xqssIA_.kind = 22;
NTI_CBobTOx0GswbKO18xqssIA_.base = (&NTI_kRnNrqDqgCDbcfyCYJWfkw_);
NTI_CBobTOx0GswbKO18xqssIA_.marker = Marker_tyRef_CBobTOx0GswbKO18xqssIA;
NTI_gMusbyN15UJBRxE8mQITkQ_.size = sizeof(tyObject_ListcolonObjectType__5n4g9cmeh9b6y5ArRowKRuIQ*);
NTI_gMusbyN15UJBRxE8mQITkQ_.kind = 22;
NTI_gMusbyN15UJBRxE8mQITkQ_.base = (&NTI_5n4g9cmeh9b6y5ArRowKRuIQ_);
NTI_gMusbyN15UJBRxE8mQITkQ_.marker = Marker_tyRef_gMusbyN15UJBRxE8mQITkQ;
NTI_u265gaSX0MPT06gifycCyQ_.size = sizeof(tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ);
NTI_u265gaSX0MPT06gifycCyQ_.kind = 17;
NTI_u265gaSX0MPT06gifycCyQ_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_35[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[24];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[24].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[24].offset = offsetof(tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ, arguments);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[24].typ = (&NTI_q5SKz0XShJtOaiDC4VrjTA_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[24].name = "arguments";
TM_e1qf3uIyLveIFu9a9cRtgNyg_35[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[25];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[25].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[25].offset = offsetof(tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ, expression);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[25].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[25].name = "expression";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[23].len = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[23].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[23].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_35[0];
NTI_u265gaSX0MPT06gifycCyQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[23];
NTI_tx5HDH7XI1F1wmNqlcaw6g_.size = sizeof(tyObject_SimpleFunctioncolonObjectType__u265gaSX0MPT06gifycCyQ*);
NTI_tx5HDH7XI1F1wmNqlcaw6g_.kind = 22;
NTI_tx5HDH7XI1F1wmNqlcaw6g_.base = (&NTI_u265gaSX0MPT06gifycCyQ_);
NTI_tx5HDH7XI1F1wmNqlcaw6g_.marker = Marker_tyRef_tx5HDH7XI1F1wmNqlcaw6g;
NTI_x2GjBVvTXMSLFyceo9csgtg_.size = sizeof(tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg);
NTI_x2GjBVvTXMSLFyceo9csgtg_.kind = 17;
NTI_x2GjBVvTXMSLFyceo9csgtg_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_36[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[27];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[27].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[27].offset = offsetof(tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg, arguments);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[27].typ = (&NTI_q5SKz0XShJtOaiDC4VrjTA_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[27].name = "arguments";
TM_e1qf3uIyLveIFu9a9cRtgNyg_36[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[28];
NTI_3PhzvO9b59cuRtHL3meWMYpg_.size = sizeof(tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg);
NTI_3PhzvO9b59cuRtHL3meWMYpg_.kind = 17;
NTI_3PhzvO9b59cuRtHL3meWMYpg_.base = (&NTI_g3GRisyoY8TUGSo7QDexIw_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[29].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[29].offset = offsetof(tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg, body);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[29].typ = (&NTI_x9cl451W8JtBGbwWydXa7PQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[29].name = "body";
NTI_3PhzvO9b59cuRtHL3meWMYpg_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[29];
NTI_9aHvZsHm9aUiDR6MMbfKGX1g_.size = sizeof(tyObject_BlockcolonObjectType__3PhzvO9b59cuRtHL3meWMYpg*);
NTI_9aHvZsHm9aUiDR6MMbfKGX1g_.kind = 22;
NTI_9aHvZsHm9aUiDR6MMbfKGX1g_.base = (&NTI_3PhzvO9b59cuRtHL3meWMYpg_);
NTI_9aHvZsHm9aUiDR6MMbfKGX1g_.marker = Marker_tyRef_9aHvZsHm9aUiDR6MMbfKGX1g;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[28].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[28].offset = offsetof(tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg, body);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[28].typ = (&NTI_9aHvZsHm9aUiDR6MMbfKGX1g_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[28].name = "body";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[26].len = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[26].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[26].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_36[0];
NTI_x2GjBVvTXMSLFyceo9csgtg_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[26];
NTI_Ofqzvrn9ciQqdn2DHPB8MaQ_.size = sizeof(tyObject_FunctioncolonObjectType__x2GjBVvTXMSLFyceo9csgtg*);
NTI_Ofqzvrn9ciQqdn2DHPB8MaQ_.kind = 22;
NTI_Ofqzvrn9ciQqdn2DHPB8MaQ_.base = (&NTI_x2GjBVvTXMSLFyceo9csgtg_);
NTI_Ofqzvrn9ciQqdn2DHPB8MaQ_.marker = Marker_tyRef_Ofqzvrn9ciQqdn2DHPB8MaQ;
NTI_d2OzjtAZ2xAFsxCjsp3KeA_.size = sizeof(tyObject_GroupcolonObjectType__WJW05mFVFR8R5Re1RdwjkQ*);
NTI_d2OzjtAZ2xAFsxCjsp3KeA_.kind = 22;
NTI_d2OzjtAZ2xAFsxCjsp3KeA_.base = (&NTI_WJW05mFVFR8R5Re1RdwjkQ_);
NTI_d2OzjtAZ2xAFsxCjsp3KeA_.marker = Marker_tyRef_d2OzjtAZ2xAFsxCjsp3KeA;
NTI_WilglSQ9aUNqKdPtw9bgGnTA_.size = sizeof(tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA);
NTI_WilglSQ9aUNqKdPtw9bgGnTA_.kind = 17;
NTI_WilglSQ9aUNqKdPtw9bgGnTA_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_37[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[31];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[31].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[31].offset = offsetof(tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA, callee);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[31].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[31].name = "callee";
TM_e1qf3uIyLveIFu9a9cRtgNyg_37[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[32];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[32].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[32].offset = offsetof(tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA, paren);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[32].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[32].name = "paren";
TM_e1qf3uIyLveIFu9a9cRtgNyg_37[2] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[33];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[33].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[33].offset = offsetof(tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA, arguments);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[33].typ = (&NTI_9bpx44aFIusE9bW4FLAgSGhA_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[33].name = "arguments";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[30].len = 3; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[30].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[30].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_37[0];
NTI_WilglSQ9aUNqKdPtw9bgGnTA_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[30];
NTI_K1dj7759cs8U08D9biGluCQQ_.size = sizeof(tyObject_CallcolonObjectType__WilglSQ9aUNqKdPtw9bgGnTA*);
NTI_K1dj7759cs8U08D9biGluCQQ_.kind = 22;
NTI_K1dj7759cs8U08D9biGluCQQ_.base = (&NTI_WilglSQ9aUNqKdPtw9bgGnTA_);
NTI_K1dj7759cs8U08D9biGluCQQ_.marker = Marker_tyRef_K1dj7759cs8U08D9biGluCQQ;
NTI_uxYIijxEkQ8erAyjJzJcOQ_.size = sizeof(tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ);
NTI_uxYIijxEkQ8erAyjJzJcOQ_.kind = 17;
NTI_uxYIijxEkQ8erAyjJzJcOQ_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_38[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[35];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[35].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[35].offset = offsetof(tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ, item);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[35].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[35].name = "item";
TM_e1qf3uIyLveIFu9a9cRtgNyg_38[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[36];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[36].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[36].offset = offsetof(tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ, index);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[36].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[36].name = "index";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[34].len = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[34].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[34].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_38[0];
NTI_uxYIijxEkQ8erAyjJzJcOQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[34];
NTI_lQxA8LgwOz1RB2r9crx9a6fg_.size = sizeof(tyObject_AccesscolonObjectType__uxYIijxEkQ8erAyjJzJcOQ*);
NTI_lQxA8LgwOz1RB2r9crx9a6fg_.kind = 22;
NTI_lQxA8LgwOz1RB2r9crx9a6fg_.base = (&NTI_uxYIijxEkQ8erAyjJzJcOQ_);
NTI_lQxA8LgwOz1RB2r9crx9a6fg_.marker = Marker_tyRef_lQxA8LgwOz1RB2r9crx9a6fg;
NTI_9byfr5Q9c3j9cZwj6B9cKxGVTw_.size = sizeof(tyObject_BinarycolonObjectType__dqD3ROdpQFuI6y9a2nYB32Q*);
NTI_9byfr5Q9c3j9cZwj6B9cKxGVTw_.kind = 22;
NTI_9byfr5Q9c3j9cZwj6B9cKxGVTw_.base = (&NTI_dqD3ROdpQFuI6y9a2nYB32Q_);
NTI_9byfr5Q9c3j9cZwj6B9cKxGVTw_.marker = Marker_tyRef_9byfr5Q9c3j9cZwj6B9cKxGVTw;
NTI_zgf9byZOH735gbLd9b6y3Ddw_.size = sizeof(tyObject_LogicalcolonObjectType__rw8DvbXrFC9cPt2Vhqv9clxQ*);
NTI_zgf9byZOH735gbLd9b6y3Ddw_.kind = 22;
NTI_zgf9byZOH735gbLd9b6y3Ddw_.base = (&NTI_rw8DvbXrFC9cPt2Vhqv9clxQ_);
NTI_zgf9byZOH735gbLd9b6y3Ddw_.marker = Marker_tyRef_zgf9byZOH735gbLd9b6y3Ddw;
NTI_GsCLniDIGL7wguLE00poBQ_.size = sizeof(tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ);
NTI_GsCLniDIGL7wguLE00poBQ_.kind = 17;
NTI_GsCLniDIGL7wguLE00poBQ_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_39[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[38];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[38].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[38].offset = offsetof(tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ, name);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[38].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[38].name = "name";
TM_e1qf3uIyLveIFu9a9cRtgNyg_39[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[39];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[39].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[39].offset = offsetof(tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ, value);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[39].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[39].name = "value";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[37].len = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[37].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[37].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_39[0];
NTI_GsCLniDIGL7wguLE00poBQ_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[37];
NTI_A29aeP1yJWXm58U9bNRz87yQ_.size = sizeof(tyObject_AssigncolonObjectType__GsCLniDIGL7wguLE00poBQ*);
NTI_A29aeP1yJWXm58U9bNRz87yQ_.kind = 22;
NTI_A29aeP1yJWXm58U9bNRz87yQ_.base = (&NTI_GsCLniDIGL7wguLE00poBQ_);
NTI_A29aeP1yJWXm58U9bNRz87yQ_.marker = Marker_tyRef_A29aeP1yJWXm58U9bNRz87yQ;
NTI_44ZOUzoHf9a19bYVak31LkdA_.size = sizeof(tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA);
NTI_44ZOUzoHf9a19bYVak31LkdA_.kind = 17;
NTI_44ZOUzoHf9a19bYVak31LkdA_.base = (&NTI_iy1XUAZvASFmRHhy6Sl3QQ_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_40[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[41];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[41].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[41].offset = offsetof(tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA, name);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[41].typ = (&NTI_KWcIY9c1klZQizoiQC0yHOg_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[41].name = "name";
TM_e1qf3uIyLveIFu9a9cRtgNyg_40[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[42];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[42].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[42].offset = offsetof(tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA, index);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[42].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[42].name = "index";
TM_e1qf3uIyLveIFu9a9cRtgNyg_40[2] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[43];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[43].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[43].offset = offsetof(tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA, value);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[43].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[43].name = "value";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[40].len = 3; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[40].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[40].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_40[0];
NTI_44ZOUzoHf9a19bYVak31LkdA_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[40];
NTI_9b2yF8eg2p3nFw60XJXuC9aQ_.size = sizeof(tyObject_AssignAccesscolonObjectType__44ZOUzoHf9a19bYVak31LkdA*);
NTI_9b2yF8eg2p3nFw60XJXuC9aQ_.kind = 22;
NTI_9b2yF8eg2p3nFw60XJXuC9aQ_.base = (&NTI_44ZOUzoHf9a19bYVak31LkdA_);
NTI_9b2yF8eg2p3nFw60XJXuC9aQ_.marker = Marker_tyRef_9b2yF8eg2p3nFw60XJXuC9aQ;
NTI_x9aL9cMYr9cCbSrhkSWnryVvA_.size = sizeof(tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA);
NTI_x9aL9cMYr9cCbSrhkSWnryVvA_.kind = 17;
NTI_x9aL9cMYr9cCbSrhkSWnryVvA_.base = (&NTI_g3GRisyoY8TUGSo7QDexIw_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_41[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[45];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[45].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[45].offset = offsetof(tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA, condition);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[45].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[45].name = "condition";
TM_e1qf3uIyLveIFu9a9cRtgNyg_41[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[46];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[46].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[46].offset = offsetof(tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA, expression);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[46].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[46].name = "expression";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[44].len = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[44].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[44].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_41[0];
NTI_x9aL9cMYr9cCbSrhkSWnryVvA_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[44];
NTI_amAOnss7JKRUudZgJKMrZg_.size = sizeof(tyObject_SimpleIfcolonObjectType__x9aL9cMYr9cCbSrhkSWnryVvA*);
NTI_amAOnss7JKRUudZgJKMrZg_.kind = 22;
NTI_amAOnss7JKRUudZgJKMrZg_.base = (&NTI_x9aL9cMYr9cCbSrhkSWnryVvA_);
NTI_amAOnss7JKRUudZgJKMrZg_.marker = Marker_tyRef_amAOnss7JKRUudZgJKMrZg;
NTI_8cjtRrEFjHGd6Y7na7NGlA_.size = sizeof(tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA);
NTI_8cjtRrEFjHGd6Y7na7NGlA_.kind = 17;
NTI_8cjtRrEFjHGd6Y7na7NGlA_.base = (&NTI_g3GRisyoY8TUGSo7QDexIw_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_42[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[48];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[48].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[48].offset = offsetof(tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA, condition);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[48].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[48].name = "condition";
TM_e1qf3uIyLveIFu9a9cRtgNyg_42[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[49];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[49].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[49].offset = offsetof(tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA, thenBranch);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[49].typ = (&NTI_9aHvZsHm9aUiDR6MMbfKGX1g_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[49].name = "thenBranch";
TM_e1qf3uIyLveIFu9a9cRtgNyg_42[2] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[50];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[50].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[50].offset = offsetof(tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA, elseBranch);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[50].typ = (&NTI_9aHvZsHm9aUiDR6MMbfKGX1g_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[50].name = "elseBranch";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[47].len = 3; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[47].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[47].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_42[0];
NTI_8cjtRrEFjHGd6Y7na7NGlA_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[47];
NTI_REwFzo5GNPW2hz33o9b4sZA_.size = sizeof(tyObject_IfcolonObjectType__8cjtRrEFjHGd6Y7na7NGlA*);
NTI_REwFzo5GNPW2hz33o9b4sZA_.kind = 22;
NTI_REwFzo5GNPW2hz33o9b4sZA_.base = (&NTI_8cjtRrEFjHGd6Y7na7NGlA_);
NTI_REwFzo5GNPW2hz33o9b4sZA_.marker = Marker_tyRef_REwFzo5GNPW2hz33o9b4sZA;
NTI_gws4iaqmhdyLuikDU0Kd4A_.size = sizeof(tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A);
NTI_gws4iaqmhdyLuikDU0Kd4A_.kind = 17;
NTI_gws4iaqmhdyLuikDU0Kd4A_.base = (&NTI_g3GRisyoY8TUGSo7QDexIw_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[51].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[51].offset = offsetof(tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A, expression);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[51].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[51].name = "expression";
NTI_gws4iaqmhdyLuikDU0Kd4A_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[51];
NTI_9a9bq2t9b77qCcff6YL5yLsvg_.size = sizeof(tyObject_PrintcolonObjectType__gws4iaqmhdyLuikDU0Kd4A*);
NTI_9a9bq2t9b77qCcff6YL5yLsvg_.kind = 22;
NTI_9a9bq2t9b77qCcff6YL5yLsvg_.base = (&NTI_gws4iaqmhdyLuikDU0Kd4A_);
NTI_9a9bq2t9b77qCcff6YL5yLsvg_.marker = Marker_tyRef_9a9bq2t9b77qCcff6YL5yLsvg;
NTI_04BvVjBlmkK2D3Dvo59cE1Q_.size = sizeof(tyObject_ReturncolonObjectType__K9aIg0VZvCzVPoXP2BYctmw*);
NTI_04BvVjBlmkK2D3Dvo59cE1Q_.kind = 22;
NTI_04BvVjBlmkK2D3Dvo59cE1Q_.base = (&NTI_K9aIg0VZvCzVPoXP2BYctmw_);
NTI_04BvVjBlmkK2D3Dvo59cE1Q_.marker = Marker_tyRef_04BvVjBlmkK2D3Dvo59cE1Q;
NTI_5M9ar9bYql9bg3tWBfZPXpTFw_.size = sizeof(tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw);
NTI_5M9ar9bYql9bg3tWBfZPXpTFw_.kind = 17;
NTI_5M9ar9bYql9bg3tWBfZPXpTFw_.base = (&NTI_g3GRisyoY8TUGSo7QDexIw_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_43[0] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[53];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[53].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[53].offset = offsetof(tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw, condition);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[53].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[53].name = "condition";
TM_e1qf3uIyLveIFu9a9cRtgNyg_43[1] = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[54];
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[54].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[54].offset = offsetof(tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw, body);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[54].typ = (&NTI_9aHvZsHm9aUiDR6MMbfKGX1g_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[54].name = "body";
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[52].len = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[52].kind = 2; TM_e1qf3uIyLveIFu9a9cRtgNyg_0[52].sons = &TM_e1qf3uIyLveIFu9a9cRtgNyg_43[0];
NTI_5M9ar9bYql9bg3tWBfZPXpTFw_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[52];
NTI_0nas9cdBOCeb1qHpvxOocGg_.size = sizeof(tyObject_WhilecolonObjectType__5M9ar9bYql9bg3tWBfZPXpTFw*);
NTI_0nas9cdBOCeb1qHpvxOocGg_.kind = 22;
NTI_0nas9cdBOCeb1qHpvxOocGg_.base = (&NTI_5M9ar9bYql9bg3tWBfZPXpTFw_);
NTI_0nas9cdBOCeb1qHpvxOocGg_.marker = Marker_tyRef_0nas9cdBOCeb1qHpvxOocGg;
NTI_0fTeFc1ncIUGvG6ZDbWW3A_.size = sizeof(tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A);
NTI_0fTeFc1ncIUGvG6ZDbWW3A_.kind = 17;
NTI_0fTeFc1ncIUGvG6ZDbWW3A_.base = (&NTI_g3GRisyoY8TUGSo7QDexIw_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[55].kind = 1;
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[55].offset = offsetof(tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A, expression);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[55].typ = (&NTI_NenfDgTNVh6SvXGs80KU2A_);
TM_e1qf3uIyLveIFu9a9cRtgNyg_0[55].name = "expression";
NTI_0fTeFc1ncIUGvG6ZDbWW3A_.node = &TM_e1qf3uIyLveIFu9a9cRtgNyg_0[55];
NTI_1iwO2mjhvAgjUCXIYlFkzw_.size = sizeof(tyObject_ExpressionStatementcolonObjectType__0fTeFc1ncIUGvG6ZDbWW3A*);
NTI_1iwO2mjhvAgjUCXIYlFkzw_.kind = 22;
NTI_1iwO2mjhvAgjUCXIYlFkzw_.base = (&NTI_0fTeFc1ncIUGvG6ZDbWW3A_);
NTI_1iwO2mjhvAgjUCXIYlFkzw_.marker = Marker_tyRef_1iwO2mjhvAgjUCXIYlFkzw;
}

