/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/erik/.choosenim/toolchains/nim-0.18.0/lib -o /home/erik/Code/TFG/void/NimVoid/src/nimcache/std.o /home/erik/Code/TFG/void/NimVoid/src/nimcache/std.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg;
typedef struct tySequence_RGI7x8xRcqqyfGoCDX4zJQ tySequence_RGI7x8xRcqqyfGoCDX4zJQ;
typedef struct tyTuple_7lOBCx9cCrvEawWBqjuj8vQ tyTuple_7lOBCx9cCrvEawWBqjuj8vQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_g8wWagWtbBE4jkij9axgDjA tySequence_g8wWagWtbBE4jkij9axgDjA;
typedef struct tyTuple_p7Uw0BAWm1JV3F8w0mhMOA tyTuple_p7Uw0BAWm1JV3F8w0mhMOA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA;
typedef struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ;
typedef struct RootObj RootObj;
typedef struct tyTuple_M3y5mHl2OtcVFI81N2j0DQ tyTuple_M3y5mHl2OtcVFI81N2j0DQ;
typedef struct tyTuple_mfj8s9cvmtjfv2tUmnpfuug tyTuple_mfj8s9cvmtjfv2tUmnpfuug;
typedef struct tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA;
typedef struct tySequence_49cSLhOXtIXPXzKKaGFU0eQ tySequence_49cSLhOXtIXPXzKKaGFU0eQ;
typedef struct tySequence_rl1wTgiGRBZamH1pllm1bA tySequence_rl1wTgiGRBZamH1pllm1bA;
typedef struct tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg;
typedef struct tyObject_Table_zjMaDBasw1LnKbj11akpfw tyObject_Table_zjMaDBasw1LnKbj11akpfw;
typedef struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og tySequence_pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg;
typedef struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw;
typedef struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ tySequence_JAV0yhDlrNFYdAVDw2r39bQ;
typedef struct tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ tyTuple_zXBGqNygOt4DlBCAX3NcVQ;
struct tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg {
tySequence_RGI7x8xRcqqyfGoCDX4zJQ* data;
NI counter;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_7lOBCx9cCrvEawWBqjuj8vQ {
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field0;
tySequence_g8wWagWtbBE4jkij9axgDjA* Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA {
NimStringDesc* Field0;
tyTuple_7lOBCx9cCrvEawWBqjuj8vQ Field1;
};
typedef tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA tyArray_BYh7gvjpl9aW87YpAI4YBoA[2];
typedef NU8 tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw {
  RootObj Sup;
};
struct tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NimStringDesc* value;
};
struct tyTuple_mfj8s9cvmtjfv2tUmnpfuug {
NI Field0;
NimStringDesc* Field1;
tyTuple_7lOBCx9cCrvEawWBqjuj8vQ Field2;
};
struct tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NF value;
};
struct tyObject_Table_zjMaDBasw1LnKbj11akpfw {
tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* data;
NI counter;
};
struct tyTuple_M3y5mHl2OtcVFI81N2j0DQ {
tySequence_g8wWagWtbBE4jkij9axgDjA* Field0;
tySequence_49cSLhOXtIXPXzKKaGFU0eQ* Field1;
tySequence_rl1wTgiGRBZamH1pllm1bA* Field2;
tyObject_Table_zjMaDBasw1LnKbj11akpfw Field3;
NI Field4;
NI Field5;
};
struct tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
};
struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw {
tySequence_JAV0yhDlrNFYdAVDw2r39bQ* data;
NI counter;
};
struct tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg {
tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw Field0;
NI Field1;
};
struct tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NI arguments;
tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* frame;
NimStringDesc* label;
};
struct tyTuple_p7Uw0BAWm1JV3F8w0mhMOA {
tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw Field0;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field1;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ {
NI Field0;
NimStringDesc* Field1;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field2;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_g8wWagWtbBE4jkij9axgDjA {
  TGenericSeq Sup;
  tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* data[SEQ_DECL_SIZE];
};
struct tySequence_49cSLhOXtIXPXzKKaGFU0eQ {
  TGenericSeq Sup;
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* data[SEQ_DECL_SIZE];
};
struct tySequence_rl1wTgiGRBZamH1pllm1bA {
  TGenericSeq Sup;
  tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* data[SEQ_DECL_SIZE];
};
struct tySequence_RGI7x8xRcqqyfGoCDX4zJQ {
  TGenericSeq Sup;
  tyTuple_mfj8s9cvmtjfv2tUmnpfuug data[SEQ_DECL_SIZE];
};
struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og {
  TGenericSeq Sup;
  tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ {
  TGenericSeq Sup;
  tyTuple_zXBGqNygOt4DlBCAX3NcVQ data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_g8wWagWtbBE4jkij9axgDjA)(void* p, NI op);
static N_NIMCALL(void, TM_wubxbolkTA1TY8xDgnKDMA_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, toTable_7LYUurmrFBFgKXxLkOoxXQ)(tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA* pairs, NI pairsLen_0, tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* Result);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, createFun_2waq5KT0GCdOAKG1GblEew)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* arguments, tySequence_g8wWagWtbBE4jkij9axgDjA* instructions, tyTuple_7lOBCx9cCrvEawWBqjuj8vQ* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*, newInstruction_v3erJGxJlXuevon1DXWGig)(tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw kind, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, tempLabel_4BbOJaErQoxvC9cm3k9cGHvA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm);
N_LIB_PRIVATE N_NIMCALL(void, add_E3g4xDBK9cp2YYvK9cfQDRDg)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw kind, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5D__9cTh0NZIzKMVpNtO46NirYg)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg t, NimStringDesc* key, tyTuple_7lOBCx9cCrvEawWBqjuj8vQ* Result);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__HW88TTiOGEbkbPlPS00naA)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t, NimStringDesc* key, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* val);
tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg lib_iNoydHbUloYrhihWBvTkxQ;
TNimType NTI_7lOBCx9cCrvEawWBqjuj8vQ_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_JDXL0YFnlY6q2ZZ2NGY75A_;
TNimType NTI_g8wWagWtbBE4jkij9axgDjA_;
extern TNimType NTI_9aV9cyUfSVEvrEHigJPwqVqg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_;
extern TNimType NTI_PO9bUMXtlWXaezrslbDbWhQ_;
extern TNimType NTI_gOxHjz9bS5yarbZPfCpiI9ag_;
extern TNimType NTI_560SkOiRWWBbF6rm9aw64dA_;
extern TNimType NTI_wxtX2Dn9bLzkwATjviHoHPw_;
extern TNimType NTI_tKCpk3v6uzTPdzngd4khKg_;
extern TNimType NTI_y9c6dv0kMrsaxQCTP1qYOAA_;
extern TNimType NTI_FIkPLrBpEJy6rtwh9bFNTRA_;
STRING_LITERAL(TM_wubxbolkTA1TY8xDgnKDMA_4, "len", 3);
STRING_LITERAL(TM_wubxbolkTA1TY8xDgnKDMA_6, "e", 1);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[1];
} TM_wubxbolkTA1TY8xDgnKDMA_7 = {{1, 1}, {((NimStringDesc*) &TM_wubxbolkTA1TY8xDgnKDMA_6)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_wubxbolkTA1TY8xDgnKDMA_5 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_wubxbolkTA1TY8xDgnKDMA_7);
STRING_LITERAL(TM_wubxbolkTA1TY8xDgnKDMA_8, "push", 4);
STRING_LITERAL(TM_wubxbolkTA1TY8xDgnKDMA_10, "l", 1);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[2];
} TM_wubxbolkTA1TY8xDgnKDMA_11 = {{2, 2}, {((NimStringDesc*) &TM_wubxbolkTA1TY8xDgnKDMA_6),
((NimStringDesc*) &TM_wubxbolkTA1TY8xDgnKDMA_10)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_wubxbolkTA1TY8xDgnKDMA_9 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_wubxbolkTA1TY8xDgnKDMA_11);
static N_NIMCALL(void, Marker_tySequence_g8wWagWtbBE4jkij9axgDjA)(void* p, NI op) {
	tySequence_g8wWagWtbBE4jkij9axgDjA* a;
	NI T1_;
	a = (tySequence_g8wWagWtbBE4jkij9axgDjA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, TM_wubxbolkTA1TY8xDgnKDMA_3)(void) {
	nimGCvisit((void*)lib_iNoydHbUloYrhihWBvTkxQ.data, 0);
}

N_LIB_PRIVATE N_NIMCALL(void, createFun_2waq5KT0GCdOAKG1GblEew)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* arguments, tySequence_g8wWagWtbBE4jkij9axgDjA* instructions, tyTuple_7lOBCx9cCrvEawWBqjuj8vQ* Result) {
	genericReset((void*)Result, (&NTI_7lOBCx9cCrvEawWBqjuj8vQ_));
	genericSeqAssign((&(*Result).Field0), arguments, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	genericSeqAssign((&(*Result).Field1), instructions, (&NTI_g8wWagWtbBE4jkij9axgDjA_));
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, addStdLib_3tzcmdTZgTPHKq6Vh9bz53A)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm) {
	{
		NimStringDesc* k;
		k = (NimStringDesc*)0;
		{
			NI h;
			NI colontmp_;
			NI T3_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			T3_ = (lib_iNoydHbUloYrhihWBvTkxQ.data ? (lib_iNoydHbUloYrhihWBvTkxQ.data->Sup.len-1) : -1);
			colontmp_ = T3_;
			res = ((NI) 0);
			{
				while (1) {
					if (!(res <= colontmp_)) goto LA5;
					h = res;
					{
						NIM_BOOL T8_;
						NimStringDesc* startLabel;
						NimStringDesc* endLabel;
						tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T11_;
						NimStringDesc* T12_;
						tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T13_;
						tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T14_;
						NimStringDesc* T15_;
						tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T16_;
						tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA* T17_;
						tyTuple_7lOBCx9cCrvEawWBqjuj8vQ T18_;
						NI T19_;
						tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T20_;
						tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T21_;
						NimStringDesc* T22_;
						tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T23_;
						tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg* T38_;
						tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T39_;
						tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T40_;
						NimStringDesc* T41_;
						tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T42_;
						tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* frame;
						NI T43_;
						tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA* T44_;
						NimStringDesc* T45_;
						tyTuple_7lOBCx9cCrvEawWBqjuj8vQ T46_;
						NI T47_;
						tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T48_;
						T8_ = (NIM_BOOL)0;
						T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(lib_iNoydHbUloYrhihWBvTkxQ.data->data[h].Field0);
						if (!T8_) goto LA9_;
						k = lib_iNoydHbUloYrhihWBvTkxQ.data->data[h].Field1;
						startLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
						endLabel = tempLabel_4BbOJaErQoxvC9cm3k9cGHvA(vm);
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
						T11_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
						T11_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
						(*T11_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
						T12_ = (NimStringDesc*)0;
						T12_ = (*T11_).value; (*T11_).value = copyStringRC1(startLabel);
						if (T12_) nimGCunrefNoCycle(T12_);
						T13_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
						T13_ = &T11_->Sup;
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T13_);
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
						T14_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
						T14_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
						(*T14_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
						T15_ = (NimStringDesc*)0;
						T15_ = (*T14_).value; (*T14_).value = copyStringRC1(endLabel);
						if (T15_) nimGCunrefNoCycle(T15_);
						T16_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
						T16_ = &T14_->Sup;
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T16_);
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
						T17_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*)0;
						T17_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) newObj((&NTI_gOxHjz9bS5yarbZPfCpiI9ag_), sizeof(tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA));
						(*T17_).Sup.Sup.m_type = (&NTI_560SkOiRWWBbF6rm9aw64dA_);
						memset((void*)(&T18_), 0, sizeof(T18_));
						X5BX5D__9cTh0NZIzKMVpNtO46NirYg(lib_iNoydHbUloYrhihWBvTkxQ, k, (&T18_));
						T19_ = (T18_.Field0 ? T18_.Field0->Sup.len : 0);
						(*T17_).value = ((NF) (T19_));
						T20_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
						T20_ = &T17_->Sup;
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T20_);
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 29), NIM_NIL);
						T21_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
						T21_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
						(*T21_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
						T22_ = (NimStringDesc*)0;
						T22_ = (*T21_).value; (*T21_).value = copyStringRC1(startLabel);
						if (T22_) nimGCunrefNoCycle(T22_);
						T23_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
						T23_ = &T21_->Sup;
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T23_);
						{
							NimStringDesc* v;
							tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp__2;
							tyTuple_7lOBCx9cCrvEawWBqjuj8vQ T25_;
							NI i;
							NI L;
							NI T26_;
							v = (NimStringDesc*)0;
							colontmp__2 = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
							memset((void*)(&T25_), 0, sizeof(T25_));
							X5BX5D__9cTh0NZIzKMVpNtO46NirYg(lib_iNoydHbUloYrhihWBvTkxQ, k, (&T25_));
							colontmp__2 = T25_.Field0;
							i = ((NI) 0);
							T26_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
							L = T26_;
							{
								while (1) {
									tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T29_;
									NimStringDesc* T30_;
									tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T31_;
									if (!(i < L)) goto LA28;
									v = colontmp__2->data[i];
									add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 26), NIM_NIL);
									T29_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
									T29_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
									(*T29_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
									T30_ = (NimStringDesc*)0;
									T30_ = (*T29_).value; (*T29_).value = copyStringRC1(v);
									if (T30_) nimGCunrefNoCycle(T30_);
									T31_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
									T31_ = &T29_->Sup;
									add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T31_);
									i += ((NI) 1);
								} LA28: ;
							}
						}
						{
							tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* i_2;
							tySequence_g8wWagWtbBE4jkij9axgDjA* colontmp__3;
							tyTuple_7lOBCx9cCrvEawWBqjuj8vQ T33_;
							NI i_3;
							NI L_2;
							NI T34_;
							i_2 = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
							colontmp__3 = (tySequence_g8wWagWtbBE4jkij9axgDjA*)0;
							memset((void*)(&T33_), 0, sizeof(T33_));
							X5BX5D__9cTh0NZIzKMVpNtO46NirYg(lib_iNoydHbUloYrhihWBvTkxQ, k, (&T33_));
							colontmp__3 = T33_.Field1;
							i_3 = ((NI) 0);
							T34_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
							L_2 = T34_;
							{
								while (1) {
									NI T37_;
									if (!(i_3 < L_2)) goto LA36;
									i_2 = colontmp__3->data[i_3];
									(*vm).Field0 = (tySequence_g8wWagWtbBE4jkij9axgDjA*) incrSeqV2(&((*vm).Field0)->Sup, sizeof(tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*));
									T37_ = (*vm).Field0->Sup.len++;
									asgnRef((void**) (&(*vm).Field0->data[T37_]), i_2);
									i_3 += ((NI) 1);
								} LA36: ;
							}
						}
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1), NIM_NIL);
						T38_ = (tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg*)0;
						T38_ = (tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg*) newObj((&NTI_wxtX2Dn9bLzkwATjviHoHPw_), sizeof(tyObject_NoneValuecolonObjectType__tKCpk3v6uzTPdzngd4khKg));
						(*T38_).Sup.Sup.m_type = (&NTI_tKCpk3v6uzTPdzngd4khKg_);
						T39_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
						T39_ = &T38_->Sup;
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T39_);
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 31), NIM_NIL);
						T40_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
						T40_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
						(*T40_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
						T41_ = (NimStringDesc*)0;
						T41_ = (*T40_).value; (*T40_).value = copyStringRC1(endLabel);
						if (T41_) nimGCunrefNoCycle(T41_);
						T42_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
						T42_ = &T40_->Sup;
						add_E3g4xDBK9cp2YYvK9cfQDRDg(vm, ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4), T42_);
						T43_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
						frame = (*vm).Field2->data[(NI)(T43_ - ((NI) 1))];
						T44_ = (tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA*)0;
						T44_ = (tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA*) newObj((&NTI_y9c6dv0kMrsaxQCTP1qYOAA_), sizeof(tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA));
						(*T44_).Sup.Sup.m_type = (&NTI_FIkPLrBpEJy6rtwh9bFNTRA_);
						T45_ = (NimStringDesc*)0;
						T45_ = (*T44_).label; (*T44_).label = copyStringRC1(startLabel);
						if (T45_) nimGCunrefNoCycle(T45_);
						asgnRef((void**) (&(*T44_).frame), frame);
						memset((void*)(&T46_), 0, sizeof(T46_));
						X5BX5D__9cTh0NZIzKMVpNtO46NirYg(lib_iNoydHbUloYrhihWBvTkxQ, k, (&T46_));
						T47_ = (T46_.Field0 ? T46_.Field0->Sup.len : 0);
						(*T44_).arguments = T47_;
						T48_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
						T48_ = &T44_->Sup;
						X5BX5Deq__HW88TTiOGEbkbPlPS00naA((&(*frame).Field0), k, T48_);
					}
					LA9_: ;
					res += ((NI) 1);
				} LA5: ;
			}
		}
	}
}
NIM_EXTERNC N_NOINLINE(void, unknown_stdInit000)(void) {
	tyArray_BYh7gvjpl9aW87YpAI4YBoA T1_;
	tySequence_g8wWagWtbBE4jkij9axgDjA* T2_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T3_;
	NimStringDesc* T4_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T5_;
	tySequence_g8wWagWtbBE4jkij9axgDjA* T6_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T7_;
	NimStringDesc* T8_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T9_;
	tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* T10_;
	NimStringDesc* T11_;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T12_;
nimRegisterGlobalMarker(TM_wubxbolkTA1TY8xDgnKDMA_3);
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0].Field0 = copyString(((NimStringDesc*) &TM_wubxbolkTA1TY8xDgnKDMA_4));
	T2_ = (tySequence_g8wWagWtbBE4jkij9axgDjA*)0;
	T2_ = (tySequence_g8wWagWtbBE4jkij9axgDjA*) newSeq((&NTI_g8wWagWtbBE4jkij9axgDjA_), 4);
	asgnRef((void**) (&T2_->data[0]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 27), NIM_NIL));
	T3_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T3_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T3_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T4_ = (NimStringDesc*)0;
	T4_ = (*T3_).value; (*T3_).value = copyStringRC1(((NimStringDesc*) &TM_wubxbolkTA1TY8xDgnKDMA_6));
	if (T4_) nimGCunrefNoCycle(T4_);
	T5_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T5_ = &T3_->Sup;
	asgnRef((void**) (&T2_->data[1]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T5_));
	asgnRef((void**) (&T2_->data[2]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 37), NIM_NIL));
	asgnRef((void**) (&T2_->data[3]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 31), NIM_NIL));
	createFun_2waq5KT0GCdOAKG1GblEew(TM_wubxbolkTA1TY8xDgnKDMA_5, T2_, (&T1_[0].Field1));
	T1_[1].Field0 = copyString(((NimStringDesc*) &TM_wubxbolkTA1TY8xDgnKDMA_8));
	T6_ = (tySequence_g8wWagWtbBE4jkij9axgDjA*)0;
	T6_ = (tySequence_g8wWagWtbBE4jkij9axgDjA*) newSeq((&NTI_g8wWagWtbBE4jkij9axgDjA_), 6);
	asgnRef((void**) (&T6_->data[0]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 27), NIM_NIL));
	T7_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T7_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T7_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T8_ = (NimStringDesc*)0;
	T8_ = (*T7_).value; (*T7_).value = copyStringRC1(((NimStringDesc*) &TM_wubxbolkTA1TY8xDgnKDMA_6));
	if (T8_) nimGCunrefNoCycle(T8_);
	T9_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T9_ = &T7_->Sup;
	asgnRef((void**) (&T6_->data[1]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T9_));
	asgnRef((void**) (&T6_->data[2]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 27), NIM_NIL));
	T10_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*)0;
	T10_ = (tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) newObj((&NTI_eTxP9aHZt79bG9aSLwJsrW9bYA_), sizeof(tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ));
	(*T10_).Sup.Sup.m_type = (&NTI_PO9bUMXtlWXaezrslbDbWhQ_);
	T11_ = (NimStringDesc*)0;
	T11_ = (*T10_).value; (*T10_).value = copyStringRC1(((NimStringDesc*) &TM_wubxbolkTA1TY8xDgnKDMA_10));
	if (T11_) nimGCunrefNoCycle(T11_);
	T12_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	T12_ = &T10_->Sup;
	asgnRef((void**) (&T6_->data[3]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6), T12_));
	asgnRef((void**) (&T6_->data[4]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 38), NIM_NIL));
	asgnRef((void**) (&T6_->data[5]), newInstruction_v3erJGxJlXuevon1DXWGig(((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 31), NIM_NIL));
	createFun_2waq5KT0GCdOAKG1GblEew(TM_wubxbolkTA1TY8xDgnKDMA_9, T6_, (&T1_[1].Field1));
	toTable_7LYUurmrFBFgKXxLkOoxXQ(T1_, 2, (&lib_iNoydHbUloYrhihWBvTkxQ));
}

NIM_EXTERNC N_NOINLINE(void, unknown_stdDatInit000)(void) {
static TNimNode* TM_wubxbolkTA1TY8xDgnKDMA_2[2];
static TNimNode TM_wubxbolkTA1TY8xDgnKDMA_0[3];
NTI_7lOBCx9cCrvEawWBqjuj8vQ_.size = sizeof(tyTuple_7lOBCx9cCrvEawWBqjuj8vQ);
NTI_7lOBCx9cCrvEawWBqjuj8vQ_.kind = 18;
NTI_7lOBCx9cCrvEawWBqjuj8vQ_.base = 0;
TM_wubxbolkTA1TY8xDgnKDMA_2[0] = &TM_wubxbolkTA1TY8xDgnKDMA_0[1];
TM_wubxbolkTA1TY8xDgnKDMA_0[1].kind = 1;
TM_wubxbolkTA1TY8xDgnKDMA_0[1].offset = offsetof(tyTuple_7lOBCx9cCrvEawWBqjuj8vQ, Field0);
TM_wubxbolkTA1TY8xDgnKDMA_0[1].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_wubxbolkTA1TY8xDgnKDMA_0[1].name = "Field0";
TM_wubxbolkTA1TY8xDgnKDMA_2[1] = &TM_wubxbolkTA1TY8xDgnKDMA_0[2];
NTI_g8wWagWtbBE4jkij9axgDjA_.size = sizeof(tySequence_g8wWagWtbBE4jkij9axgDjA*);
NTI_g8wWagWtbBE4jkij9axgDjA_.kind = 24;
NTI_g8wWagWtbBE4jkij9axgDjA_.base = (&NTI_JDXL0YFnlY6q2ZZ2NGY75A_);
NTI_g8wWagWtbBE4jkij9axgDjA_.marker = Marker_tySequence_g8wWagWtbBE4jkij9axgDjA;
TM_wubxbolkTA1TY8xDgnKDMA_0[2].kind = 1;
TM_wubxbolkTA1TY8xDgnKDMA_0[2].offset = offsetof(tyTuple_7lOBCx9cCrvEawWBqjuj8vQ, Field1);
TM_wubxbolkTA1TY8xDgnKDMA_0[2].typ = (&NTI_g8wWagWtbBE4jkij9axgDjA_);
TM_wubxbolkTA1TY8xDgnKDMA_0[2].name = "Field1";
TM_wubxbolkTA1TY8xDgnKDMA_0[0].len = 2; TM_wubxbolkTA1TY8xDgnKDMA_0[0].kind = 2; TM_wubxbolkTA1TY8xDgnKDMA_0[0].sons = &TM_wubxbolkTA1TY8xDgnKDMA_2[0];
NTI_7lOBCx9cCrvEawWBqjuj8vQ_.node = &TM_wubxbolkTA1TY8xDgnKDMA_0[0];
}

