/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/erik/.choosenim/toolchains/nim-0.18.0/lib -o /home/erik/Code/TFG/void/NimVoid/src/nimcache/stdlib_tables.o /home/erik/Code/TFG/void/NimVoid/src/nimcache/stdlib_tables.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw;
typedef struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ tySequence_JAV0yhDlrNFYdAVDw2r39bQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ tyTuple_zXBGqNygOt4DlBCAX3NcVQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw;
typedef struct tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg;
typedef struct tySequence_RGI7x8xRcqqyfGoCDX4zJQ tySequence_RGI7x8xRcqqyfGoCDX4zJQ;
typedef struct tyTuple_mfj8s9cvmtjfv2tUmnpfuug tyTuple_mfj8s9cvmtjfv2tUmnpfuug;
typedef struct tyTuple_7lOBCx9cCrvEawWBqjuj8vQ tyTuple_7lOBCx9cCrvEawWBqjuj8vQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence_g8wWagWtbBE4jkij9axgDjA tySequence_g8wWagWtbBE4jkij9axgDjA;
typedef struct tyTuple_p7Uw0BAWm1JV3F8w0mhMOA tyTuple_p7Uw0BAWm1JV3F8w0mhMOA;
typedef struct tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Table_pntvPsgDJ7q7yAcWyvfffA tyObject_Table_pntvPsgDJ7q7yAcWyvfffA;
typedef struct tySequence_ABPSpAd6GJPBDOgnx8Xaeg tySequence_ABPSpAd6GJPBDOgnx8Xaeg;
typedef struct tyTuple_CqK5avyg59bVH4ni9ajbhfNw tyTuple_CqK5avyg59bVH4ni9ajbhfNw;
typedef struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Table_zjMaDBasw1LnKbj11akpfw tyObject_Table_zjMaDBasw1LnKbj11akpfw;
typedef struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og tySequence_pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw {
tySequence_JAV0yhDlrNFYdAVDw2r39bQ* data;
NI counter;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ {
NI Field0;
NimStringDesc* Field1;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field2;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg {
tySequence_RGI7x8xRcqqyfGoCDX4zJQ* data;
NI counter;
};
struct tyTuple_7lOBCx9cCrvEawWBqjuj8vQ {
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field0;
tySequence_g8wWagWtbBE4jkij9axgDjA* Field1;
};
struct tyTuple_mfj8s9cvmtjfv2tUmnpfuug {
NI Field0;
NimStringDesc* Field1;
tyTuple_7lOBCx9cCrvEawWBqjuj8vQ Field2;
};
struct tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA {
NimStringDesc* Field0;
tyTuple_7lOBCx9cCrvEawWBqjuj8vQ Field1;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Table_pntvPsgDJ7q7yAcWyvfffA {
tySequence_ABPSpAd6GJPBDOgnx8Xaeg* data;
NI counter;
};
typedef NU8 tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A;
struct tyTuple_CqK5avyg59bVH4ni9ajbhfNw {
NI Field0;
NimStringDesc* Field1;
tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A Field2;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
struct tyObject_Table_zjMaDBasw1LnKbj11akpfw {
tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* data;
NI counter;
};
struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw {
  RootObj Sup;
};
typedef NU8 tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw;
struct tyTuple_p7Uw0BAWm1JV3F8w0mhMOA {
tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw Field0;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field1;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ {
  TGenericSeq Sup;
  tyTuple_zXBGqNygOt4DlBCAX3NcVQ data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_g8wWagWtbBE4jkij9axgDjA {
  TGenericSeq Sup;
  tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* data[SEQ_DECL_SIZE];
};
struct tySequence_RGI7x8xRcqqyfGoCDX4zJQ {
  TGenericSeq Sup;
  tyTuple_mfj8s9cvmtjfv2tUmnpfuug data[SEQ_DECL_SIZE];
};
struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og {
  TGenericSeq Sup;
  tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tySequence_ABPSpAd6GJPBDOgnx8Xaeg {
  TGenericSeq Sup;
  tyTuple_CqK5avyg59bVH4ni9ajbhfNw data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_JAV0yhDlrNFYdAVDw2r39bQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_RGI7x8xRcqqyfGoCDX4zJQ)(void* p, NI op);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, initTable_k6FvvwLpfkLbR0qei5BTag)(NI initialSize, tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* Result);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__RMUgI4RQdgrAHzsY2uI0Gw)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* t, NimStringDesc* key, tyTuple_7lOBCx9cCrvEawWBqjuj8vQ val);
static N_INLINE(NI, rawGet_h4fHJNOOviCcBqEWaMO8Lwtables)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQinstructions)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_k79a5cVu68iMPfWR9cdJiazw)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_vU19bQ9b9bY9aEGcJdz9b80NlxQ)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* t, tySequence_RGI7x8xRcqqyfGoCDX4zJQ** data, NimStringDesc* key, tyTuple_7lOBCx9cCrvEawWBqjuj8vQ val, NI hc, NI h);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, rawGetKnownHC_8x9cMaj18Sd3hc9atnMJX8Xgtables)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg t, NimStringDesc* key, NI hc);
static N_INLINE(NI, rawGet_Tlk809aSTRCw229bbn1GoMawtables)(tyObject_Table_pntvPsgDJ7q7yAcWyvfffA t, NimStringDesc* key, NI* hc);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_NIMCALL(void, Marker_tySequence_pUxI6Ljo6IKKHXKOZkQ7Og)(void* p, NI op);
static N_INLINE(NI, rawGet_8tUiuCSSvEA5RC0dri5Zcwtables)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_7gDjc0voQOQhvldyHhB6sQ)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_MHVqM4kiYpFYPWDGMKC9b0A)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t, tySequence_JAV0yhDlrNFYdAVDw2r39bQ** data, NimStringDesc* key, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_Kz9bWl5T5j1XovUu9cpkZzgQtables)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw t, NimStringDesc* key, NI hc);
static N_INLINE(NI, rawGet_6W1ssjRyuKtSjII2c2v5RQtables)(tyObject_Table_zjMaDBasw1LnKbj11akpfw t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_NkEl9bLLrzlYTmLn9cgTZPyg)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_JrnDXRCjxItwEsaMlP5tEA)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t, tySequence_pUxI6Ljo6IKKHXKOZkQ7Og** data, NimStringDesc* key, NI val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_m6drWlVK9bHkmyhr05CjMNQtables)(tyObject_Table_zjMaDBasw1LnKbj11akpfw t, NimStringDesc* key, NI hc);
TNimType NTI_upT1OmA0PO9bbHjDDPVn2Uw_;
TNimType NTI_zXBGqNygOt4DlBCAX3NcVQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_9a9cRvMBGWDRFk9av9bTYiXvsg_;
TNimType NTI_JAV0yhDlrNFYdAVDw2r39bQ_;
TNimType NTI_9aV9cyUfSVEvrEHigJPwqVqg_;
TNimType NTI_mfj8s9cvmtjfv2tUmnpfuug_;
extern TNimType NTI_7lOBCx9cCrvEawWBqjuj8vQ_;
TNimType NTI_RGI7x8xRcqqyfGoCDX4zJQ_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_g8wWagWtbBE4jkij9axgDjA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_axqhRnwd09cVJkRcojfw6mA_;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg_;
TNimType NTI_zjMaDBasw1LnKbj11akpfw_;
TNimType NTI_sr3s7uVHpu9cEbbDnCSg8yQ_;
TNimType NTI_pUxI6Ljo6IKKHXKOZkQ7Og_;
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_6, "key not found: ", 15);
static N_NIMCALL(void, Marker_tySequence_JAV0yhDlrNFYdAVDw2r39bQ)(void* p, NI op) {
	tySequence_JAV0yhDlrNFYdAVDw2r39bQ* a;
	NI T1_;
	a = (tySequence_JAV0yhDlrNFYdAVDw2r39bQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}
static N_NIMCALL(void, Marker_tySequence_RGI7x8xRcqqyfGoCDX4zJQ)(void* p, NI op) {
	tySequence_RGI7x8xRcqqyfGoCDX4zJQ* a;
	NI T1_;
	a = (tySequence_RGI7x8xRcqqyfGoCDX4zJQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2.Field0, op);
	nimGCvisit((void*)a->data[T1_].Field2.Field1, op);
	}
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_k6FvvwLpfkLbR0qei5BTag)(NI initialSize, tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* Result) {
	genericReset((void*)Result, (&NTI_9aV9cyUfSVEvrEHigJPwqVqg_));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_RGI7x8xRcqqyfGoCDX4zJQ*) newSeq((&NTI_RGI7x8xRcqqyfGoCDX4zJQ_), ((NI) (initialSize))));
}

static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count) {
	NI result;
	result = (NI)0;
	result = nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA((NI)((NI)((NI)(((NI) (count)) * ((NI) 3)) / ((NI) 2)) + ((NI) 4)));
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQinstructions)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQinstructions(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)(h + ((NI) 1)) & maxHash);
	return result;
}

static N_INLINE(NI, rawGet_h4fHJNOOviCcBqEWaMO8Lwtables)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
{	result = (NI)0;
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = ((NI)(length * ((NI) 2)) < (NI)(counter * ((NI) 3)));
	if (T1_) goto LA2_;
	T1_ = ((NI)(length - counter) < ((NI) 4));
	LA2_: ;
	result = T1_;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_vU19bQ9b9bY9aEGcJdz9b80NlxQ)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* t, tySequence_RGI7x8xRcqqyfGoCDX4zJQ** data, NimStringDesc* key, tyTuple_7lOBCx9cCrvEawWBqjuj8vQ val, NI hc, NI h) {
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	genericSeqAssign((&(*data)->data[h].Field2.Field0), val.Field0, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	genericSeqAssign((&(*data)->data[h].Field2.Field1), val.Field1, (&NTI_g8wWagWtbBE4jkij9axgDjA_));
	(*data)->data[h].Field0 = hc;
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_k79a5cVu68iMPfWR9cdJiazw)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* t) {
	tySequence_RGI7x8xRcqqyfGoCDX4zJQ* n;
	NI T1_;
	tySequence_RGI7x8xRcqqyfGoCDX4zJQ* T2_;
	n = (tySequence_RGI7x8xRcqqyfGoCDX4zJQ*)0;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence_RGI7x8xRcqqyfGoCDX4zJQ*) newSeq((&NTI_RGI7x8xRcqqyfGoCDX4zJQ_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	T2_ = (tySequence_RGI7x8xRcqqyfGoCDX4zJQ*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				eh = n->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(eh);
					if (!T9_) goto LA10_;
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					rawInsert_vU19bQ9b9bY9aEGcJdz9b80NlxQ(t, (&(*t).data), n->data[i].Field1, n->data[i].Field2, eh, j);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
}

static N_INLINE(NI, rawGetKnownHC_8x9cMaj18Sd3hc9atnMJX8Xgtables)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
{	result = (NI)0;
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__RMUgI4RQdgrAHzsY2uI0Gw)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* t, NimStringDesc* key, tyTuple_7lOBCx9cCrvEawWBqjuj8vQ val) {
	NI hc;
	NI index;
	hc = (NI)0;
	index = rawGet_h4fHJNOOviCcBqEWaMO8Lwtables((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		genericSeqAssign((&(*t).data->data[index].Field2.Field0), val.Field0, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
		genericSeqAssign((&(*t).data->data[index].Field2.Field1), val.Field1, (&NTI_g8wWagWtbBE4jkij9axgDjA_));
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI T8_;
			NIM_BOOL T9_;
			T8_ = ((*t).data ? (*t).data->Sup.len : 0);
			T9_ = (NIM_BOOL)0;
			T9_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T8_, (*t).counter);
			if (!T9_) goto LA10_;
			enlarge_k79a5cVu68iMPfWR9cdJiazw(t);
			index = rawGetKnownHC_8x9cMaj18Sd3hc9atnMJX8Xgtables((*t), key, hc);
		}
		LA10_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert_vU19bQ9b9bY9aEGcJdz9b80NlxQ(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, toTable_7LYUurmrFBFgKXxLkOoxXQ)(tyTuple_Tm9b70UjZRu9bcRFBg8QfgkA* pairs, NI pairsLen_0, tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg* Result) {
	NI T1_;
	genericReset((void*)Result, (&NTI_9aV9cyUfSVEvrEHigJPwqVqg_));
	T1_ = (NI)0;
	T1_ = rightSize_l3wfAVpWNBWtzL8kQfvMMAtables(((NI) (pairsLen_0)));
	initTable_k6FvvwLpfkLbR0qei5BTag(T1_, Result);
	{
		NimStringDesc* key;
		tyTuple_7lOBCx9cCrvEawWBqjuj8vQ val;
		NI i;
		key = (NimStringDesc*)0;
		memset((void*)(&val), 0, sizeof(val));
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < pairsLen_0)) goto LA4;
				key = pairs[i].Field0;
				val.Field0 = pairs[i].Field1.Field0;
				val.Field1 = pairs[i].Field1.Field1;
				X5BX5Deq__RMUgI4RQdgrAHzsY2uI0Gw(Result, key, val);
				i += ((NI) 1);
			} LA4: ;
		}
	}
}

static N_INLINE(NI, rawGet_Tlk809aSTRCw229bbn1GoMawtables)(tyObject_Table_pntvPsgDJ7q7yAcWyvfffA t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
{	result = (NI)0;
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_4ygQFmCO3DZsQWcbRPxovg)(tyObject_Table_pntvPsgDJ7q7yAcWyvfffA t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet_Tlk809aSTRCw229bbn1GoMawtables(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A, X5BX5D__AMJfbib2i6SfJzvstSdk9ag)(tyObject_Table_pntvPsgDJ7q7yAcWyvfffA t, NimStringDesc* key) {
	tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A result;
	NI hc;
	NI index;
	result = (tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A)0;
	hc = (NI)0;
	index = rawGet_Tlk809aSTRCw229bbn1GoMawtables(t, key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		result = t.data->data[index].Field2;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		T6_ = (NimStringDesc*)0;
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_6));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_pUxI6Ljo6IKKHXKOZkQ7Og)(void* p, NI op) {
	tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* a;
	NI T1_;
	a = (tySequence_pUxI6Ljo6IKKHXKOZkQ7Og*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_ldxARpi0QpxbGWU5LVgSZQ)(NI initialSize, tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* Result) {
	genericReset((void*)Result, (&NTI_upT1OmA0PO9bbHjDDPVn2Uw_));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_JAV0yhDlrNFYdAVDw2r39bQ*) newSeq((&NTI_JAV0yhDlrNFYdAVDw2r39bQ_), ((NI) (initialSize))));
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_3Cf7Fyn7tUxJRodC9aUxtFw)(NI initialSize, tyObject_Table_zjMaDBasw1LnKbj11akpfw* Result) {
	genericReset((void*)Result, (&NTI_zjMaDBasw1LnKbj11akpfw_));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_pUxI6Ljo6IKKHXKOZkQ7Og*) newSeq((&NTI_pUxI6Ljo6IKKHXKOZkQ7Og_), ((NI) (initialSize))));
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5D__9cTh0NZIzKMVpNtO46NirYg)(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg t, NimStringDesc* key, tyTuple_7lOBCx9cCrvEawWBqjuj8vQ* Result) {
	NI hc;
	NI index;
	genericReset((void*)Result, (&NTI_7lOBCx9cCrvEawWBqjuj8vQ_));
	hc = (NI)0;
	index = rawGet_h4fHJNOOviCcBqEWaMO8Lwtables(t, key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		genericSeqAssign((&(*Result).Field0), t.data->data[index].Field2.Field0, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
		genericSeqAssign((&(*Result).Field1), t.data->data[index].Field2.Field1, (&NTI_g8wWagWtbBE4jkij9axgDjA_));
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		T6_ = (NimStringDesc*)0;
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_6));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
}

static N_INLINE(NI, rawGet_8tUiuCSSvEA5RC0dri5Zcwtables)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
{	result = (NI)0;
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_MHVqM4kiYpFYPWDGMKC9b0A)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t, tySequence_JAV0yhDlrNFYdAVDw2r39bQ** data, NimStringDesc* key, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* val, NI hc, NI h) {
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRef((void**) (&(*data)->data[h].Field2), val);
	(*data)->data[h].Field0 = hc;
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_7gDjc0voQOQhvldyHhB6sQ)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t) {
	tySequence_JAV0yhDlrNFYdAVDw2r39bQ* n;
	NI T1_;
	tySequence_JAV0yhDlrNFYdAVDw2r39bQ* T2_;
	n = (tySequence_JAV0yhDlrNFYdAVDw2r39bQ*)0;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence_JAV0yhDlrNFYdAVDw2r39bQ*) newSeq((&NTI_JAV0yhDlrNFYdAVDw2r39bQ_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	T2_ = (tySequence_JAV0yhDlrNFYdAVDw2r39bQ*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				eh = n->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(eh);
					if (!T9_) goto LA10_;
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					rawInsert_MHVqM4kiYpFYPWDGMKC9b0A(t, (&(*t).data), n->data[i].Field1, n->data[i].Field2, eh, j);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
}

static N_INLINE(NI, rawGetKnownHC_Kz9bWl5T5j1XovUu9cpkZzgQtables)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
{	result = (NI)0;
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__HW88TTiOGEbkbPlPS00naA)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t, NimStringDesc* key, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* val) {
	NI hc;
	NI index;
	hc = (NI)0;
	index = rawGet_8tUiuCSSvEA5RC0dri5Zcwtables((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		asgnRef((void**) (&(*t).data->data[index].Field2), val);
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI T8_;
			NIM_BOOL T9_;
			T8_ = ((*t).data ? (*t).data->Sup.len : 0);
			T9_ = (NIM_BOOL)0;
			T9_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T8_, (*t).counter);
			if (!T9_) goto LA10_;
			enlarge_7gDjc0voQOQhvldyHhB6sQ(t);
			index = rawGetKnownHC_Kz9bWl5T5j1XovUu9cpkZzgQtables((*t), key, hc);
		}
		LA10_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert_MHVqM4kiYpFYPWDGMKC9b0A(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA1_: ;
}

static N_INLINE(NI, rawGet_6W1ssjRyuKtSjII2c2v5RQtables)(tyObject_Table_zjMaDBasw1LnKbj11akpfw t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
{	result = (NI)0;
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_JrnDXRCjxItwEsaMlP5tEA)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t, tySequence_pUxI6Ljo6IKKHXKOZkQ7Og** data, NimStringDesc* key, NI val, NI hc, NI h) {
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	(*data)->data[h].Field2 = val;
	(*data)->data[h].Field0 = hc;
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_NkEl9bLLrzlYTmLn9cgTZPyg)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t) {
	tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* n;
	NI T1_;
	tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* T2_;
	n = (tySequence_pUxI6Ljo6IKKHXKOZkQ7Og*)0;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence_pUxI6Ljo6IKKHXKOZkQ7Og*) newSeq((&NTI_pUxI6Ljo6IKKHXKOZkQ7Og_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	T2_ = (tySequence_pUxI6Ljo6IKKHXKOZkQ7Og*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				eh = n->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(eh);
					if (!T9_) goto LA10_;
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					rawInsert_JrnDXRCjxItwEsaMlP5tEA(t, (&(*t).data), n->data[i].Field1, n->data[i].Field2, eh, j);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
}

static N_INLINE(NI, rawGetKnownHC_m6drWlVK9bHkmyhr05CjMNQtables)(tyObject_Table_zjMaDBasw1LnKbj11akpfw t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
{	result = (NI)0;
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__ElMq9artIyfSkc1PsoGBTww)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t, NimStringDesc* key, NI val) {
	NI hc;
	NI index;
	hc = (NI)0;
	index = rawGet_6W1ssjRyuKtSjII2c2v5RQtables((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		(*t).data->data[index].Field2 = val;
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI T8_;
			NIM_BOOL T9_;
			T8_ = ((*t).data ? (*t).data->Sup.len : 0);
			T9_ = (NIM_BOOL)0;
			T9_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T8_, (*t).counter);
			if (!T9_) goto LA10_;
			enlarge_NkEl9bLLrzlYTmLn9cgTZPyg(t);
			index = rawGetKnownHC_m6drWlVK9bHkmyhr05CjMNQtables((*t), key, hc);
		}
		LA10_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert_JrnDXRCjxItwEsaMlP5tEA(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA1_: ;
}

N_LIB_PRIVATE N_NIMCALL(NI*, X5BX5D__0psyqwBtEfcfpLgnMt8iYQ)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t, NimStringDesc* key) {
	NI* result;
	NI hc;
	NI index;
	result = (NI*)0;
	hc = (NI)0;
	index = rawGet_6W1ssjRyuKtSjII2c2v5RQtables((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		result = (&(*t).data->data[index].Field2);
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		T6_ = (NimStringDesc*)0;
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_6));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_eVs19ak9bLDMU8DCGg32t3aQ)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet_8tUiuCSSvEA5RC0dri5Zcwtables(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw**, X5BX5D__BTFIz0ITK8bF3RR5rKqcDg)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t, NimStringDesc* key) {
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw** result;
	NI hc;
	NI index;
	result = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw**)0;
	hc = (NI)0;
	index = rawGet_8tUiuCSSvEA5RC0dri5Zcwtables((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		result = &(*t).data->data[index].Field2;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		T6_ = (NimStringDesc*)0;
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_6));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_2[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_3[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_4[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_5[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_7[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_8[3];
static TNimNode TM_4SoG2KRQy3oMm9aUzSLtGrA_0[21];
NTI_upT1OmA0PO9bbHjDDPVn2Uw_.size = sizeof(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw);
NTI_upT1OmA0PO9bbHjDDPVn2Uw_.kind = 18;
NTI_upT1OmA0PO9bbHjDDPVn2Uw_.base = 0;
TM_4SoG2KRQy3oMm9aUzSLtGrA_2[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1];
NTI_zXBGqNygOt4DlBCAX3NcVQ_.size = sizeof(tyTuple_zXBGqNygOt4DlBCAX3NcVQ);
NTI_zXBGqNygOt4DlBCAX3NcVQ_.kind = 18;
NTI_zXBGqNygOt4DlBCAX3NcVQ_.base = 0;
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].offset = offsetof(tyTuple_zXBGqNygOt4DlBCAX3NcVQ, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].offset = offsetof(tyTuple_zXBGqNygOt4DlBCAX3NcVQ, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_3[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].offset = offsetof(tyTuple_zXBGqNygOt4DlBCAX3NcVQ, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].typ = (&NTI_9a9cRvMBGWDRFk9av9bTYiXvsg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_3[0];
NTI_zXBGqNygOt4DlBCAX3NcVQ_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2];
NTI_JAV0yhDlrNFYdAVDw2r39bQ_.size = sizeof(tySequence_JAV0yhDlrNFYdAVDw2r39bQ*);
NTI_JAV0yhDlrNFYdAVDw2r39bQ_.kind = 24;
NTI_JAV0yhDlrNFYdAVDw2r39bQ_.base = (&NTI_zXBGqNygOt4DlBCAX3NcVQ_);
NTI_JAV0yhDlrNFYdAVDw2r39bQ_.marker = Marker_tySequence_JAV0yhDlrNFYdAVDw2r39bQ;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].offset = offsetof(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].typ = (&NTI_JAV0yhDlrNFYdAVDw2r39bQ_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_2[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].offset = offsetof(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_2[0];
NTI_upT1OmA0PO9bbHjDDPVn2Uw_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0];
NTI_9aV9cyUfSVEvrEHigJPwqVqg_.size = sizeof(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg);
NTI_9aV9cyUfSVEvrEHigJPwqVqg_.kind = 18;
NTI_9aV9cyUfSVEvrEHigJPwqVqg_.base = 0;
TM_4SoG2KRQy3oMm9aUzSLtGrA_4[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8];
NTI_mfj8s9cvmtjfv2tUmnpfuug_.size = sizeof(tyTuple_mfj8s9cvmtjfv2tUmnpfuug);
NTI_mfj8s9cvmtjfv2tUmnpfuug_.kind = 18;
NTI_mfj8s9cvmtjfv2tUmnpfuug_.base = 0;
TM_4SoG2KRQy3oMm9aUzSLtGrA_5[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].offset = offsetof(tyTuple_mfj8s9cvmtjfv2tUmnpfuug, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_5[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].offset = offsetof(tyTuple_mfj8s9cvmtjfv2tUmnpfuug, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_5[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].offset = offsetof(tyTuple_mfj8s9cvmtjfv2tUmnpfuug, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].typ = (&NTI_7lOBCx9cCrvEawWBqjuj8vQ_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_5[0];
NTI_mfj8s9cvmtjfv2tUmnpfuug_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9];
NTI_RGI7x8xRcqqyfGoCDX4zJQ_.size = sizeof(tySequence_RGI7x8xRcqqyfGoCDX4zJQ*);
NTI_RGI7x8xRcqqyfGoCDX4zJQ_.kind = 24;
NTI_RGI7x8xRcqqyfGoCDX4zJQ_.base = (&NTI_mfj8s9cvmtjfv2tUmnpfuug_);
NTI_RGI7x8xRcqqyfGoCDX4zJQ_.marker = Marker_tySequence_RGI7x8xRcqqyfGoCDX4zJQ;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].offset = offsetof(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].typ = (&NTI_RGI7x8xRcqqyfGoCDX4zJQ_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_4[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].offset = offsetof(tyObject_Table_9aV9cyUfSVEvrEHigJPwqVqg, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_4[0];
NTI_9aV9cyUfSVEvrEHigJPwqVqg_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7];
NTI_zjMaDBasw1LnKbj11akpfw_.size = sizeof(tyObject_Table_zjMaDBasw1LnKbj11akpfw);
NTI_zjMaDBasw1LnKbj11akpfw_.kind = 18;
NTI_zjMaDBasw1LnKbj11akpfw_.base = 0;
NTI_zjMaDBasw1LnKbj11akpfw_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_7[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15];
NTI_sr3s7uVHpu9cEbbDnCSg8yQ_.size = sizeof(tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ);
NTI_sr3s7uVHpu9cEbbDnCSg8yQ_.kind = 18;
NTI_sr3s7uVHpu9cEbbDnCSg8yQ_.base = 0;
NTI_sr3s7uVHpu9cEbbDnCSg8yQ_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_8[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].offset = offsetof(tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_8[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].offset = offsetof(tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_8[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].offset = offsetof(tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_8[0];
NTI_sr3s7uVHpu9cEbbDnCSg8yQ_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16];
NTI_pUxI6Ljo6IKKHXKOZkQ7Og_.size = sizeof(tySequence_pUxI6Ljo6IKKHXKOZkQ7Og*);
NTI_pUxI6Ljo6IKKHXKOZkQ7Og_.kind = 24;
NTI_pUxI6Ljo6IKKHXKOZkQ7Og_.base = (&NTI_sr3s7uVHpu9cEbbDnCSg8yQ_);
NTI_pUxI6Ljo6IKKHXKOZkQ7Og_.flags = 2;
NTI_pUxI6Ljo6IKKHXKOZkQ7Og_.marker = Marker_tySequence_pUxI6Ljo6IKKHXKOZkQ7Og;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].offset = offsetof(tyObject_Table_zjMaDBasw1LnKbj11akpfw, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].typ = (&NTI_pUxI6Ljo6IKKHXKOZkQ7Og_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_7[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].offset = offsetof(tyObject_Table_zjMaDBasw1LnKbj11akpfw, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_7[0];
NTI_zjMaDBasw1LnKbj11akpfw_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14];
}

