/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/erik/.choosenim/toolchains/nim-0.18.0/lib -o /home/erik/Code/TFG/void/NimVoid/src/nimcache/tokens.o /home/erik/Code/TFG/void/NimVoid/src/nimcache/tokens.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_KWcIY9c1klZQizoiQC0yHOg tyTuple_KWcIY9c1klZQizoiQC0yHOg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_KWcIY9c1klZQizoiQC0yHOg {
tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A Field0;
NI Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
TNimType NTI_KWcIY9c1klZQizoiQC0yHOg_;
TNimType NTI_GfUVZb1p7fCHLBrHZDvq7A_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;

N_LIB_PRIVATE N_NIMCALL(void, newToken_CxEPRFYDeVoM1n45VSW9bqQ)(tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A kind, NI line, NimStringDesc* lexeme, NimStringDesc* value, tyTuple_KWcIY9c1klZQizoiQC0yHOg* Result) {
	genericReset((void*)Result, (&NTI_KWcIY9c1klZQizoiQC0yHOg_));
	(*Result).Field0 = kind;
	(*Result).Field1 = line;
	unsureAsgnRef((void**) (&(*Result).Field2), copyString(lexeme));
	unsureAsgnRef((void**) (&(*Result).Field3), copyString(value));
}
NIM_EXTERNC N_NOINLINE(void, unknown_tokensInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_tokensDatInit000)(void) {
static TNimNode* TM_xDlB0WHPxJhXV9ckv5nm5Og_2[4];
static TNimNode* TM_xDlB0WHPxJhXV9ckv5nm5Og_3[40];
NI TM_xDlB0WHPxJhXV9ckv5nm5Og_5;
static char* NIM_CONST TM_xDlB0WHPxJhXV9ckv5nm5Og_4[40] = {
"TOK_PLUS", 
"TOK_MINUS", 
"TOK_STAR", 
"TOK_SLASH", 
"TOK_PERCENT", 
"TOK_LEFT_PAREN", 
"TOK_RIGHT_PAREN", 
"TOK_LEFT_SPAREN", 
"TOK_RIGHT_SPAREN", 
"TOK_LEFT_BRACE", 
"TOK_RIGHT_BRACE", 
"TOK_COMMA", 
"TOK_DOT", 
"TOK_COLON", 
"TOK_SEMICOLON", 
"TOK_EQUAL", 
"TOK_EQUAL_EQUAL", 
"TOK_BANG", 
"TOK_BANG_EQUAL", 
"TOK_GREATER", 
"TOK_GREATER_EQUAL", 
"TOK_LESS", 
"TOK_LESS_EQUAL", 
"TOK_SIMPLE_ARROW", 
"TOK_ARROW", 
"TOK_IDENTIFIER", 
"TOK_STRING", 
"TOK_NUMBER", 
"TOK_AND", 
"TOK_OR", 
"TOK_TRUE", 
"TOK_FALSE", 
"TOK_IF", 
"TOK_ELSE", 
"TOK_NONE", 
"TOK_RETURN", 
"TOK_FOR", 
"TOK_WHILE", 
"TOK_PRINT", 
"TOK_EOF"};
static TNimNode TM_xDlB0WHPxJhXV9ckv5nm5Og_0[46];
NTI_KWcIY9c1klZQizoiQC0yHOg_.size = sizeof(tyTuple_KWcIY9c1klZQizoiQC0yHOg);
NTI_KWcIY9c1klZQizoiQC0yHOg_.kind = 18;
NTI_KWcIY9c1klZQizoiQC0yHOg_.base = 0;
NTI_KWcIY9c1klZQizoiQC0yHOg_.flags = 2;
TM_xDlB0WHPxJhXV9ckv5nm5Og_2[0] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[1];
NTI_GfUVZb1p7fCHLBrHZDvq7A_.size = sizeof(tyEnum_Kinds_GfUVZb1p7fCHLBrHZDvq7A);
NTI_GfUVZb1p7fCHLBrHZDvq7A_.kind = 14;
NTI_GfUVZb1p7fCHLBrHZDvq7A_.base = 0;
NTI_GfUVZb1p7fCHLBrHZDvq7A_.flags = 3;
for (TM_xDlB0WHPxJhXV9ckv5nm5Og_5 = 0; TM_xDlB0WHPxJhXV9ckv5nm5Og_5 < 40; TM_xDlB0WHPxJhXV9ckv5nm5Og_5++) {
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[TM_xDlB0WHPxJhXV9ckv5nm5Og_5+2].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[TM_xDlB0WHPxJhXV9ckv5nm5Og_5+2].offset = TM_xDlB0WHPxJhXV9ckv5nm5Og_5;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[TM_xDlB0WHPxJhXV9ckv5nm5Og_5+2].name = TM_xDlB0WHPxJhXV9ckv5nm5Og_4[TM_xDlB0WHPxJhXV9ckv5nm5Og_5];
TM_xDlB0WHPxJhXV9ckv5nm5Og_3[TM_xDlB0WHPxJhXV9ckv5nm5Og_5] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[TM_xDlB0WHPxJhXV9ckv5nm5Og_5+2];
}
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42].len = 40; TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42].kind = 2; TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42].sons = &TM_xDlB0WHPxJhXV9ckv5nm5Og_3[0];
NTI_GfUVZb1p7fCHLBrHZDvq7A_.node = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42];
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[1].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[1].offset = offsetof(tyTuple_KWcIY9c1klZQizoiQC0yHOg, Field0);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[1].typ = (&NTI_GfUVZb1p7fCHLBrHZDvq7A_);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[1].name = "Field0";
TM_xDlB0WHPxJhXV9ckv5nm5Og_2[1] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43];
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43].offset = offsetof(tyTuple_KWcIY9c1klZQizoiQC0yHOg, Field1);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43].name = "Field1";
TM_xDlB0WHPxJhXV9ckv5nm5Og_2[2] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[44];
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[44].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[44].offset = offsetof(tyTuple_KWcIY9c1klZQizoiQC0yHOg, Field2);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[44].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[44].name = "Field2";
TM_xDlB0WHPxJhXV9ckv5nm5Og_2[3] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[45];
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[45].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[45].offset = offsetof(tyTuple_KWcIY9c1klZQizoiQC0yHOg, Field3);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[45].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[45].name = "Field3";
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[0].len = 4; TM_xDlB0WHPxJhXV9ckv5nm5Og_0[0].kind = 2; TM_xDlB0WHPxJhXV9ckv5nm5Og_0[0].sons = &TM_xDlB0WHPxJhXV9ckv5nm5Og_2[0];
NTI_KWcIY9c1klZQizoiQC0yHOg_.node = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[0];
}

