/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/erik/.choosenim/toolchains/nim-0.18.0/lib -o /home/erik/Code/TFG/void/NimVoid/src/nimcache/vm.o /home/erik/Code/TFG/void/NimVoid/src/nimcache/vm.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_M3y5mHl2OtcVFI81N2j0DQ tyTuple_M3y5mHl2OtcVFI81N2j0DQ;
typedef struct tySequence_g8wWagWtbBE4jkij9axgDjA tySequence_g8wWagWtbBE4jkij9axgDjA;
typedef struct tyTuple_p7Uw0BAWm1JV3F8w0mhMOA tyTuple_p7Uw0BAWm1JV3F8w0mhMOA;
typedef struct tySequence_49cSLhOXtIXPXzKKaGFU0eQ tySequence_49cSLhOXtIXPXzKKaGFU0eQ;
typedef struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw;
typedef struct tySequence_rl1wTgiGRBZamH1pllm1bA tySequence_rl1wTgiGRBZamH1pllm1bA;
typedef struct tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg;
typedef struct tyObject_Table_zjMaDBasw1LnKbj11akpfw tyObject_Table_zjMaDBasw1LnKbj11akpfw;
typedef struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og tySequence_pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw;
typedef struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ tySequence_JAV0yhDlrNFYdAVDw2r39bQ;
typedef struct tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA;
typedef struct RootObj RootObj;
typedef struct tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ;
typedef struct tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA;
typedef struct tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ;
typedef struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ tyTuple_zXBGqNygOt4DlBCAX3NcVQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table_zjMaDBasw1LnKbj11akpfw {
tySequence_pUxI6Ljo6IKKHXKOZkQ7Og* data;
NI counter;
};
struct tyTuple_M3y5mHl2OtcVFI81N2j0DQ {
tySequence_g8wWagWtbBE4jkij9axgDjA* Field0;
tySequence_49cSLhOXtIXPXzKKaGFU0eQ* Field1;
tySequence_rl1wTgiGRBZamH1pllm1bA* Field2;
tyObject_Table_zjMaDBasw1LnKbj11akpfw Field3;
NI Field4;
NI Field5;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw {
tySequence_JAV0yhDlrNFYdAVDw2r39bQ* data;
NI counter;
};
typedef NU8 tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw;
struct tyTuple_p7Uw0BAWm1JV3F8w0mhMOA {
tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw Field0;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field1;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw {
  RootObj Sup;
};
struct tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NF value;
};
struct tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NimStringDesc* value;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg {
tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw Field0;
NI Field1;
};
struct tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
NI arguments;
tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* frame;
NimStringDesc* label;
};
struct tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ {
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw Sup;
tySequence_49cSLhOXtIXPXzKKaGFU0eQ* values;
};
struct tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringDesc* Field1;
NI Field2;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_zXBGqNygOt4DlBCAX3NcVQ {
NI Field0;
NimStringDesc* Field1;
tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* Field2;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_g8wWagWtbBE4jkij9axgDjA {
  TGenericSeq Sup;
  tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* data[SEQ_DECL_SIZE];
};
struct tySequence_49cSLhOXtIXPXzKKaGFU0eQ {
  TGenericSeq Sup;
  tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* data[SEQ_DECL_SIZE];
};
struct tySequence_rl1wTgiGRBZamH1pllm1bA {
  TGenericSeq Sup;
  tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* data[SEQ_DECL_SIZE];
};
struct tySequence_pUxI6Ljo6IKKHXKOZkQ7Og {
  TGenericSeq Sup;
  tyTuple_sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tySequence_JAV0yhDlrNFYdAVDw2r39bQ {
  TGenericSeq Sup;
  tyTuple_zXBGqNygOt4DlBCAX3NcVQ data[SEQ_DECL_SIZE];
};
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_49cSLhOXtIXPXzKKaGFU0eQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_rl1wTgiGRBZamH1pllm1bA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_ORWQUtasKGvy7C2tIe1dcg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(void, nimGCunrefRC1)(void* p);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*, newFrame_nfe2NsS0Jn8q3iozdCF9c8g)(NI return_address, tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw heap);
N_LIB_PRIVATE N_NIMCALL(void, initTable_ldxARpi0QpxbGWU5LVgSZQ)(NI initialSize, tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* Result);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, initTable_3Cf7Fyn7tUxJRodC9aUxtFw)(NI initialSize, tyObject_Table_zjMaDBasw1LnKbj11akpfw* Result);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__ElMq9artIyfSkc1PsoGBTww)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t, NimStringDesc* key, NI val);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__7fo3EMB4ZHVOeNHdcmvmHw)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value);
N_LIB_PRIVATE N_NIMCALL(NI*, X5BX5D__0psyqwBtEfcfpLgnMt8iYQ)(tyObject_Table_zjMaDBasw1LnKbj11akpfw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*, peek_SVMMhbcmdU9bbGmU4y3y9cPA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, pop_sriDR80u76aqeJV4KxrLyQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, delete_xVzaGyEHLmq9cWAIfcmhv9ag)(tySequence_49cSLhOXtIXPXzKKaGFU0eQ** x, NI i);
N_LIB_PRIVATE N_NIMCALL(void, push_42VJRI9baGwvzSPeFvwV0PQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*, advance_SVMMhbcmdU9bbGmU4y3y9cPA_2)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, negInst_xyQWTytrhLP5sNYraZHgWA)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, notInst_xyQWTytrhLP5sNYraZHgWA_2)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, orInst_tkSI5SBXwZSvZ7e09bMVKnQ)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, andInst_tkSI5SBXwZSvZ7e09bMVKnQ_2)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, addInst_tkSI5SBXwZSvZ7e09bMVKnQ_3)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, subInst_tkSI5SBXwZSvZ7e09bMVKnQ_4)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, mulInst_tkSI5SBXwZSvZ7e09bMVKnQ_5)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, divInst_tkSI5SBXwZSvZ7e09bMVKnQ_6)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, modInst_tkSI5SBXwZSvZ7e09bMVKnQ_7)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, eqInst_tkSI5SBXwZSvZ7e09bMVKnQ_8)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, neqInst_tkSI5SBXwZSvZ7e09bMVKnQ_9)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, gtInst_tkSI5SBXwZSvZ7e09bMVKnQ_10)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, gteInst_tkSI5SBXwZSvZ7e09bMVKnQ_11)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, ltInst_tkSI5SBXwZSvZ7e09bMVKnQ_12)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, lteInst_tkSI5SBXwZSvZ7e09bMVKnQ_13)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b);
N_LIB_PRIVATE N_NIMCALL(void, labelJump_oQz7PD9cSeqOkaoRqQj9b1OA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* i);
N_LIB_PRIVATE N_NIMCALL(void, jump_oQz7PD9cSeqOkaoRqQj9b1OA_2)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* i);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, funInst_q277MmzO36qhOVSX572bog)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* startLabel, tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* frame, NI arguments);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__HW88TTiOGEbkbPlPS00naA)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t, NimStringDesc* key, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* val);
N_LIB_PRIVATE N_NIMCALL(void, labelJump_81L7T6SAy1i3aSNYuCvUig)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* i);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, branchtInst_Ta7UGXfYpipiP2t82lLQyg)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, branchfInst_Ta7UGXfYpipiP2t82lLQyg_2)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQinstructions)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_eVs19ak9bLDMU8DCGg32t3aQ)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw**, X5BX5D__BTFIz0ITK8bF3RR5rKqcDg)(tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, delete_ZcgKNNy8O3y2vsPS1KBnvA)(tySequence_rl1wTgiGRBZamH1pllm1bA** x, NI i);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwvm)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, accessInst_W9abjXu3cyh9c9bRLmF7ZdZkA)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* i);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, lenInst_xyQWTytrhLP5sNYraZHgWA_3)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, pushListInst_cO9cPN0psHDTy8Oz9bxU5oyg)(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* list, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
TNimType NTI_M3y5mHl2OtcVFI81N2j0DQ_;
extern TNimType NTI_g8wWagWtbBE4jkij9axgDjA_;
extern TNimType NTI_9a9cRvMBGWDRFk9av9bTYiXvsg_;
TNimType NTI_49cSLhOXtIXPXzKKaGFU0eQ_;
extern TNimType NTI_ZJnTpp110EyOkSiqN7Yliw_;
TNimType NTI_rl1wTgiGRBZamH1pllm1bA_;
extern TNimType NTI_zjMaDBasw1LnKbj11akpfw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_ORWQUtasKGvy7C2tIe1dcg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_gOxHjz9bS5yarbZPfCpiI9ag_;
extern TNimType NTI_560SkOiRWWBbF6rm9aw64dA_;
extern TNimType NTI_mW8phZov9cHZwUtCe8U2gZw_;
extern TNimType NTI_noD08ztngGqjHZ7t6Rl9aiQ_;
static TNimType* Nim_OfCheck_CACHE14[2];
static TNimType* Nim_OfCheck_CACHE15[2];
extern TNimType NTI_wzzqsNRSFKQWlUMuy1TJiw_;
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_2, "*_", 2);
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_5, "Empty stack, can\'t pop", 22);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_RKHCVF7xUfBueKXFrGJGRA_4 = {((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_5)}
;
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_6, "f", 1);
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_7, "The function requires ", 22);
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_8, " arguments. You provided ", 25);
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_9, ".", 1);
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_11, "The \'f\' variable name is reserved to function self-reference at"
" the moment.", 75);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_RKHCVF7xUfBueKXFrGJGRA_10 = {((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_11)}
;
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_12, "Undefined variable ", 19);
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_15, " is out of index", 16);
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_17, "Unknown combination of variable and index", 41);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_RKHCVF7xUfBueKXFrGJGRA_16 = {((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_17)}
;
STRING_LITERAL(TM_RKHCVF7xUfBueKXFrGJGRA_18, "Unknown operation ", 18);

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, tempLabel_4BbOJaErQoxvC9cm3k9cGHvA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	result = (NimStringDesc*)0;
	(*vm).Field5 += ((NI) 1);
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr((NI)((*vm).Field5 - ((NI) 1)));
	T1_ = rawNewString(T2_->Sup.len + 2);
appendString(T1_, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_2));
appendString(T1_, T2_);
	result = T1_;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_49cSLhOXtIXPXzKKaGFU0eQ)(void* p, NI op) {
	tySequence_49cSLhOXtIXPXzKKaGFU0eQ* a;
	NI T1_;
	a = (tySequence_49cSLhOXtIXPXzKKaGFU0eQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tySequence_rl1wTgiGRBZamH1pllm1bA)(void* p, NI op) {
	tySequence_rl1wTgiGRBZamH1pllm1bA* a;
	NI T1_;
	a = (tySequence_rl1wTgiGRBZamH1pllm1bA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef_ORWQUtasKGvy7C2tIe1dcg)(void* p, NI op) {
	tyTuple_M3y5mHl2OtcVFI81N2j0DQ* a;
	a = (tyTuple_M3y5mHl2OtcVFI81N2j0DQ*)p;
	nimGCvisit((void*)(*a).Field0, op);
	nimGCvisit((void*)(*a).Field1, op);
	nimGCvisit((void*)(*a).Field2, op);
	nimGCvisit((void*)(*a).Field3.data, op);
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_M3y5mHl2OtcVFI81N2j0DQ*, newVM_edzPHV9aEP9c1HS9bSsGnwsCw)(tySequence_g8wWagWtbBE4jkij9axgDjA* program) {
	tyTuple_M3y5mHl2OtcVFI81N2j0DQ* result;
	tyObject_Table_upT1OmA0PO9bbHjDDPVn2Uw T1_;
	result = (tyTuple_M3y5mHl2OtcVFI81N2j0DQ*)0;
	result = (tyTuple_M3y5mHl2OtcVFI81N2j0DQ*) newObj((&NTI_ORWQUtasKGvy7C2tIe1dcg_), sizeof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ));
	genericSeqAssign((&(*result).Field0), program, (&NTI_g8wWagWtbBE4jkij9axgDjA_));
	if ((*result).Field1) { nimGCunrefRC1((*result).Field1); (*result).Field1 = NIM_NIL; }
	(*result).Field1 = (tySequence_49cSLhOXtIXPXzKKaGFU0eQ*) newSeqRC1((&NTI_49cSLhOXtIXPXzKKaGFU0eQ_), 0);
	(*result).Field4 = ((NI) -1);
	(*result).Field5 = ((NI) 0);
	if ((*result).Field2) { nimGCunrefRC1((*result).Field2); (*result).Field2 = NIM_NIL; }
	(*result).Field2 = (tySequence_rl1wTgiGRBZamH1pllm1bA*) newSeqRC1((&NTI_rl1wTgiGRBZamH1pllm1bA_), 1);
	memset((void*)(&T1_), 0, sizeof(T1_));
	initTable_ldxARpi0QpxbGWU5LVgSZQ(((NI) 64), (&T1_));
	asgnRef((void**) (&(*result).Field2->data[0]), newFrame_nfe2NsS0Jn8q3iozdCF9c8g(((NI) 0), T1_));
	initTable_3Cf7Fyn7tUxJRodC9aUxtFw(((NI) 64), (&(*result).Field3));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, findLabels_9bi8b66OvH1yopTHTPHnt6Q)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm) {
	{
		NI i;
		tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* e;
		tySequence_g8wWagWtbBE4jkij9axgDjA* colontmp_;
		NI i_2;
		i = (NI)0;
		e = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
		colontmp_ = (tySequence_g8wWagWtbBE4jkij9axgDjA*)0;
		colontmp_ = (*vm).Field0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI T4_;
				T4_ = (colontmp_ ? colontmp_->Sup.len : 0);
				if (!(i_2 < T4_)) goto LA3;
				i = i_2;
				e = colontmp_->data[i_2];
				{
					NimStringDesc* T9_;
					if (!((*e).Field0 == ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4))) goto LA7_;
					T9_ = (NimStringDesc*)0;
					T9_ = dollar__7fo3EMB4ZHVOeNHdcmvmHw((*e).Field1);
					X5BX5Deq__ElMq9artIyfSkc1PsoGBTww((&(*vm).Field3), T9_, i);
				}
				LA7_: ;
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_LIB_PRIVATE N_NIMCALL(void, replaceLabelJumps_MUXxx2FpFPqUsh0AR27HfQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm) {
	{
		NI i;
		tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* e;
		tySequence_g8wWagWtbBE4jkij9axgDjA* colontmp_;
		NI i_2;
		i = (NI)0;
		e = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
		colontmp_ = (tySequence_g8wWagWtbBE4jkij9axgDjA*)0;
		colontmp_ = (*vm).Field0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI T4_;
				T4_ = (colontmp_ ? colontmp_->Sup.len : 0);
				if (!(i_2 < T4_)) goto LA3;
				i = i_2;
				e = colontmp_->data[i_2];
				{
					tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA* T9_;
					NI* T10_;
					if (!((*e).Field0 == ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 22))) goto LA7_;
					(*(*vm).Field0->data[i]).Field0 = ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 23);
					T9_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*)0;
					T9_ = (tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) newObj((&NTI_gOxHjz9bS5yarbZPfCpiI9ag_), sizeof(tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA));
					(*T9_).Sup.Sup.m_type = (&NTI_560SkOiRWWBbF6rm9aw64dA_);
					T10_ = (NI*)0;
					T10_ = X5BX5D__0psyqwBtEfcfpLgnMt8iYQ((&(*vm).Field3), (*((tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) ((*(*vm).Field0->data[(NI)(i + ((NI) 1))]).Field1))).value);
					(*T9_).value = ((NF) ((*T10_)));
					asgnRef((void**) (&(*(*vm).Field0->data[(NI)(i + ((NI) 1))]).Field1), &T9_->Sup);
				}
				LA7_: ;
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*, peek_SVMMhbcmdU9bbGmU4y3y9cPA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm) {
	tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* result;
	result = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
	result = (*vm).Field0->data[(*vm).Field4];
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*, pop_sriDR80u76aqeJV4KxrLyQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm) {
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* result;
	tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value;
	NI T6_;
	NI T7_;
{	result = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
	{
		NI T3_;
		T3_ = ((*vm).Field1 ? (*vm).Field1->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		echoBinSafe(TM_RKHCVF7xUfBueKXFrGJGRA_4, 1);
		exit(((NI) 0));
	}
	LA4_: ;
	T6_ = ((*vm).Field1 ? (*vm).Field1->Sup.len : 0);
	value = (*vm).Field1->data[(NI)(T6_ - ((NI) 1))];
	T7_ = ((*vm).Field1 ? (*vm).Field1->Sup.len : 0);
	delete_xVzaGyEHLmq9cWAIfcmhv9ag((&(*vm).Field1), ((NI) ((NI)(T7_ - ((NI) 1)))));
	result = value;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, push_42VJRI9baGwvzSPeFvwV0PQ)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value) {
	NI T1_;
	(*vm).Field1 = (tySequence_49cSLhOXtIXPXzKKaGFU0eQ*) incrSeqV2(&((*vm).Field1)->Sup, sizeof(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*));
	T1_ = (*vm).Field1->Sup.len++;
	asgnRef((void**) (&(*vm).Field1->data[T1_]), value);
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*, advance_SVMMhbcmdU9bbGmU4y3y9cPA_2)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm) {
	tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* result;
{	result = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
	(*vm).Field4 += ((NI) 1);
	result = peek_SVMMhbcmdU9bbGmU4y3y9cPA(vm);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, labelJump_oQz7PD9cSeqOkaoRqQj9b1OA)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* i) {
	NI* T1_;
	T1_ = (NI*)0;
	T1_ = X5BX5D__0psyqwBtEfcfpLgnMt8iYQ((&(*vm).Field3), (*((tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) ((*i).Field1))).value);
	(*vm).Field4 = (*T1_);
}

N_LIB_PRIVATE N_NIMCALL(void, jump_oQz7PD9cSeqOkaoRqQj9b1OA_2)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* i) {
	(*vm).Field4 = ((NI) ((*((tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) ((*i).Field1))).value));
}

N_LIB_PRIVATE N_NIMCALL(void, labelJump_81L7T6SAy1i3aSNYuCvUig)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm, tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ* i) {
	NI* T1_;
	T1_ = (NI*)0;
	T1_ = X5BX5D__0psyqwBtEfcfpLgnMt8iYQ((&(*vm).Field3), (*i).value);
	(*vm).Field4 = (*T1_);
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQinstructions)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQinstructions(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwvm)(NF* x, NF y) {
	(*x) = ((NF)((*x)) - (NF)(y));
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA15_: ;
	result = isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, run_9bi8b66OvH1yopTHTPHnt6Q_2)(tyTuple_M3y5mHl2OtcVFI81N2j0DQ* vm) {
{	{
		while (1) {
			NI T3_;
			tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T4_;
			T3_ = ((*vm).Field0 ? (*vm).Field0->Sup.len : 0);
			if (!((*vm).Field4 < (NI)(T3_ - ((NI) 1)))) goto LA2;
			(*vm).Field4 += ((NI) 1);
			T4_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
			T4_ = peek_SVMMhbcmdU9bbGmU4y3y9cPA(vm);
			switch ((*T4_).Field0) {
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 0):
			{
				goto BeforeRet_;
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 3):
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 4):
			{
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 5):
			{
				tyArray_nHXaesL0DJZHyVS07ARPRA T8_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T9_;
				memset((void*)T8_, 0, sizeof(T8_));
				T9_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T9_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T8_[0] = dollar__7fo3EMB4ZHVOeNHdcmvmHw(T9_);
				echoBinSafe(T8_, 1);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 1):
			{
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T11_;
				T11_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
				T11_ = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, (*T11_).Field1);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 6):
			{
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 2):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T14_;
				T14_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T14_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T14_;
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 7):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T16_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T17_;
				T16_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T16_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T17_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T17_ = negInst_xyQWTytrhLP5sNYraZHgWA(T16_);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T17_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 8):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T19_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T20_;
				T19_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T19_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T20_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T20_ = notInst_xyQWTytrhLP5sNYraZHgWA_2(T19_);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T20_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 9):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T22_;
				a = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T22_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T22_ = orInst_tkSI5SBXwZSvZ7e09bMVKnQ(a, b);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T22_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 10):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_2;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_2;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T24_;
				a_2 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_2 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T24_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T24_ = andInst_tkSI5SBXwZSvZ7e09bMVKnQ_2(a_2, b_2);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T24_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 11):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_3;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_3;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T26_;
				a_3 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_3 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T26_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T26_ = addInst_tkSI5SBXwZSvZ7e09bMVKnQ_3(a_3, b_3);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T26_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 12):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_4;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_4;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T28_;
				a_4 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_4 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T28_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T28_ = subInst_tkSI5SBXwZSvZ7e09bMVKnQ_4(a_4, b_4);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T28_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 13):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_5;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_5;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T30_;
				a_5 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_5 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T30_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T30_ = mulInst_tkSI5SBXwZSvZ7e09bMVKnQ_5(a_5, b_5);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T30_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 14):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_6;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_6;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T32_;
				a_6 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_6 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T32_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T32_ = divInst_tkSI5SBXwZSvZ7e09bMVKnQ_6(a_6, b_6);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T32_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 15):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_7;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_7;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T34_;
				a_7 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_7 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T34_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T34_ = modInst_tkSI5SBXwZSvZ7e09bMVKnQ_7(a_7, b_7);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T34_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 16):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_8;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_8;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T36_;
				a_8 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_8 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T36_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T36_ = eqInst_tkSI5SBXwZSvZ7e09bMVKnQ_8(a_8, b_8);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T36_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 17):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_9;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_9;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T38_;
				a_9 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_9 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T38_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T38_ = neqInst_tkSI5SBXwZSvZ7e09bMVKnQ_9(a_9, b_9);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T38_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 18):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_10;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_10;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T40_;
				a_10 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_10 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T40_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T40_ = gtInst_tkSI5SBXwZSvZ7e09bMVKnQ_10(a_10, b_10);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T40_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 19):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_11;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_11;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T42_;
				a_11 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_11 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T42_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T42_ = gteInst_tkSI5SBXwZSvZ7e09bMVKnQ_11(a_11, b_11);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T42_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 20):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_12;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_12;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T44_;
				a_12 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_12 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T44_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T44_ = ltInst_tkSI5SBXwZSvZ7e09bMVKnQ_12(a_12, b_12);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T44_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 21):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* a_13;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* b_13;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T46_;
				a_13 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				b_13 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T46_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T46_ = lteInst_tkSI5SBXwZSvZ7e09bMVKnQ_13(a_13, b_13);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T46_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 22):
			{
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T48_;
				T48_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
				T48_ = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				labelJump_oQz7PD9cSeqOkaoRqQj9b1OA(vm, T48_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 23):
			{
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T50_;
				T50_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
				T50_ = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				jump_oQz7PD9cSeqOkaoRqQj9b1OA_2(vm, T50_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 28):
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 29):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* arguments;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* endLabel;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* startLabel;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* fun;
				NI T52_;
				NI T53_;
				NI T54_;
				NI T55_;
				tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* T56_;
				NI T57_;
				arguments = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				endLabel = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				startLabel = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T52_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				fun = funInst_q277MmzO36qhOVSX572bog(startLabel, (*vm).Field2->data[(NI)(T52_ - ((NI) 1))], ((NI) ((*((tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) (arguments))).value)));
				T53_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				X5BX5Deq__HW88TTiOGEbkbPlPS00naA((&(*(*vm).Field2->data[(NI)(T53_ - ((NI) 1))]).Field0), ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_6), fun);
				T54_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				T55_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				T56_ = (tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*)0;
				T56_ = newFrame_nfe2NsS0Jn8q3iozdCF9c8g((*(*vm).Field2->data[(NI)(T54_ - ((NI) 1))]).Field1, (*(*vm).Field2->data[(NI)(T55_ - ((NI) 1))]).Field0);
				(*vm).Field2 = (tySequence_rl1wTgiGRBZamH1pllm1bA*) incrSeqV2(&((*vm).Field2)->Sup, sizeof(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*));
				T57_ = (*vm).Field2->Sup.len++;
				asgnRef((void**) (&(*vm).Field2->data[T57_]), T56_);
				{
					tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T60_;
					T60_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
					T60_ = peek_SVMMhbcmdU9bbGmU4y3y9cPA(vm);
					if (!((*T60_).Field0 == ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 28))) goto LA61_;
					push_42VJRI9baGwvzSPeFvwV0PQ(vm, fun);
				}
				LA61_: ;
				labelJump_81L7T6SAy1i3aSNYuCvUig(vm, ((tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) (endLabel)));
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 30):
			{
				NI arguments_2;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T64_;
				tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA* fun_2;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T65_;
				tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* T74_;
				NI T75_;
				NI* T76_;
				T64_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T64_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				arguments_2 = ((NI) ((*((tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) (T64_))).value));
				T65_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T65_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				fun_2 = ((tyObject_FunctionValuecolonObjectType__FIkPLrBpEJy6rtwh9bFNTRA*) (T65_));
				{
					tyArray_nHXaesL0DJZHyVS07ARPRA T70_;
					NimStringDesc* T71_;
					NimStringDesc* T72_;
					NimStringDesc* T73_;
					if (!!((arguments_2 == (*fun_2).arguments))) goto LA68_;
					memset((void*)T70_, 0, sizeof(T70_));
					T71_ = (NimStringDesc*)0;
					T72_ = (NimStringDesc*)0;
					T72_ = nimIntToStr((*fun_2).arguments);
					T73_ = (NimStringDesc*)0;
					T73_ = nimIntToStr(arguments_2);
					T71_ = rawNewString(T72_->Sup.len + T73_->Sup.len + 48);
appendString(T71_, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_7));
appendString(T71_, T72_);
appendString(T71_, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_8));
appendString(T71_, T73_);
appendString(T71_, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_9));
					T70_[0] = T71_;
					echoBinSafe(T70_, 1);
					exit(((NI) 0));
				}
				LA68_: ;
				T74_ = (tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*)0;
				T74_ = newFrame_nfe2NsS0Jn8q3iozdCF9c8g((*vm).Field4, (*(*fun_2).frame).Field0);
				(*vm).Field2 = (tySequence_rl1wTgiGRBZamH1pllm1bA*) incrSeqV2(&((*vm).Field2)->Sup, sizeof(tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg*));
				T75_ = (*vm).Field2->Sup.len++;
				asgnRef((void**) (&(*vm).Field2->data[T75_]), T74_);
				T76_ = (NI*)0;
				T76_ = X5BX5D__0psyqwBtEfcfpLgnMt8iYQ((&(*vm).Field3), (*fun_2).label);
				(*vm).Field4 = (*T76_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 24):
			{
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* inst;
				inst = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				{
					tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T80_;
					NIM_BOOL T81_;
					T80_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
					T80_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
					T81_ = (NIM_BOOL)0;
					T81_ = branchtInst_Ta7UGXfYpipiP2t82lLQyg(T80_);
					if (!T81_) goto LA82_;
					labelJump_oQz7PD9cSeqOkaoRqQj9b1OA(vm, inst);
				}
				LA82_: ;
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 25):
			{
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* inst_2;
				inst_2 = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				{
					tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T87_;
					NIM_BOOL T88_;
					T87_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
					T87_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
					T88_ = (NIM_BOOL)0;
					T88_ = branchfInst_Ta7UGXfYpipiP2t82lLQyg_2(T87_);
					if (!T88_) goto LA89_;
					labelJump_oQz7PD9cSeqOkaoRqQj9b1OA(vm, inst_2);
				}
				LA89_: ;
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 26):
			{
				NimStringDesc* value;
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T92_;
				NI T97_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T98_;
				T92_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
				T92_ = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				value = (*((tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) ((*T92_).Field1))).value;
				{
					if (!eqStrings(value, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_6))) goto LA95_;
					echoBinSafe(TM_RKHCVF7xUfBueKXFrGJGRA_10, 1);
					exit(((NI) 0));
				}
				LA95_: ;
				T97_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				T98_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T98_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				X5BX5Deq__HW88TTiOGEbkbPlPS00naA((&(*(*vm).Field2->data[(NI)(T97_ - ((NI) 1))]).Field0), value, T98_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 27):
			{
				NimStringDesc* key;
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T100_;
				tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* frame;
				NI T101_;
				T100_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
				T100_ = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				key = (*((tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) ((*T100_).Field1))).value;
				T101_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				frame = (*vm).Field2->data[(NI)(T101_ - ((NI) 1))];
				{
					NIM_BOOL T104_;
					tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw** T107_;
					T104_ = (NIM_BOOL)0;
					T104_ = hasKey_eVs19ak9bLDMU8DCGg32t3aQ((*frame).Field0, key);
					if (!T104_) goto LA105_;
					T107_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw**)0;
					T107_ = X5BX5D__BTFIz0ITK8bF3RR5rKqcDg((&(*frame).Field0), key);
					push_42VJRI9baGwvzSPeFvwV0PQ(vm, (*T107_));
				}
				goto LA102_;
				LA105_: ;
				{
					tyArray_nHXaesL0DJZHyVS07ARPRA T109_;
					NimStringDesc* T110_;
					memset((void*)T109_, 0, sizeof(T109_));
					T110_ = (NimStringDesc*)0;
					T110_ = rawNewString(key->Sup.len + 19);
appendString(T110_, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_12));
appendString(T110_, key);
					T109_[0] = T110_;
					echoBinSafe(T109_, 1);
					exit(((NI) 0));
				}
				LA102_: ;
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 34):
			{
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 31):
			{
				NI pc;
				NI T113_;
				NI T114_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T115_;
				T113_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				pc = (*(*vm).Field2->data[(NI)(T113_ - ((NI) 1))]).Field1;
				T114_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				delete_ZcgKNNy8O3y2vsPS1KBnvA((&(*vm).Field2), ((NI) ((NI)(T114_ - ((NI) 1)))));
				(*vm).Field4 = pc;
				T115_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T115_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T115_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 35):
			{
				tySequence_49cSLhOXtIXPXzKKaGFU0eQ* values;
				NF num;
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T117_;
				tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ* T122_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T123_;
				values = (tySequence_49cSLhOXtIXPXzKKaGFU0eQ*) newSeq((&NTI_49cSLhOXtIXPXzKKaGFU0eQ_), 0);
				T117_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
				T117_ = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				num = (*((tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) ((*T117_).Field1))).value;
				{
					while (1) {
						tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T120_;
						NI T121_;
						if (!(0.0 < num)) goto LA119;
						T120_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
						T120_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
						values = (tySequence_49cSLhOXtIXPXzKKaGFU0eQ*) incrSeqV2(&(values)->Sup, sizeof(tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*));
						T121_ = values->Sup.len++;
						asgnRef((void**) (&values->data[T121_]), T120_);
						minuseq__7kHiltrvRlcg6wSYR3CxAwvm((&num), 1.0000000000000000e+00);
					} LA119: ;
				}
				T122_ = (tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ*)0;
				T122_ = (tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ*) newObj((&NTI_mW8phZov9cHZwUtCe8U2gZw_), sizeof(tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ));
				(*T122_).Sup.Sup.m_type = (&NTI_noD08ztngGqjHZ7t6Rl9aiQ_);
				genericSeqAssign((&(*T122_).values), values, (&NTI_49cSLhOXtIXPXzKKaGFU0eQ_));
				T123_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T123_ = &T122_->Sup;
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T123_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 36):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T125_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T126_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T127_;
				T125_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T125_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T126_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T126_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T127_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T127_ = accessInst_W9abjXu3cyh9c9bRLmF7ZdZkA(T125_, T126_);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T127_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 37):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T129_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T130_;
				T129_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T129_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T130_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T130_ = lenInst_xyQWTytrhLP5sNYraZHgWA_3(T129_);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T130_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 38):
			{
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T132_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T133_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* T134_;
				T132_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T132_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T133_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T133_ = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T134_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw*)0;
				T134_ = pushListInst_cO9cPN0psHDTy8Oz9bxU5oyg(T132_, T133_);
				push_42VJRI9baGwvzSPeFvwV0PQ(vm, T134_);
			}
			break;
			case ((tyEnum_InstructionKind_wzzqsNRSFKQWlUMuy1TJiw) 39):
			{
				tyTuple_r4JoVxlxeWnXF9cuRoe3Jtg* frame_2;
				NI T136_;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* value_2;
				tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw* index;
				NimStringDesc* variable;
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T137_;
				T136_ = ((*vm).Field2 ? (*vm).Field2->Sup.len : 0);
				frame_2 = (*vm).Field2->data[(NI)(T136_ - ((NI) 1))];
				value_2 = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				index = pop_sriDR80u76aqeJV4KxrLyQ(vm);
				T137_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
				T137_ = advance_SVMMhbcmdU9bbGmU4y3y9cPA_2(vm);
				variable = (*((tyObject_StringValuecolonObjectType__PO9bUMXtlWXaezrslbDbWhQ*) ((*T137_).Field1))).value;
				{
					NIM_BOOL T140_;
					tyArray_nHXaesL0DJZHyVS07ARPRA T143_;
					NimStringDesc* T144_;
					T140_ = (NIM_BOOL)0;
					T140_ = hasKey_eVs19ak9bLDMU8DCGg32t3aQ((*frame_2).Field0, variable);
					if (!!(T140_)) goto LA141_;
					memset((void*)T143_, 0, sizeof(T143_));
					T144_ = (NimStringDesc*)0;
					T144_ = rawNewString(variable->Sup.len + 19);
appendString(T144_, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_12));
appendString(T144_, variable);
					T143_[0] = T144_;
					echoBinSafe(T143_, 1);
					exit(((NI) 0));
				}
				LA141_: ;
				{
					NIM_BOOL T147_;
					tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw** T149_;
					tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ* list;
					tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw** T152_;
					NI i;
					T147_ = (NIM_BOOL)0;
					T147_ = ((index) && (isObjWithCache((*index).Sup.m_type, (&NTI_560SkOiRWWBbF6rm9aw64dA_), Nim_OfCheck_CACHE14)));
					if (!(T147_)) goto LA148_;
					T149_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw**)0;
					T149_ = X5BX5D__BTFIz0ITK8bF3RR5rKqcDg((&(*frame_2).Field0), variable);
					T147_ = (((*T149_)) && (isObjWithCache((*(*T149_)).Sup.m_type, (&NTI_noD08ztngGqjHZ7t6Rl9aiQ_), Nim_OfCheck_CACHE15)));
					LA148_: ;
					if (!T147_) goto LA150_;
					T152_ = (tyObject_ValuecolonObjectType__73JSczcdor7tTS06v9cHOZw**)0;
					T152_ = X5BX5D__BTFIz0ITK8bF3RR5rKqcDg((&(*frame_2).Field0), variable);
					list = ((tyObject_ListValuecolonObjectType__noD08ztngGqjHZ7t6Rl9aiQ*) ((*T152_)));
					i = ((NI) ((*((tyObject_NumberValuecolonObjectType__560SkOiRWWBbF6rm9aw64dA*) (index))).value));
					{
						NIM_BOOL T155_;
						NI T156_;
						tyArray_nHXaesL0DJZHyVS07ARPRA T160_;
						NimStringDesc* T161_;
						NimStringDesc* T162_;
						T155_ = (NIM_BOOL)0;
						T156_ = ((*list).values ? (*list).values->Sup.len : 0);
						T155_ = ((NI)(T156_ - ((NI) 1)) < i);
						if (T155_) goto LA157_;
						T155_ = (i < ((NI) 0));
						LA157_: ;
						if (!T155_) goto LA158_;
						memset((void*)T160_, 0, sizeof(T160_));
						T161_ = (NimStringDesc*)0;
						T162_ = (NimStringDesc*)0;
						T162_ = nimIntToStr(i);
						T161_ = rawNewString(T162_->Sup.len + 16);
appendString(T161_, T162_);
appendString(T161_, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_15));
						T160_[0] = T161_;
						echoBinSafe(T160_, 1);
						exit(((NI) 0));
					}
					LA158_: ;
					asgnRef((void**) (&(*list).values->data[i]), value_2);
				}
				goto LA145_;
				LA150_: ;
				{
					echoBinSafe(TM_RKHCVF7xUfBueKXFrGJGRA_16, 1);
					exit(((NI) 0));
				}
				LA145_: ;
			}
			break;
			default:
			{
				tyArray_nHXaesL0DJZHyVS07ARPRA T165_;
				NimStringDesc* T166_;
				tyTuple_p7Uw0BAWm1JV3F8w0mhMOA* T167_;
				memset((void*)T165_, 0, sizeof(T165_));
				T166_ = (NimStringDesc*)0;
				T167_ = (tyTuple_p7Uw0BAWm1JV3F8w0mhMOA*)0;
				T167_ = peek_SVMMhbcmdU9bbGmU4y3y9cPA(vm);
				T166_ = rawNewString(reprEnum((NI)(*T167_).Field0, (&NTI_wzzqsNRSFKQWlUMuy1TJiw_))->Sup.len + 18);
appendString(T166_, ((NimStringDesc*) &TM_RKHCVF7xUfBueKXFrGJGRA_18));
appendString(T166_, reprEnum((NI)(*T167_).Field0, (&NTI_wzzqsNRSFKQWlUMuy1TJiw_)));
				T165_[0] = T166_;
				echoBinSafe(T165_, 1);
				exit(((NI) 0));
			}
			break;
			}
		} LA2: ;
	}
	}BeforeRet_: ;
}
NIM_EXTERNC N_NOINLINE(void, unknown_vmInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_vmDatInit000)(void) {
static TNimNode* TM_RKHCVF7xUfBueKXFrGJGRA_3[6];
static TNimNode TM_RKHCVF7xUfBueKXFrGJGRA_0[7];
NTI_M3y5mHl2OtcVFI81N2j0DQ_.size = sizeof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ);
NTI_M3y5mHl2OtcVFI81N2j0DQ_.kind = 18;
NTI_M3y5mHl2OtcVFI81N2j0DQ_.base = 0;
TM_RKHCVF7xUfBueKXFrGJGRA_3[0] = &TM_RKHCVF7xUfBueKXFrGJGRA_0[1];
TM_RKHCVF7xUfBueKXFrGJGRA_0[1].kind = 1;
TM_RKHCVF7xUfBueKXFrGJGRA_0[1].offset = offsetof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ, Field0);
TM_RKHCVF7xUfBueKXFrGJGRA_0[1].typ = (&NTI_g8wWagWtbBE4jkij9axgDjA_);
TM_RKHCVF7xUfBueKXFrGJGRA_0[1].name = "Field0";
TM_RKHCVF7xUfBueKXFrGJGRA_3[1] = &TM_RKHCVF7xUfBueKXFrGJGRA_0[2];
NTI_49cSLhOXtIXPXzKKaGFU0eQ_.size = sizeof(tySequence_49cSLhOXtIXPXzKKaGFU0eQ*);
NTI_49cSLhOXtIXPXzKKaGFU0eQ_.kind = 24;
NTI_49cSLhOXtIXPXzKKaGFU0eQ_.base = (&NTI_9a9cRvMBGWDRFk9av9bTYiXvsg_);
NTI_49cSLhOXtIXPXzKKaGFU0eQ_.marker = Marker_tySequence_49cSLhOXtIXPXzKKaGFU0eQ;
TM_RKHCVF7xUfBueKXFrGJGRA_0[2].kind = 1;
TM_RKHCVF7xUfBueKXFrGJGRA_0[2].offset = offsetof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ, Field1);
TM_RKHCVF7xUfBueKXFrGJGRA_0[2].typ = (&NTI_49cSLhOXtIXPXzKKaGFU0eQ_);
TM_RKHCVF7xUfBueKXFrGJGRA_0[2].name = "Field1";
TM_RKHCVF7xUfBueKXFrGJGRA_3[2] = &TM_RKHCVF7xUfBueKXFrGJGRA_0[3];
NTI_rl1wTgiGRBZamH1pllm1bA_.size = sizeof(tySequence_rl1wTgiGRBZamH1pllm1bA*);
NTI_rl1wTgiGRBZamH1pllm1bA_.kind = 24;
NTI_rl1wTgiGRBZamH1pllm1bA_.base = (&NTI_ZJnTpp110EyOkSiqN7Yliw_);
NTI_rl1wTgiGRBZamH1pllm1bA_.marker = Marker_tySequence_rl1wTgiGRBZamH1pllm1bA;
TM_RKHCVF7xUfBueKXFrGJGRA_0[3].kind = 1;
TM_RKHCVF7xUfBueKXFrGJGRA_0[3].offset = offsetof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ, Field2);
TM_RKHCVF7xUfBueKXFrGJGRA_0[3].typ = (&NTI_rl1wTgiGRBZamH1pllm1bA_);
TM_RKHCVF7xUfBueKXFrGJGRA_0[3].name = "Field2";
TM_RKHCVF7xUfBueKXFrGJGRA_3[3] = &TM_RKHCVF7xUfBueKXFrGJGRA_0[4];
TM_RKHCVF7xUfBueKXFrGJGRA_0[4].kind = 1;
TM_RKHCVF7xUfBueKXFrGJGRA_0[4].offset = offsetof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ, Field3);
TM_RKHCVF7xUfBueKXFrGJGRA_0[4].typ = (&NTI_zjMaDBasw1LnKbj11akpfw_);
TM_RKHCVF7xUfBueKXFrGJGRA_0[4].name = "Field3";
TM_RKHCVF7xUfBueKXFrGJGRA_3[4] = &TM_RKHCVF7xUfBueKXFrGJGRA_0[5];
TM_RKHCVF7xUfBueKXFrGJGRA_0[5].kind = 1;
TM_RKHCVF7xUfBueKXFrGJGRA_0[5].offset = offsetof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ, Field4);
TM_RKHCVF7xUfBueKXFrGJGRA_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_RKHCVF7xUfBueKXFrGJGRA_0[5].name = "Field4";
TM_RKHCVF7xUfBueKXFrGJGRA_3[5] = &TM_RKHCVF7xUfBueKXFrGJGRA_0[6];
TM_RKHCVF7xUfBueKXFrGJGRA_0[6].kind = 1;
TM_RKHCVF7xUfBueKXFrGJGRA_0[6].offset = offsetof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ, Field5);
TM_RKHCVF7xUfBueKXFrGJGRA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_RKHCVF7xUfBueKXFrGJGRA_0[6].name = "Field5";
TM_RKHCVF7xUfBueKXFrGJGRA_0[0].len = 6; TM_RKHCVF7xUfBueKXFrGJGRA_0[0].kind = 2; TM_RKHCVF7xUfBueKXFrGJGRA_0[0].sons = &TM_RKHCVF7xUfBueKXFrGJGRA_3[0];
NTI_M3y5mHl2OtcVFI81N2j0DQ_.node = &TM_RKHCVF7xUfBueKXFrGJGRA_0[0];
NTI_ORWQUtasKGvy7C2tIe1dcg_.size = sizeof(tyTuple_M3y5mHl2OtcVFI81N2j0DQ*);
NTI_ORWQUtasKGvy7C2tIe1dcg_.kind = 22;
NTI_ORWQUtasKGvy7C2tIe1dcg_.base = (&NTI_M3y5mHl2OtcVFI81N2j0DQ_);
NTI_ORWQUtasKGvy7C2tIe1dcg_.marker = Marker_tyRef_ORWQUtasKGvy7C2tIe1dcg;
}

