/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files (x86)\Nim\lib" -o C:\Users\soc\Documents\UPC\TFG_NIM\nimcache\lexer.o C:\Users\soc\Documents\UPC\TFG_NIM\nimcache\lexer.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Lexer_ddvkox66wCZM9cHu9at9bYq6g tyObject_Lexer_ddvkox66wCZM9cHu9at9bYq6g;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_PfNvNze9askwnDI5DEBi7uA tySequence_PfNvNze9askwnDI5DEBi7uA;
typedef struct tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Lexer_ddvkox66wCZM9cHu9at9bYq6g {
NimStringDesc* source;
tySequence_PfNvNze9askwnDI5DEBi7uA* tokens;
NI start;
NI current;
NI line;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_tokens_0utjJWHI9bII0BHrTbbRyUQ;
struct tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw {
  RootObj Sup;
tyEnum_tokens_0utjJWHI9bII0BHrTbbRyUQ tType;
NimStringDesc* tLexeme;
NI line;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tySequence_PfNvNze9askwnDI5DEBi7uA {
  TGenericSeq Sup;
  tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAtEnd_1OorNChr2G49cchjNPbaDhQ)(tyObject_Lexer_ddvkox66wCZM9cHu9at9bYq6g* lexer);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_PfNvNze9askwnDI5DEBi7uA*, scan_SuYwU9b9cWghqOiBjP6dxwGA)(tyObject_Lexer_ddvkox66wCZM9cHu9at9bYq6g* lexer);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_PfNvNze9askwnDI5DEBi7uA)(void* p, NI op);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_aBhdX4GThuHBbVT9cCpiB9cw_;
TNimType NTI_PfNvNze9askwnDI5DEBi7uA_;
STRING_LITERAL(TM_LGhhYqHVISrBY59b6oZtR9bA_2, "", 0);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAtEnd_1OorNChr2G49cchjNPbaDhQ)(tyObject_Lexer_ddvkox66wCZM9cHu9at9bYq6g* lexer) {
	NIM_BOOL result;
	nimfr_("isAtEnd", "lexer.nim");
{	result = (NIM_BOOL)0;
	nimln_(10, "lexer.nim");
	result = (((*lexer).source ? (*lexer).source->Sup.len : 0) <= (*lexer).current);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_PfNvNze9askwnDI5DEBi7uA)(void* p, NI op) {
	tySequence_PfNvNze9askwnDI5DEBi7uA* a;
	NI T1_;
	a = (tySequence_PfNvNze9askwnDI5DEBi7uA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].tLexeme, op);
	}
}

N_LIB_PRIVATE N_NIMCALL(tySequence_PfNvNze9askwnDI5DEBi7uA*, scan_SuYwU9b9cWghqOiBjP6dxwGA)(tyObject_Lexer_ddvkox66wCZM9cHu9at9bYq6g* lexer) {
	tySequence_PfNvNze9askwnDI5DEBi7uA* result;
	tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw T4_;
	NI T5_;
	nimfr_("scan", "lexer.nim");
{	result = (tySequence_PfNvNze9askwnDI5DEBi7uA*)0;
	nimln_(14, "lexer.nim");
	(*lexer).line = ((NI) 1);
	nimln_(15, "lexer.nim");
	(*lexer).start = ((NI) 0);
	nimln_(16, "lexer.nim");
	(*lexer).current = ((NI) 0);
	{
		nimln_(19, "lexer.nim");
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = isAtEnd_1OorNChr2G49cchjNPbaDhQ((&(*lexer)));
			if (!!(T3_)) goto LA2;
			nimln_(20, "lexer.nim");
			(*lexer).start = (*lexer).current;
		} LA2: ;
	}
	nimln_(22, "lexer.nim");
	memset((void*)(&T4_), 0, sizeof(T4_));
	T4_.Sup.m_type = (&NTI_aBhdX4GThuHBbVT9cCpiB9cw_);
	memset((void*)(&T4_), 0, sizeof(T4_));
	T4_.Sup.m_type = (&NTI_aBhdX4GThuHBbVT9cCpiB9cw_);
	T4_.tType = ((tyEnum_tokens_0utjJWHI9bII0BHrTbbRyUQ) 38);
	T4_.tLexeme = copyString(((NimStringDesc*) &TM_LGhhYqHVISrBY59b6oZtR9bA_2));
	T4_.line = (*lexer).line;
	(*lexer).tokens = (tySequence_PfNvNze9askwnDI5DEBi7uA*) incrSeqV2(&((*lexer).tokens)->Sup, sizeof(tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw));
	T5_ = (*lexer).tokens->Sup.len++;
	genericAssign((void*)(&(*lexer).tokens->data[T5_]), (void*)(&T4_), (&NTI_aBhdX4GThuHBbVT9cCpiB9cw_));
	nimln_(23, "lexer.nim");
	genericSeqAssign((&result), (*lexer).tokens, (&NTI_PfNvNze9askwnDI5DEBi7uA_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_lexerInit000)(void) {
	nimfr_("lexer", "lexer.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_lexerDatInit000)(void) {
NTI_PfNvNze9askwnDI5DEBi7uA_.size = sizeof(tySequence_PfNvNze9askwnDI5DEBi7uA*);
NTI_PfNvNze9askwnDI5DEBi7uA_.kind = 24;
NTI_PfNvNze9askwnDI5DEBi7uA_.base = (&NTI_aBhdX4GThuHBbVT9cCpiB9cw_);
NTI_PfNvNze9askwnDI5DEBi7uA_.marker = Marker_tySequence_PfNvNze9askwnDI5DEBi7uA;
}

