/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -I"C:\Program Files (x86)\Nim\lib" -o C:\Users\soc\Documents\UPC\TFG_NIM\nimcache\tokens.o C:\Users\soc\Documents\UPC\TFG_NIM\nimcache\tokens.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_tokens_0utjJWHI9bII0BHrTbbRyUQ;
struct tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw {
  RootObj Sup;
tyEnum_tokens_0utjJWHI9bII0BHrTbbRyUQ tType;
NimStringDesc* tLexeme;
NI line;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__KUyqqOp3BSFcWxmN6pdKTw)(tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw* token);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_0utjJWHI9bII0BHrTbbRyUQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_aBhdX4GThuHBbVT9cCpiB9cw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
STRING_LITERAL(TM_xDlB0WHPxJhXV9ckv5nm5Og_2, "TOKEN(", 6);
STRING_LITERAL(TM_xDlB0WHPxJhXV9ckv5nm5Og_6, ", ", 2);
STRING_LITERAL(TM_xDlB0WHPxJhXV9ckv5nm5Og_7, ": ", 2);
STRING_LITERAL(TM_xDlB0WHPxJhXV9ckv5nm5Og_8, ")", 1);

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__KUyqqOp3BSFcWxmN6pdKTw)(tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw* token) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("$", "tokens.nim");
{	result = (NimStringDesc*)0;
	nimln_(28, "tokens.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr((*token).line);
	T1_ = rawNewString(reprEnum((NI)(*token).tType, (&NTI_0utjJWHI9bII0BHrTbbRyUQ_))->Sup.len + (*token).tLexeme->Sup.len + T2_->Sup.len + 11);
appendString(T1_, ((NimStringDesc*) &TM_xDlB0WHPxJhXV9ckv5nm5Og_2));
appendString(T1_, reprEnum((NI)(*token).tType, (&NTI_0utjJWHI9bII0BHrTbbRyUQ_)));
appendString(T1_, ((NimStringDesc*) &TM_xDlB0WHPxJhXV9ckv5nm5Og_6));
appendString(T1_, (*token).tLexeme);
appendString(T1_, ((NimStringDesc*) &TM_xDlB0WHPxJhXV9ckv5nm5Og_7));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_xDlB0WHPxJhXV9ckv5nm5Og_8));
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_tokensInit000)(void) {
	nimfr_("tokens", "tokens.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_tokensDatInit000)(void) {
static TNimNode* TM_xDlB0WHPxJhXV9ckv5nm5Og_3[39];
NI TM_xDlB0WHPxJhXV9ckv5nm5Og_5;
static char* NIM_CONST TM_xDlB0WHPxJhXV9ckv5nm5Og_4[39] = {
"LEFT_PAREN", 
"RIGHT_PAREN", 
"LEFT_BRACE", 
"RIGHT_BRACE", 
"COMMA", 
"DOT", 
"MINUS", 
"PLUS", 
"SEMICOLON", 
"SLASH", 
"STAR", 
"BANG", 
"BANG_EQUAL", 
"EQUAL", 
"EQUAL_EQUAL", 
"GREATER", 
"GREATER_EQUAL", 
"LESS", 
"LESS_EQUAL", 
"IDENTIFIER", 
"STRING", 
"NUMBER", 
"AND", 
"CLASS", 
"ELSE", 
"FALSE", 
"FUN", 
"FOR", 
"IF", 
"NIL", 
"OR", 
"PRINT", 
"RETURN", 
"SUPER", 
"THIS", 
"TRUE", 
"VAR", 
"WHILE", 
"EOF"};
static TNimNode* TM_xDlB0WHPxJhXV9ckv5nm5Og_9[3];
static TNimNode TM_xDlB0WHPxJhXV9ckv5nm5Og_0[44];
NTI_0utjJWHI9bII0BHrTbbRyUQ_.size = sizeof(tyEnum_tokens_0utjJWHI9bII0BHrTbbRyUQ);
NTI_0utjJWHI9bII0BHrTbbRyUQ_.kind = 14;
NTI_0utjJWHI9bII0BHrTbbRyUQ_.base = 0;
NTI_0utjJWHI9bII0BHrTbbRyUQ_.flags = 3;
for (TM_xDlB0WHPxJhXV9ckv5nm5Og_5 = 0; TM_xDlB0WHPxJhXV9ckv5nm5Og_5 < 39; TM_xDlB0WHPxJhXV9ckv5nm5Og_5++) {
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[TM_xDlB0WHPxJhXV9ckv5nm5Og_5+0].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[TM_xDlB0WHPxJhXV9ckv5nm5Og_5+0].offset = TM_xDlB0WHPxJhXV9ckv5nm5Og_5;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[TM_xDlB0WHPxJhXV9ckv5nm5Og_5+0].name = TM_xDlB0WHPxJhXV9ckv5nm5Og_4[TM_xDlB0WHPxJhXV9ckv5nm5Og_5];
TM_xDlB0WHPxJhXV9ckv5nm5Og_3[TM_xDlB0WHPxJhXV9ckv5nm5Og_5] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[TM_xDlB0WHPxJhXV9ckv5nm5Og_5+0];
}
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[39].len = 39; TM_xDlB0WHPxJhXV9ckv5nm5Og_0[39].kind = 2; TM_xDlB0WHPxJhXV9ckv5nm5Og_0[39].sons = &TM_xDlB0WHPxJhXV9ckv5nm5Og_3[0];
NTI_0utjJWHI9bII0BHrTbbRyUQ_.node = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[39];
NTI_aBhdX4GThuHBbVT9cCpiB9cw_.size = sizeof(tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw);
NTI_aBhdX4GThuHBbVT9cCpiB9cw_.kind = 17;
NTI_aBhdX4GThuHBbVT9cCpiB9cw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_xDlB0WHPxJhXV9ckv5nm5Og_9[0] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[41];
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[41].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[41].offset = offsetof(tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw, tType);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[41].typ = (&NTI_0utjJWHI9bII0BHrTbbRyUQ_);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[41].name = "tType";
TM_xDlB0WHPxJhXV9ckv5nm5Og_9[1] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42];
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42].offset = offsetof(tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw, tLexeme);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[42].name = "tLexeme";
TM_xDlB0WHPxJhXV9ckv5nm5Og_9[2] = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43];
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43].kind = 1;
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43].offset = offsetof(tyObject_Token_aBhdX4GThuHBbVT9cCpiB9cw, line);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[43].name = "line";
TM_xDlB0WHPxJhXV9ckv5nm5Og_0[40].len = 3; TM_xDlB0WHPxJhXV9ckv5nm5Og_0[40].kind = 2; TM_xDlB0WHPxJhXV9ckv5nm5Og_0[40].sons = &TM_xDlB0WHPxJhXV9ckv5nm5Og_9[0];
NTI_aBhdX4GThuHBbVT9cCpiB9cw_.node = &TM_xDlB0WHPxJhXV9ckv5nm5Og_0[40];
}

